In [121]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
%pip install pyarrow

Requirement already satisfied: pyarrow in /opt/anaconda3/lib/python3.13/site-packages (19.0.0)
Note: you may need to restart the kernel to use updated packages.

# Preparamos las 8 tablas anuales originales

In [122]:
# Empezamos con las tablas originales con id_fila_og ya asignado desde los archivos Excel

In [123]:
from pathlib import Path

DATOS = Path("..") / "datos"

In [124]:
og_17 = pd.read_excel(DATOS / "procesados" / "etiquetados" / "Copia de ANEXO TRASLADOS 2017 INFOMEX 0863.xlsx", header = 1)
og_18 = pd.read_excel(DATOS / "procesados" / "etiquetados" / "Copia de ANEXO TRASLADOS 2018 INFOMEX 0863.xlsx", header = 1)
og_19 = pd.read_excel(DATOS / "procesados" / "etiquetados" / "Copia de ANEXO TRASLADOS 2019 INFOMEX 0863.xlsx", header = 1)
og_20 = pd.read_excel(DATOS / "procesados" / "etiquetados" / "Copia de ANEXO TRASLADOS 2020 INFOMEX 0863.xlsx", header = 1)
og_21 = pd.read_excel(DATOS / "procesados" / "etiquetados" / "Copia de ANEXO TRASLADOS 2021 INFOMEX 0863.xlsx", header = 1)
og_22 = pd.read_excel(DATOS / "procesados" / "etiquetados" / "Copia de ANEXO TRASLADOS 2022 INFOMEX 0863.xlsx", header = 1)
og_23 = pd.read_excel(DATOS / "procesados" / "etiquetados" / "Copia de ANEXO TRASLADOS 2023 INFOMEX 0863.xlsx", header = 1)
og_24 = pd.read_excel(DATOS / "procesados" / "etiquetados" / "Copia de ANEXO TRASLADOS 2024 INFOMEX 0863.xlsx", header = 1)

### En cada tabla anual, asignamos los nombres de las columnas para que sean uniformes 
### También agregamos la columna de year (año), y quitamos columnas de scratch

In [125]:
print(og_17.columns.tolist())

['Unnamed: 0', 'Oficina de Representación del INM', 'Lugar de origen', 'Lugar de destino ', 'Total de migrantes en traslado', 'Nacionalidad ', 'Hombres', 'Mujeres', 'Niñas', 'Niños']

In [126]:
og_17 = og_17.rename(columns={'Unnamed: 0': 'id_fila_og', 'Oficina de Representación del INM': 'oficina_regional', 'Lugar de origen': 'lugar_origen', 'Lugar de destino ': 'lugar_destino', 'Total de migrantes en traslado': 'total_migrantes_traslado', 'Nacionalidad ': 'nacionalidad', 'Hombres': 'hombres', 'Mujeres': 'mujeres', 'Niñas':'niñas', 'Niños':'niños'})
og_17['year'] = 2017
print(og_17.columns.tolist())

['id_fila_og', 'oficina_regional', 'lugar_origen', 'lugar_destino', 'total_migrantes_traslado', 'nacionalidad', 'hombres', 'mujeres', 'niñas', 'niños', 'year']

In [127]:
print(og_18.columns.tolist())

['id', 'Oficina de Representación  del INM', 'Lugar de origen', 'Lugar de destino ', 'Total de migrantes en traslado', 'Nacionalidad ', 'Hombres', 'Mujeres', 'Niñas', 'Niños']

In [128]:
og_18 = og_18.rename(columns={'id': 'id_fila_og', 'Oficina de Representación  del INM': 'oficina_regional', 'Lugar de origen': 'lugar_origen', 'Lugar de destino ': 'lugar_destino', 'Total de migrantes en traslado': 'total_migrantes_traslado', 'Nacionalidad ': 'nacionalidad', 'Hombres': 'hombres', 'Mujeres': 'mujeres', 'Niñas':'niñas', 'Niños':'niños'})
og_18['year'] = 2018
print(og_18.columns.tolist())

['id_fila_og', 'oficina_regional', 'lugar_origen', 'lugar_destino', 'total_migrantes_traslado', 'nacionalidad', 'hombres', 'mujeres', 'niñas', 'niños', 'year']

In [129]:
print(og_19.columns.tolist())

['id', 'Ofina de Representación del INM ', 'Lugar de origen', 'Lugar de destino ', 'Total de migrantes en traslado', 'Nacionalidad ', 'Hombres', 'Mujeres', 'Niñas', 'Niños']

In [130]:
og_19 = og_19.rename(columns={'id': 'id_fila_og', 'Ofina de Representación del INM ': 'oficina_regional', 'Lugar de origen': 'lugar_origen', 'Lugar de destino ': 'lugar_destino', 'Total de migrantes en traslado': 'total_migrantes_traslado', 'Nacionalidad ': 'nacionalidad', 'Hombres': 'hombres', 'Mujeres': 'mujeres', 'Niñas':'niñas', 'Niños':'niños'})
og_19['year'] = 2019
print(og_19.columns.tolist())

['id_fila_og', 'oficina_regional', 'lugar_origen', 'lugar_destino', 'total_migrantes_traslado', 'nacionalidad', 'hombres', 'mujeres', 'niñas', 'niños', 'year']

In [131]:
print(og_20.columns.tolist())

['Unnamed: 0', 'Oficina de Representación del INM', 'Lugar de origen', 'Lugar de destino ', 'Total de migrantes en traslado', 'Nacionalidad ', 'Hombres', 'Mujeres', 'Niñas', 'Niños', 'Unnamed: 10']

In [132]:
og_20 = og_20.rename(columns={'Unnamed: 0': 'id_fila_og', 'Oficina de Representación del INM': 'oficina_regional', 'Lugar de origen': 'lugar_origen', 'Lugar de destino ': 'lugar_destino', 'Total de migrantes en traslado': 'total_migrantes_traslado', 'Nacionalidad ': 'nacionalidad', 'Hombres': 'hombres', 'Mujeres': 'mujeres', 'Niñas':'niñas', 'Niños':'niños'})
og_20 = og_20.drop(columns='Unnamed: 10')
og_20['year'] = 2020
print(og_20.columns.tolist())

['id_fila_og', 'oficina_regional', 'lugar_origen', 'lugar_destino', 'total_migrantes_traslado', 'nacionalidad', 'hombres', 'mujeres', 'niñas', 'niños', 'year']

In [133]:
print(og_21.columns.tolist())

['id', 'Oficina de Representación del INM ', 'Lugar de origen', 'Lugar de destino ', 'Total de migrantes en traslado', 'Nacionalidad ', 'Hombres', 'Mujeres', 'Niñas', 'Niños']

In [134]:
og_21 = og_21.rename(columns={'id': 'id_fila_og', 'Oficina de Representación del INM ': 'oficina_regional', 'Lugar de origen': 'lugar_origen', 'Lugar de destino ': 'lugar_destino', 'Total de migrantes en traslado': 'total_migrantes_traslado', 'Nacionalidad ': 'nacionalidad', 'Hombres': 'hombres', 'Mujeres': 'mujeres', 'Niñas':'niñas', 'Niños':'niños'})
og_21['year'] = 2021
print(og_21.columns.tolist())

['id_fila_og', 'oficina_regional', 'lugar_origen', 'lugar_destino', 'total_migrantes_traslado', 'nacionalidad', 'hombres', 'mujeres', 'niñas', 'niños', 'year']

In [135]:
print(og_22.columns.tolist())

['id', 'Oficina de Representación del INM ', 'Lugar de origen', 'Lugar de destino ', 'Total de migrantes en traslado', 'Nacionalidad ', '[SCRATCH]', 'Hombres', 'Mujeres', 'Niñas', 'Niños']

In [136]:
og_22 = og_22.rename(columns={'id': 'id_fila_og', 'Oficina de Representación del INM ': 'oficina_regional', 'Lugar de origen': 'lugar_origen', 'Lugar de destino ': 'lugar_destino', 'Total de migrantes en traslado': 'total_migrantes_traslado', 'Nacionalidad ': 'nacionalidad', 'Hombres': 'hombres', 'Mujeres': 'mujeres', 'Niñas':'niñas', 'Niños':'niños'})
og_22 = og_22.drop(columns='[SCRATCH]')
og_22['year'] = 2022
print(og_22.columns.tolist())

['id_fila_og', 'oficina_regional', 'lugar_origen', 'lugar_destino', 'total_migrantes_traslado', 'nacionalidad', 'hombres', 'mujeres', 'niñas', 'niños', 'year']

In [137]:
print(og_23.columns.tolist())

['id', 'Oficina de Representación del INM ', 'Oficina de Representación del INM .1', 'Lugar de destino ', 'Total de migrantes en traslado', 'Nacionalidad ', '[SCRATCH} nacionalidad', '[SCRATCH] demografía', 'Hombres', 'Mujeres', 'Niñas', 'Niños']

In [138]:
og_23 = og_23.rename(columns={'id': 'id_fila_og', 'Oficina de Representación del INM ': 'oficina_regional', 'Oficina de Representación del INM .1': 'lugar_origen', 'Lugar de destino ': 'lugar_destino', 'Total de migrantes en traslado': 'total_migrantes_traslado', 'Nacionalidad ': 'nacionalidad', 'Hombres': 'hombres', 'Mujeres': 'mujeres', 'Niñas':'niñas', 'Niños':'niños'})
og_23 = og_23.drop(columns=['[SCRATCH} nacionalidad', '[SCRATCH] demografía'])
og_23['year'] = 2023
print(og_23.columns.tolist())

['id_fila_og', 'oficina_regional', 'lugar_origen', 'lugar_destino', 'total_migrantes_traslado', 'nacionalidad', 'hombres', 'mujeres', 'niñas', 'niños', 'year']

In [139]:
print(og_24.columns.tolist())

['Unnamed: 0', 'Oficina de Representación del INM ', 'Lugar de origen', 'Lugar de destino ', 'Total de migrantes en traslado', 'Nacionalidad ', '[SCRATCH} nacionalidad', '[SCRATCH] demografía', 'Hombres', 'Mujeres', 'Niñas', 'Niños']

In [140]:
og_24 = og_24.rename(columns={'Unnamed: 0': 'id_fila_og', 'Oficina de Representación del INM ': 'oficina_regional', 'Lugar de origen': 'lugar_origen', 'Lugar de destino ': 'lugar_destino', 'Total de migrantes en traslado': 'total_migrantes_traslado', 'Nacionalidad ': 'nacionalidad', 'Hombres': 'hombres', 'Mujeres': 'mujeres', 'Niñas':'niñas', 'Niños':'niños'})
og_24 = og_24.drop(columns=['[SCRATCH} nacionalidad', '[SCRATCH] demografía'])
og_24['year'] = 2024
print(og_24.columns.tolist())

['id_fila_og', 'oficina_regional', 'lugar_origen', 'lugar_destino', 'total_migrantes_traslado', 'nacionalidad', 'hombres', 'mujeres', 'niñas', 'niños', 'year']

### Ahora, limpiamos los nombres de las oficinas regionales para asegurar que sean uniformes

In [141]:
print(og_17['oficina_regional'].unique())

['CHIHUAHUA' 'HIDALGO' 'JALISCO ' 'ESTADO DE MÉXICO' nan 'OAXACA'
 'QUINTANA ROO' 'SAN LUIS POTOSÍ' 'TAMAULIPAS' 'ZACATECAS']

In [142]:
og_17['oficina_regional'] = og_17['oficina_regional'].str.strip().str.title()
og_17['oficina_regional'] = og_17['oficina_regional'].replace('Estado De México', 'Estado de México')
print(og_17['oficina_regional'].unique())

['Chihuahua' 'Hidalgo' 'Jalisco' 'Estado de México' nan 'Oaxaca'
 'Quintana Roo' 'San Luis Potosí' 'Tamaulipas' 'Zacatecas']

In [143]:
print(og_18['oficina_regional'].unique())

['AGUASCALIENTES' nan 'BAJA CALIFORNIA' 'CAMPECHE' 'CHIAPAS' 'CHIHUAHUA'
 'CIUDAD DE MEXICO' 'COAHUILA' 'HIDALGO' 'JALISCO ' 'OAXACA' 'QUERÉTARO '
 'QUINTANA ROO' 'SAN LUIS POTOSI' 'SINALOA' 'TABASCO' 'TAMAULIPAS'
 'TLAXCALA' 'VERACRUZ' 'ZACATECAS']

In [144]:
og_18['oficina_regional'] = og_18['oficina_regional'].str.strip().str.title()
og_18['oficina_regional'] = og_18['oficina_regional'].replace('Ciudad De Mexico', 'Ciudad de México')
og_18['oficina_regional'] = og_18['oficina_regional'].replace('San Luis Potosi', 'San Luis Potosí')
print(og_18['oficina_regional'].unique())

['Aguascalientes' nan 'Baja California' 'Campeche' 'Chiapas' 'Chihuahua'
 'Ciudad de México' 'Coahuila' 'Hidalgo' 'Jalisco' 'Oaxaca' 'Querétaro'
 'Quintana Roo' 'San Luis Potosí' 'Sinaloa' 'Tabasco' 'Tamaulipas'
 'Tlaxcala' 'Veracruz' 'Zacatecas']

In [145]:
print(og_19['oficina_regional'].unique())

['AGUASCALIENTES' nan 'BAJA CALIFORNIA' 'CAMPECHE' 'CHIAPAS' 'CHIHUAHUA'
 'CIUDAD DE MEXICO' 'COAHUILA ' ' DURANGO' 'HIDALGO' 'MICHOACÁN' 'NAYARIT'
 'OAXACA' 'QUINTANA ROO' 'SAN LUIS POTOSI' 'SINALOA' 'TABASCO'
 'TAMAULIPAS' 'TLAXCALA' 'YUCATÁN' 'ZACATECAS ']

In [146]:
og_19['oficina_regional'] = og_19['oficina_regional'].str.strip().str.title()
og_19['oficina_regional'] = og_19['oficina_regional'].replace('Ciudad De Mexico', 'Ciudad de México')
og_19['oficina_regional'] = og_19['oficina_regional'].replace('San Luis Potosi', 'San Luis Potosí')
print(og_19['oficina_regional'].unique())

['Aguascalientes' nan 'Baja California' 'Campeche' 'Chiapas' 'Chihuahua'
 'Ciudad de México' 'Coahuila' 'Durango' 'Hidalgo' 'Michoacán' 'Nayarit'
 'Oaxaca' 'Quintana Roo' 'San Luis Potosí' 'Sinaloa' 'Tabasco'
 'Tamaulipas' 'Tlaxcala' 'Yucatán' 'Zacatecas']

In [147]:
print(og_20['oficina_regional'].unique())

['AGUASCALIENTES' nan 'BAJA CALIFORNIA' 'CAMPECHE' 'CHIAPAS' 'CHIHUAHUA'
 'CIUDAD DE MEXICO' 'COAHUILA ' 'HIDALGO' 'JALISCO' 'OAXACA' 'QUERETARO'
 'QUINTANA ROO' 'SAN LUIS POTOSI' 'SINALOA' 'TABASCO' ' TAMAULIPAS'
 'TLAXCALA' 'VERACRUZ' 'YUCATÁN' 'ZACATECAS']

In [148]:
og_20['oficina_regional'] = og_20['oficina_regional'].str.strip().str.title()
og_20['oficina_regional'] = og_20['oficina_regional'].replace('Ciudad De Mexico', 'Ciudad de México')
og_20['oficina_regional'] = og_20['oficina_regional'].replace('San Luis Potosi', 'San Luis Potosí')
og_20['oficina_regional'] = og_20['oficina_regional'].replace('Queretaro', 'Querétaro')
print(og_20['oficina_regional'].unique())

['Aguascalientes' nan 'Baja California' 'Campeche' 'Chiapas' 'Chihuahua'
 'Ciudad de México' 'Coahuila' 'Hidalgo' 'Jalisco' 'Oaxaca' 'Querétaro'
 'Quintana Roo' 'San Luis Potosí' 'Sinaloa' 'Tabasco' 'Tamaulipas'
 'Tlaxcala' 'Veracruz' 'Yucatán' 'Zacatecas']

In [149]:
print(og_21['oficina_regional'].unique())

['AGUASCALIENTES' nan 'BAJA CALIFORNIA' 'CHIAPAS' 'CHIHUAHUA'
 'CIUDAD DE MEXICO' 'COAHUILA' 'DURANGO' 'GUANAJUATO' 'GUERRERO' 'HIDALGO'
 'JALISCO' 'ESTADO DE MÉXICO' 'MICHOACÁN' 'NAYARIT' 'OAXACA' 'PUEBLA'
 'QUINTANA ROO' 'QUERETARO' 'SAN LUIS POTOSI' 'SINALOA' 'TABASCO'
 'TAMAULIPAS' 'TLAXCALA' 'VERACRUZ' 'YUCATÁN' 'ZACATECAS']

In [150]:
og_21['oficina_regional'] = og_21['oficina_regional'].str.strip().str.title()
og_21['oficina_regional'] = og_21['oficina_regional'].replace('Ciudad De Mexico', 'Ciudad de México')
og_21['oficina_regional'] = og_21['oficina_regional'].replace('Estado De México', 'Estado de México')
og_21['oficina_regional'] = og_21['oficina_regional'].replace('San Luis Potosi', 'San Luis Potosí')
og_21['oficina_regional'] = og_21['oficina_regional'].replace('Queretaro', 'Querétaro')
print(og_21['oficina_regional'].unique())

['Aguascalientes' nan 'Baja California' 'Chiapas' 'Chihuahua'
 'Ciudad de México' 'Coahuila' 'Durango' 'Guanajuato' 'Guerrero' 'Hidalgo'
 'Jalisco' 'Estado de México' 'Michoacán' 'Nayarit' 'Oaxaca' 'Puebla'
 'Quintana Roo' 'Querétaro' 'San Luis Potosí' 'Sinaloa' 'Tabasco'
 'Tamaulipas' 'Tlaxcala' 'Veracruz' 'Yucatán' 'Zacatecas']

In [151]:
print(og_22['oficina_regional'].unique())

['AGUASCALIENTES' nan 'CAMPECHE' 'CHIAPAS' 'CHIHUAHUA' 'CIUDAD DE MEXIO'
 'SALTILLO' 'TORREON' 'MONCLOVA' 'PIEDRAS NEGRAS' 'DURANGO' 'GUANAJUATO'
 'HIDALGO' 'ESTADO DE MÉXICO' 'MICHOACÁN' 'NAYARIT' 'NUEVO LEÓN' 'OAXACA '
 'PUEBLA ' 'QUERETARO' 'QUINTANA ROO' 'SAN LUIS POTOSI' 'SINALOA' 'SONORA'
 'TABASCO' ' TAMAULIPAS' 'TLAXCALA' 'VERACRUZ' 'ZACATECAS']

In [152]:
# La regla 3 nos va a arreglar el desfase en la participación de Coahuila en está tabla, por ahora lo dejamos así
og_22['oficina_regional'] = og_22['oficina_regional'].str.strip().str.title()
og_22['oficina_regional'] = og_22['oficina_regional'].replace('Ciudad De Mexio', 'Ciudad de México')
og_22['oficina_regional'] = og_22['oficina_regional'].replace('Estado De México', 'Estado de México')
og_22['oficina_regional'] = og_22['oficina_regional'].replace('San Luis Potosi', 'San Luis Potosí')
og_22['oficina_regional'] = og_22['oficina_regional'].replace('Queretaro', 'Querétaro')
print(og_22['oficina_regional'].unique())

['Aguascalientes' nan 'Campeche' 'Chiapas' 'Chihuahua' 'Ciudad de México'
 'Saltillo' 'Torreon' 'Monclova' 'Piedras Negras' 'Durango' 'Guanajuato'
 'Hidalgo' 'Estado de México' 'Michoacán' 'Nayarit' 'Nuevo León' 'Oaxaca'
 'Puebla' 'Querétaro' 'Quintana Roo' 'San Luis Potosí' 'Sinaloa' 'Sonora'
 'Tabasco' 'Tamaulipas' 'Tlaxcala' 'Veracruz' 'Zacatecas']

In [153]:
print(og_23['oficina_regional'].unique())

['AGUASCALIENTES' nan 'BAJA CALIFORNIA' 'CHIAPAS' 'CHIHUAHUA'
 'CIUDAD DE MEXIO' 'COAHUILA' 'DURANGO' 'GUANAJUATO' 'HIDALGO' 'JALISCO '
 'ESTADO DE MÉXICO' 'NAYARIT' 'NUEVO LEÓN' 'OAXACA' 'PUEBLA' 'QUERETARO'
 'QUINTANA ROO' 'SAN LUIS POTOSI' 'SINALOA' 'SONORA' 'TABASCO'
 ' TAMAULIPAS' 'TLAXCALA' 'VERACRUZ' 'YUCATÁN' 'ZACATECAS']

In [154]:
og_23['oficina_regional'] = og_23['oficina_regional'].str.strip().str.title()
og_23['oficina_regional'] = og_23['oficina_regional'].replace('Ciudad De Mexio', 'Ciudad de México')
og_23['oficina_regional'] = og_23['oficina_regional'].replace('Estado De México', 'Estado de México')
og_23['oficina_regional'] = og_23['oficina_regional'].replace('San Luis Potosi', 'San Luis Potosí')
og_23['oficina_regional'] = og_23['oficina_regional'].replace('Queretaro', 'Querétaro')
print(og_23['oficina_regional'].unique())

['Aguascalientes' nan 'Baja California' 'Chiapas' 'Chihuahua'
 'Ciudad de México' 'Coahuila' 'Durango' 'Guanajuato' 'Hidalgo' 'Jalisco'
 'Estado de México' 'Nayarit' 'Nuevo León' 'Oaxaca' 'Puebla' 'Querétaro'
 'Quintana Roo' 'San Luis Potosí' 'Sinaloa' 'Sonora' 'Tabasco'
 'Tamaulipas' 'Tlaxcala' 'Veracruz' 'Yucatán' 'Zacatecas']

In [155]:
print(og_24['oficina_regional'].unique())

['BAJA CALIFORNIA' nan 'CHIHUAHUA' 'CIUDAD DE MÉXICO' 'COAHUILA' 'DURANGO'
 'GUANAJUATO' 'HIDALGO' 'JALISCO ' 'ESTADO DE MÉXICO' 'MICHOACÁN'
 'NAYARIT' 'NUEVO LEÓN' 'OAXACA' 'PUEBLA' 'QUERETARO' 'QUINTANA ROO'
 'SAN LUIS POTOSI' 'SINALOA' 'SONORA' 'TABASCO' 'TAMAULIPAS' 'TLAXCALA'
 'ACAYUCAN' 'YUCATÁN' 'ZACATECAS']

In [156]:
og_24['oficina_regional'] = og_24['oficina_regional'].str.strip().str.title()
og_24['oficina_regional'] = og_24['oficina_regional'].replace('Ciudad De México', 'Ciudad de México')
og_24['oficina_regional'] = og_24['oficina_regional'].replace('Estado De México', 'Estado de México')
og_24['oficina_regional'] = og_24['oficina_regional'].replace('San Luis Potosi', 'San Luis Potosí')
og_24['oficina_regional'] = og_24['oficina_regional'].replace('Acayucan', 'Veracruz')
og_24['oficina_regional'] = og_24['oficina_regional'].replace('Queretaro', 'Querétaro')
print(og_23['oficina_regional'].unique())

['Aguascalientes' nan 'Baja California' 'Chiapas' 'Chihuahua'
 'Ciudad de México' 'Coahuila' 'Durango' 'Guanajuato' 'Hidalgo' 'Jalisco'
 'Estado de México' 'Nayarit' 'Nuevo León' 'Oaxaca' 'Puebla' 'Querétaro'
 'Quintana Roo' 'San Luis Potosí' 'Sinaloa' 'Sonora' 'Tabasco'
 'Tamaulipas' 'Tlaxcala' 'Veracruz' 'Yucatán' 'Zacatecas']

# Realizamos la concatenación bruta con filas NaN y chequeos manuales para asegurar que todo está como esperamos

### Los entradas que en las tablas originales, abarcan múltiples filas o son bloques, deberían mostrarse aquí como una fila con datos seguida por varias en blanco

In [157]:
# Checamos el número de filas de cada tabla
print(og_17.shape)
print(og_18.shape)
print(og_19.shape)
print(og_20.shape)
print(og_21.shape)
print(og_22.shape)
print(og_23.shape)
print(og_24.shape)

(260, 11)
(695, 11)
(720, 11)
(1048, 11)
(1860, 11)
(2942, 11)
(4892, 11)
(1460, 11)

In [158]:
# Sumamos las filas. Esta suma debería equivaler al último valor de id_fila_og, 13877
260+695+720+1048+1860+2942+4892+1460

13877

In [159]:
# Combinamos las tablas en una
master = pd.concat([og_17, og_18, og_19, og_20, og_21, og_22, og_23, og_24], ignore_index=True)

In [160]:
# Verificamos el shape
print(master.shape)  
print(master.columns.tolist())

(13877, 11)
['id_fila_og', 'oficina_regional', 'lugar_origen', 'lugar_destino', 'total_migrantes_traslado', 'nacionalidad', 'hombres', 'mujeres', 'niñas', 'niños', 'year']

### Veamos algunos de los rangos con reglas especiales para confirmar qué hace pandas

#### La descripción de las reglas se encuentra aquí: https://docs.google.com/spreadsheets/d/17OCfRHTOGVZ7WL_YxtLJe7dqQxjmPX-1wGMM3uXzsgY/edit?usp=sharing

In [161]:
# Checamos la regla específica H
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(master.loc[master['id_fila_og'].between(2895, 3020), :])

,id_fila_og,oficina_regional,lugar_origen,lugar_destino,total_migrantes_traslado,nacionalidad,hombres,mujeres,niñas,niños,year
2894,2895,Coahuila,SALTILLO,"VILLAHERMOSA, TABASCO",80,"27 CUBANA, 01 DOMINICANA, 06 GUATEMALTECA, 18 ...",54,20.0,1.0,5.0,2021
2895,2896,NaN,NaN,NaN,39,03 CUBANA Y 36 HONDUREÑA,30,9.0,0.0,0.0,2021
2896,2897,NaN,NaN,NaN,28,28 HONDUREÑA,17,8.0,2.0,1.0,2021
2897,2898,NaN,NaN,NaN,41,27 HONDUREÑA Y 14 NICARAGÜENSE,23,11.0,3.0,4.0,2021
2898,2899,NaN,NaN,NaN,40,01 VENEZOLANA Y 39 HONDUREÑA,36,4.0,0.0,0.0,2021
2899,2900,NaN,PIEDRAS NEGRAS,NaN,40,"02 CUBANA, 02 HAITIANA, 31 HONDUREÑA, 04 NICAR...",32,7.0,0.0,1.0,2021
2900,2901,NaN,SALTILLO,NaN,40,"01 CHILENA, 03 CUBANA, 02 HAITIANA, 26 HONDUR...",32,5.0,0.0,3.0,2021
2901,2902,NaN,NaN,NaN,40,"21 SALVADOREÑA, 19 GUATEMALTECA",25,13.0,1.0,1.0,2021
2902,2903,NaN,NaN,NaN,40,39 HONDUREÑA Y 01 NICARAGÜENSE,39,1.0,0.0,0.0,2021
2903,2904,NaN,NaN,NaN,19,13 HONDUREÑA Y 06 NICARAGÜENSE,17,2.0,0.0,0.0,2021
2904,2905,NaN,NaN,NaN,40,"30 HONDUREÑA, 09 NICARAGÜENSE Y 01 VENEZOLANA",29,10.0,0.0,1.0,2021
2905,2906,NaN,NaN,NaN,40,"03 CUBANA, 36 HONDUREÑA Y 01 VENEZOLANA",25,11.0,1.0,3.0,2021
2906,2907,NaN,NaN,NaN,40,"01 CHILENA, 01 CUBANA, 02 HAITIANA, 32 HONDURE...",32,7.0,0.0,1.0,2021
2907,2908,NaN,NaN,"ACAYUCAN, VERACRUZ",40,19 GUATEMALTECA Y 21 SALVADOREÑA,24,16.0,0.0,0.0,2021
2908,2909,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",40,"06 CUBANA, 32 SALVADOREÑA Y 02 NICARAGÜENSE",31,9.0,0.0,0.0,2021
2909,2910,NaN,SALTILLO,NaN,40,40 HONDUREÑA,35,5.0,0.0,0.0,2021
2910,2911,NaN,TORREON,NaN,40,39 HONDUREÑA Y 01 VENEZOLANA,37,3.0,0.0,0.0,2021
2911,2912,NaN,SALTILLO,"TAMPICO, TAMAULIPAS",40,"02 GUATEMALTECA, 34 HONDUREÑA, 04 SALVADOREÑA",35,5.0,0.0,0.0,2021
2912,2913,NaN,NaN,"VILLAHERMOSA, TABASCO",41,41 VENEZOLANA,19,22.0,0.0,0.0,2021
2913,2914,NaN,NaN,NaN,40,03 CUBANA Y 37 NICARAGÜENSE,39,1.0,0.0,0.0,2021
2914,2915,NaN,NaN,NaN,40,24 HONDUREÑA Y 16 NICARAGÜENSE,33,7.0,0.0,0.0,2021
2915,2916,NaN,NaN,NaN,40,34 HONDUREÑA Y 06 NICARAGÜENSE,35,5.0,0.0,0.0,2021
2916,2917,NaN,NaN,NaN,40,40 HONDUREÑA,37,3.0,0.0,0.0,2021
2917,2918,NaN,NaN,NaN,39,"03 CHILENA, 07 CONGOLEÑA, 05 CUBANA, 05 HONDUR...",19,8.0,6.0,6.0,2021
2918,2919,NaN,NaN,NaN,40,"01 CHILENA, 07 CUBANA, 02 HAITI, 08 HONDUREÑA,...",23,13.0,1.0,3.0,2021
2919,2920,NaN,MONCLOVA,IZTAPALAPA,14,14 HONDUREÑA,14,0.0,0.0,0.0,2021
2920,2921,NaN,NaN,IZTAPALAPA,41,"02 CUBANA, 10 GUATEMALTECA, 21 HONDUREÑA, 02 N...",39,2.0,0.0,0.0,2021
2921,2922,NaN,NaN,ZACATECAS,30,"24 HONDUREÑA, 02 GUATEMALTECA, 04 SALVADOREÑA",27,3.0,0.0,0.0,2021
2922,2923,NaN,MONCLOVA,SAN LUIS POTOSI,28,"25 HONDUREÑA, 02 GUATEMALTECA, 01 SALVADOREÑA",27,1.0,0.0,0.0,2021
2923,2924,NaN,NaN,VILLAHERMOSA,30,30 HONDUREÑA,26,4.0,0.0,0.0,2021
2924,2925,NaN,NaN,SAN LUIS POTOSI,37,"21 HONDUREÑA, 10 GUATEMALTECA, 06 SALVADOREÑA",23,14.0,0.0,0.0,2021
2925,2926,NaN,MONCLOVA,ACAYUCAN,18,18 HONDUREÑA,12,6.0,0.0,0.0,2021
2926,2927,NaN,NaN,TAPACHULA,12,12 GUATEMALTECA,8,4.0,0.0,0.0,2021
2927,2928,NaN,NaN,SALTILLO,43,43 HONDUREÑA,42,1.0,0.0,0.0,2021
2928,2929,NaN,MONCLOVA,NUEVO LEON,13,"07 HONDUREÑA, 06 NICARAGÜENSE",7,6.0,0.0,0.0,2021
2929,2930,NaN,NaN,SALTILLO,30,"25 NICARAGÜENSE, 05 HONDUREÑA",18,8.0,1.0,3.0,2021
2930,2931,NaN,NaN,TAPACHULA,6,"05 NICARAGÜENSE, 01 HONDUREÑA",6,0.0,0.0,0.0,2021
2931,2932,NaN,MONCLOVA,VILLAHERMOSA,21,"17 HONDUREÑA, 04 SALVADOREÑA",19,2.0,0.0,0.0,2021
2932,2933,NaN,NaN,CHIAPAS,8,07 GUATEMALTECA y 01 SALVADOREÑA,6,2.0,0.0,0.0,2021
2933,2934,NaN,NaN,VILLAHERMOSA,8,"05 NICARAGÜENSE, 03 HONDUREÑA",7,1.0,0.0,0.0,2021
2934,2935,NaN,MONCLOVA,VILLAHERMOSA,22,"17 HONDUREÑA, 01 GUINEANA, 01 SENEGALESA",20,2.0,0.0,0.0,2021
2935,2936,NaN,NaN,VILLAHERMOSA,40,"29 HONDUREÑA, 05 SENEGALESA, 05 VENEZOLANA, 01...",21,8.0,0.0,0.0,2021
2936,2937,NaN,NaN,NUEVO LEON,22,"14 HONDUREÑA, 05 NICARAGÜENSE, 03 CUBANA",20,2.0,0.0,0.0,2021
2937,2938,NaN,MONCLOVA,NUEVO LEON,10,"01 COLOMBIANA, 09 CUBANA",5,5.0,0.0,0.0,2021
2938,2939,NaN,NaN,SALTILLO,20,"05 CUBANA, 03 NICARAGÜENSE, 08 HONDUREÑA, 02 P...",16,4.0,0.0,0.0,2021
2939,2940,NaN,NaN,NaN,NaN,NaN,0,0.0,0.0,0.0,2021
2940,2941,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",40,13 EL SALVADOR 09 GUATEMALA 16 HONDURAS 02 EL ...,36,4.0,0.0,0.0,2021
2941,2942,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",32,29 HONDURAS 3 GUATEMALA,30,2.0,0.0,0.0,2021
2942,2943,NaN,PIEDRAS NEGRAS,"ACAYUCAN, VERACRUZ",40,40 HONDURAS,39,1.0,0.0,0.0,2021
2943,2944,NaN,PIEDRAS NEGRAS,"ACAYUCAN, VERACRUZ",39,39 HONDURAS,39,0.0,0.0,0.0,2021
2944,2945,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",40,03 EL SALVADOR 09 GUATEMALA 27 HONDURAS 01 NIC...,36,4.0,0.0,0.0,2021
2945,2946,NaN,PIEDRAS NEGRAS,"ACAYUCAN, VERACRUZ",36,13 GUATEMALA 21 HONDURAS 02 NICARAGUA,35,1.0,0.0,0.0,2021
2946,2947,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",35,04 EL SALVADOR 06 GUATEMALA 23 HONDURAS 02 NIC...,32,3.0,0.0,0.0,2021
2947,2948,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",29,02 EL SALVADOR 01 GUATEMALA 26 HONDURAS,29,0.0,0.0,0.0,2021
2948,2949,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",33,28 HONDURAS 05 EL SALVADOR,32,1.0,0.0,0.0,2021
2949,2950,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",40,36 HONDURAS 02 GUATEMALA 02 EL SALVADOR,38,2.0,0.0,0.0,2021
2950,2951,NaN,PIEDRAS NEGRAS,"ACAYUCAN, VERACRUZ",40,40 HONDURAS,40,0.0,0.0,0.0,2021
2951,2952,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",35,35 HONDURAS,31,4.0,0.0,0.0,2021
2952,2953,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",40,39 HONDURAS 01 GUATEMALA,37,3.0,0.0,0.0,2021
2953,2954,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",35,35 HONDURAS,33,2.0,0.0,0.0,2021
2954,2955,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",35,14 GUATEMALA 21 HONDURAS,33,2.0,0.0,0.0,2021
2955,2956,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",40,40 HONDURAS,40,0.0,0.0,0.0,2021
2956,2957,NaN,PIEDRAS NEGRAS,SAN LUIS POTOSI,35,04 GUATEMALA 27 HONDURAS 04 NICARAGUA,35,0.0,0.0,0.0,2021
2957,2958,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",40,02 EL SALVADOR 02 GUATEMALA 36 HONDURAS,40,0.0,0.0,0.0,2021
2958,2959,NaN,PIEDRAS NEGRAS,"ACAYUCAN, VERACRUZ",35,09 EL SALVADOR 01 GUATEMALA 25 HONDURAS,35,0.0,0.0,0.0,2021
2959,2960,NaN,PIEDRAS NEGRAS,"ACAYUCAN, VERACRUZ",35,35 HONDURAS,28,7.0,0.0,0.0,2021
2960,2961,NaN,PIEDRAS NEGRAS,SAN LUIS POTOSI,40,40 HONDURAS,39,1.0,0.0,0.0,2021
2961,2962,NaN,PIEDRAS NEGRAS,"ACAYUCAN, VERACRUZ",33,33 HONDURAS,33,0.0,0.0,0.0,2021
2962,2963,NaN,PIEDRAS NEGRAS,"ACAYUCAN, VERACRUZ",33,33 HONDURAS,26,7.0,0.0,0.0,2021
2963,2964,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",30,20 HONDURAS 10 EL SALVADOR,26,4.0,0.0,0.0,2021
2964,2965,NaN,PIEDRAS NEGRAS,"IZTAPALAPA, CDMX",40,40 HONDURAS,39,1.0,0.0,0.0,2021
2965,2966,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",37,17 GUATEMALA 20 HONDURAS,34,3.0,0.0,0.0,2021
2966,2967,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",41,05 GUATEMALA 29 HONDURAS 07 NICARAGUA,38,3.0,0.0,0.0,2021
2967,2968,NaN,PIEDRAS NEGRAS,AEROPUERTO INTL NUEVO LEON,33,33 HONDURAS,31,1.0,0.0,1.0,2021
2968,2969,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",40,33 HONDURAS 7 GUATEMALA,37,3.0,0.0,0.0,2021
2969,2970,NaN,PIEDRAS NEGRAS,"IZTAPALAPA, CDMX",40,40 HONDURAS,36,4.0,0.0,0.0,2021
2970,2971,NaN,PIEDRAS NEGRAS,"GUADALUPE, NUEVO LEON",21,21 HONDURAS,21,0.0,0.0,0.0,2021
2971,2972,NaN,PIEDRAS NEGRAS,SAN LUIS POTOSI,20,20 GUATEMALA,15,5.0,0.0,0.0,2021
2972,2973,NaN,PIEDRAS NEGRAS,"TAPACHULA, CHIAPAS",18,18 EL SALVADOR,16,2.0,0.0,0.0,2021
2973,2974,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",21,21 HONDURAS,21,0.0,0.0,0.0,2021
2974,2975,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",30,30 HONDURAS,29,1.0,0.0,0.0,2021
2975,2976,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",33,31 HONDURAS 2 CUBA,33,0.0,0.0,0.0,2021
2976,2977,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",39,30 HONDURAS,39,0.0,0.0,0.0,2021
2977,2978,NaN,PIEDRAS NEGRAS,"MONCLOVA, COAHUILA",30,30 HONDURAS,30,0.0,0.0,0.0,2021
2978,2979,NaN,PIEDRAS NEGRAS,"IZTAPALAPA, CDMX",33,24 GUATEMALA 09 EL SALVADOR,29,4.0,0.0,0.0,2021
2979,2980,NaN,PIEDRAS NEGRAS,"IZTAPALAPA, CDMX",28,28 HONDURAS,28,0.0,0.0,0.0,2021
2980,2981,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",35,09 EL SALVADOR 09 GUATEMALA 13 HONDURAS 04 NIC...,30,5.0,0.0,0.0,2021
2981,2982,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",30,03 EL SALVADOR 08 GUATEMALA 19 HONDURAS,30,0.0,0.0,0.0,2021
2982,2983,NaN,PIEDRAS NEGRAS,"TAPACHULA, CHIAPAS",29,18 HONDURAS 11 GUATEMALA,26,3.0,0.0,0.0,2021
2983,2984,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",24,08 NICARAGUA 09 HONDURAS 08 NICARAGUA,20,4.0,0.0,0.0,2021
2984,2985,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",21,04 EL SALVADOR 02 GUATEMALA 15 HONDURAS,21,0.0,0.0,0.0,2021
2985,2986,NaN,PIEDRAS NEGRAS,"TAPACHULA, CHIAPAS",23,02 EL SALVADOR 03 GUATEMALA 18 HONDURAS,21,2.0,0.0,0.0,2021
2986,2987,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",20,18 HONDURAS 02 GUATEMALA,16,4.0,0.0,0.0,2021
2987,2988,NaN,PIEDRAS NEGRAS,"TAPACHULA, CHIAPAS",30,26 HONDURAS 02 NICARAGUA02 EL SALVADOR,30,0.0,0.0,0.0,2021
2988,2989,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",21,20 HONDURAS 01 GUATEMALA,19,2.0,0.0,0.0,2021
2989,2990,NaN,PIEDRAS NEGRAS,"TAPACHULA, CHIAPAS",28,03 GUATEMALA 24 HONDURAS 01 PAKISTAN,25,3.0,0.0,0.0,2021
2990,2991,NaN,PIEDRAS NEGRAS,"TAPACHULA, CHIAPAS",24,03 EL SALVADOR 03 GUATEMALA 18 HONDURAS,23,1.0,0.0,0.0,2021
2991,2992,NaN,PIEDRAS NEGRAS,"TAPACHULA, CHIAPAS",22,11 HONDURAS 10 GUATEMALA 01 EL SALVADOR,15,7.0,0.0,0.0,2021
2992,2993,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",40,40 HONDURAS,40,0.0,0.0,0.0,2021
2993,2994,NaN,PIEDRAS NEGRAS,"TAPACHULA, CHIAPAS",40,30 HONDURAS 10 EL SALVADOR,33,7.0,0.0,0.0,2021
2994,2995,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",29,26 HONDURAS 02 GUATEMALA 01 EL SALVADOR,25,4.0,0.0,0.0,2021
2995,2996,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",38,37 HONDURAS 01 EL SALVADOR,32,6.0,0.0,0.0,2021
2996,2997,NaN,PIEDRAS NEGRAS,"TAPACHULA, CHIAPAS",30,03 EL SALVADOR 09 GUATEMALA 18 HONDURAS,28,2.0,0.0,0.0,2021
2997,2998,NaN,PIEDRAS NEGRAS,"ACAYUCAN, VERACRUZ",39,39 HONDURAS,36,3.0,0.0,0.0,2021
2998,2999,NaN,PIEDRAS NEGRAS,"SALTILLO,COAHUILA",24,12 HONDURAS 08 GUATEMALA 04 EL SALVADOR,24,0.0,0.0,0.0,2021
2999,3000,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",31,27 HONDURAS 04 GUATEMALA,28,3.0,0.0,0.0,2021
3000,3001,NaN,PIEDRAS NEGRAS,"ACAYUCAN, VERACRUZ",22,22 HONDURAS,21,1.0,0.0,0.0,2021
3001,3002,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",30,30 HONDURAS,30,0.0,0.0,0.0,2021
3002,3003,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",33,26 HONDURAS 07 EL SALVADOR,26,7.0,0.0,0.0,2021
3003,3004,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",35,35 HONDURAS,30,5.0,0.0,0.0,2021
3004,3005,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",35,05 EL SALVADOR 30 HONDURAS,30,5.0,0.0,0.0,2021
3005,3006,NaN,PIEDRAS NEGRAS,"TAPACHULA, CHIAPAS",12,12 GUATEMALA,12,0.0,0.0,0.0,2021
3006,3007,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",36,36 HONDURAS,31,5.0,0.0,0.0,2021
3007,3008,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",32,27 HONDURAS 05 EL SALVADOR,26,6.0,0.0,0.0,2021
3008,3009,NaN,PIEDRAS NEGRAS,"TAPACHULA, CHIAPAS",40,17 GUATEMALA 04 EL SALVADOR 18 HONDURAS,34,6.0,0.0,0.0,2021
3009,3010,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",32,02 VENEZUELA 30 HONDURAS,32,0.0,0.0,0.0,2021
3010,3011,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",30,27 HONDURAS 03 HAITI,13,17.0,0.0,0.0,2021
3011,3012,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",40,40 HONDURAS,37,3.0,0.0,0.0,2021
3012,3013,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",40,02 EL SALVADOR 38 HONDURAS,29,11.0,0.0,0.0,2021
3013,3014,NaN,PIEDRAS NEGRAS,"SALTILLO, COAHUILA",30,06 CUBA 02 EL SALVADOR 04 GUATEMALA 16 HONDURA...,23,7.0,0.0,0.0,2021
3014,3015,NaN,PIEDRAS NEGRAS,"SALTILLO, COAHUILA",40,03 VENEZUELA 28 CUBA 07 NICARAGUA 02 HONDURAS,28,12.0,0.0,0.0,2021
3015,3016,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",37,03 CUBA 25 NICARAGUA 09 HONDURAS,23,14.0,0.0,0.0,2021
3016,3017,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",40,40 HONDURAS,30,10.0,0.0,0.0,2021
3017,3018,NaN,PIEDRAS NEGRAS,"SALTILLO, COAHUILA",40,28 HONDURAS 02 EL SALVADOR 07 GUATEMALA 02 COL...,34,6.0,0.0,0.0,2021
3018,3019,NaN,PIEDRAS NEGRAS,"SALTILLO, COAHUILA",40,33 VENEZUELA 1 HONDURAS 01 COLOMBIA 04 CUBA 01...,38,2.0,0.0,0.0,2021
3019,3020,NaN,PIEDRAS NEGRAS,"VILLAHERMOSA, TABASCO",31,30 HONDURAS 01 EL SALVADOR,30,1.0,0.0,0.0,2021

In [162]:
# Checamos la regla específica B
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(master.loc[master['id_fila_og'].between(459, 491), :])

,id_fila_og,oficina_regional,lugar_origen,lugar_destino,total_migrantes_traslado,nacionalidad,hombres,mujeres,niñas,niños,year
458,459,Jalisco,Guadalajara,EM IZTAPALAPA,35,"23 GUATEMALA, 10 HONDURAS, 02 EL SALVADOR",24,11.0,0.0,0.0,2018
459,460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
460,461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
461,462,NaN,Guadalajara,EM IZTAPALAPA,23,"4 GUATEMALA, 19 HONDUREÑA",20,3.0,0.0,0.0,2018
462,463,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
463,464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
464,465,NaN,Guadalajara,EM IZTAPALAPA,29,"17 GUATEMALA, 11 HONDURAS, 01 BELICEÑO",21,3.0,4.0,1.0,2018
465,466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
466,467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
467,468,NaN,Guadalajara,EM IZTAPALAPA,27,"21 GUATEMALA, 05 HONDURAS, 01 EL SALVADOR",20,7.0,0.0,0.0,2018
468,469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
469,470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
470,471,NaN,Guadalajara,EM IZTAPALAPA,22,"01 BELICE, 01 SALVADOR,03 HONDURAS, 17 GUATEMALA",18,4.0,0.0,0.0,2018
471,472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
472,473,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
473,474,NaN,Guadalajara,EM IZTAPALAPA,25,"17 GUATEMALA, 06 EL SALVADOR, 02 HONDURAS",19,3.0,1.0,2.0,2018
474,475,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
475,476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
476,477,NaN,Guadalajara,EM IZTAPALAPA,23,"15 GUATEMALA, 08 HONDURAS",15,6.0,1.0,1.0,2018
477,478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
478,479,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
479,480,NaN,Guadalajara,EM IZTAPALAPA,40,40 GUATEMALA,20,4.0,8.0,8.0,2018
480,481,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
481,482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
482,483,NaN,Guadalajara,EM IZTAPALAPA,28,"25 GUATEMALA, 03 HONDURAS",10,4.0,2.0,12.0,2018
483,484,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
484,485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
485,486,NaN,Guadalajara,EM IZTAPALAPA,39,39 GUATEMALA,20,3.0,6.0,10.0,2018
486,487,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
487,488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
488,489,NaN,Guadalajara,EM IZTAPALAPA,24,"22 GUATEMALA, 02 HONDURAS",22,2.0,0.0,0.0,2018
489,490,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
490,491,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018

In [163]:
# Checamos la regla específica E
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(master.loc[master['id_fila_og'].between(1690, 1711), :])

,id_fila_og,oficina_regional,lugar_origen,lugar_destino,total_migrantes_traslado,nacionalidad,hombres,mujeres,niñas,niños,year
1689,1690,Chiapas,COMITAN,"SIGLO XXI, TAPACHULA",526.0,GUATEMALA,250,85.0,6.0,15.0,2020
1690,1691,NaN,NaN,NaN,NaN,HONDURAS,85,25.0,12.0,6.0,2020
1691,1692,NaN,NaN,NaN,NaN,EL SALVADOR,15,9.0,3.0,5.0,2020
1692,1693,NaN,NaN,NaN,NaN,NICARAGUA,3,1.0,0.0,0.0,2020
1693,1694,NaN,NaN,NaN,NaN,CAMERUN,4,2.0,0.0,0.0,2020
1694,1695,NaN,COMITAN,"TECUN UMAN, GTM",605.0,GUATEMALA,480,95.0,17.0,3.0,2020
1695,1696,NaN,NaN,"LA MESILLA, GTM",42.0,GUATEMALA,28,8.0,2.0,4.0,2020
1696,1697,NaN,NaN,"TUXTLA GUTIERREZ, CHIS",30.0,GUATEMALA,15,7.0,1.0,3.0,2020
1697,1698,NaN,NaN,NaN,NaN,EL SALVADOR,3,1.0,0.0,0.0,2020
1698,1699,NaN,NaN,EL CARMEN GUATEMALA,84.0,GUATEMALA,55,15.0,6.0,8.0,2020
1699,1700,NaN,NaN,"ACAYUCAN, VER",11.0,EL SALVADOR,7,4.0,0.0,0.0,2020
1700,1701,NaN,NaN,"IZTAPALAPA, CD. MEXICO",62.0,HONDURAS,35,19.0,4.0,4.0,2020
1701,1702,NaN,NaN,"VILLAHERMOSA, TAB",3.0,HONDURAS,2,1.0,0.0,0.0,2020
1702,1703,NaN,TUXTLA GUTIERREZ,TECUN UMAN,1659.0,GUATEMALA,1346,235.0,42.0,36.0,2020
1703,1704,NaN,NaN,EL CARMEN,152.0,GUATEMALA,122,21.0,2.0,7.0,2020
1704,1705,NaN,NaN,"SIGLO XXI, TAPACHULA",1283.0,GUATEMALA,696,107.0,145.0,335.0,2020
1705,1706,NaN,NaN,NaN,718.0,HONDURAS,452,100.0,61.0,105.0,2020
1706,1707,NaN,NaN,NaN,62.0,NICARAGUENSE,42,13.0,4.0,3.0,2020
1707,1708,NaN,NaN,NaN,330.0,SALVADOREÑA,231,56.0,18.0,25.0,2020
1708,1709,NaN,NaN,ESTACIÓN MIGRATORIA DE ACAYUCAN,137.0,SALVADOREÑA,99,24.0,8.0,6.0,2020
1709,1710,NaN,NaN,ESTACIÓN MIGRATORIA DE IZTAPALAPA,157.0,HONDUREÑA,108,27.0,5.0,17.0,2020
1710,1711,NaN,NaN,NaN,1.0,SALVADOREÑA,0,1.0,0.0,0.0,2020

# Empezamos a arreglar casos específicos - Regla especial 3 y regla especial 1

In [164]:
# Cambiamos donde aparece la columna 'year' en el orden

In [165]:
cols = master.columns.tolist()
cols.remove('year')
cols.insert(cols.index('id_fila_og') + 1, 'year')
master = master[cols]
print(master.columns.tolist())
master.head()

['id_fila_og', 'year', 'oficina_regional', 'lugar_origen', 'lugar_destino', 'total_migrantes_traslado', 'nacionalidad', 'hombres', 'mujeres', 'niñas', 'niños']

,id_fila_og,year,oficina_regional,lugar_origen,lugar_destino,total_migrantes_traslado,nacionalidad,hombres,mujeres,niñas,niños
0,1,2017,Chihuahua,JANOS,CHIHUAHUA - IZTAPALAPA,32.0,"32 GUATEMALTECOS (19 JAN, 13 CUU)",31.0,1.0,0.0,0.0
1,2,2017,Chihuahua,JANOS,CHIHUAHUA - IZTAPALAPA,29.0,"24 GUATEMALTECOS (06 JAN, 18 CUU), 04 HONDUREÑ...",28.0,1.0,0.0,0.0
2,3,2017,Chihuahua,JANOS,IZTAPALAPA,33.0,"23 GUATEMALTECOS, 03 HONDUREÑOS Y 07 SALVADOR...",15.0,6.0,9.0,3.0
3,4,2017,Chihuahua,JANOS,IZTAPALAPA,29.0,"08 GUATEMALTECOS, 15 HONDUREÑOS Y 06 SALVADOR...",11.0,8.0,6.0,4.0
4,5,2017,Chihuahua,JANOS,CHIHUAHUA - IZTAPALAPA,36.0,"32 GUATEMALTECOS (21 JAN, 09 JRZ, 02 CUU) , 02...",26.0,4.0,2.0,4.0

### Tenemos que arreglar un desajuste documentado en regla especial 3: el rango de Coahuila en 2022 está desfasada, por lo que todos los valores en el rango deberían trasladarse por una columna a la derecha. También, en el área de la columna oficina_regional, deberíamos agregar en cada fila el valor 'Coahuila'.

In [166]:
# Definimos el rango
mask = master['id_fila_og'].between(4878, 5373)  

# Usamos forward-fill para llenar los nombres de lugar_origen y lugar_destino para este rango, reconociendo el desfase en que se encuentran actualmente
master.loc[mask, 'lugar_origen'] = master.loc[mask, 'lugar_origen'].ffill()
master.loc[mask, 'oficina_regional'] = master.loc[mask, 'oficina_regional'].ffill()

# Definir cuáles columnas queremos mover (todas menos id_fila_og y year)
cols_to_shift = master.columns[2:]  

# Permitir tipos mixtos
master[cols_to_shift] = master[cols_to_shift].astype(object)

# Las movemos
master.loc[mask, cols_to_shift] = master.loc[mask, cols_to_shift].shift(periods=1, axis=1)

# Agregamos "Coahuila" como valor de oficina_regional para todo el rango
master.loc[mask, cols_to_shift[0]] = 'Coahuila'

In [167]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.max_colwidth', None):
    display(master.loc[mask, :])

,id_fila_og,year,oficina_regional,lugar_origen,lugar_destino,total_migrantes_traslado,nacionalidad,hombres,mujeres,niñas,niños
4877,4878,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,"02 COLOMBIANA, 07 PERUANA Y 31 VENEZOLANA",22,13,3.0,2.0
4878,4879,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,"03 CUBANA, 01 DOMINICANA, 21 NICARAGÜENSE, 06 UZBEKISTANIES Y 09 VENEZOLANA",32,8,0.0,0.0
4879,4880,2022,Coahuila,Torreon,"VILLAHERMOSA, TABASCO",40,"01 COLOMBIANA, 13 CUBANA, 01 HONDUREÑA, 03 NICARAGÜENSE Y 22 VENEZOLANA",15,14,6.0,5.0
4880,4881,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,"03 CUBANA, 02 ESTADOUNIDENSE, 02 GUATEMALTECA, 01 HONDUREÑA Y 32 VENEZOLANA",13,18,5.0,4.0
4881,4882,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",81,"01 BRASILEÑA, 07 COLOMBIANA, 16 CUBANA, 06 GEORGIA, 14 UZBEKA Y 37 VENEZOLANA",58,21,1.0,1.0
4882,4883,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",42,"02 COLOMBIANA, 07 CUBANA, 01 SURINAME Y 32 VENEZOLANA",20,13,7.0,2.0
4883,4884,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,"01 DOMINICANA, 01 ECUATORIANA, 01 HAITIANA Y 37 VENEZOLANA",21,19,0.0,0.0
4884,4885,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,"02 COLOMBIANA, 11 NICARAGÜENSE, 13 UZBEKISTANI, 14 VENEZOLANA",21,11,4.0,4.0
4885,4886,2022,Coahuila,Monclova,"VILLAHERMOSA, TABASCO",40,"01 BOLIVIANA, 01 COLOMBIANA, 13 CUBANA, 05 NICARAGÜENSE Y 20 VENEZOLANA",25,12,2.0,1.0
4886,4887,2022,Coahuila,Torreon,"VILLAHERMOSA, TABASCO",50,"01 ARGENTINA, 02 COLOMBIANA Y 47 VENEZOLANA",15,15,11.0,9.0
4887,4888,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,"08 COLOMBIANA, 32 VENEZOLANA",36,4,0.0,0.0
4888,4889,2022,Coahuila,Monclova,"VILLAHERMOSA, TABASCO",40,19 CUBANA Y 21 NICARAGÜENSE,33,7,0.0,0.0
4889,4890,2022,Coahuila,Monclova,"VILLAHERMOSA, TABASCO",40,"01 COLOMBIANA, 14 CUBANA, 09 SALVADOREÑA Y 16 VENEZOLANA",16,24,0.0,0.0
4890,4891,2022,Coahuila,Monclova,"VILLAHERMOSA, TABASCO",40,"06 COLOMBIANA, 12 CUBANA, 01 NICARAGÜENSE, 07 UZBEKISTANI Y 14 VENEZOLANA",31,9,0.0,0.0
4891,4892,2022,Coahuila,Torreon,"VILLAHERMOSA, TABASCO",34,"04 COLOMBIANA, 02 CUBANA, 01 NICARAGÜENSE, 01 PERUANA Y 26 VENEZOLANA",13,14,3.0,4.0
4892,4893,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,"05 COLOMBIANA, 08 CUBANA, 10 NICARAGÜENSE, 16 VENEZOLANA Y 01 ZURINAM",25,7,2.0,6.0
4893,4894,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,"03 BRASILEÑA, 08 COLOMBIANA, 10 CUBANA, 01 KIRGUISTANI, 08 NICARAGÜENSE, 03 PERU, 01 RUSA, 05 VENEZOLANA Y 01 YEMENITA",29,11,0.0,0.0
4894,4895,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,"03 BRASILEÑA, 03 COLOMBIANA, 24 NICARAGÜENSE, 02 SYRIA, 02 TAYIKO, 01 UZBEKISTANI, 05 VENEZOLANA",23,9,4.0,4.0
4895,4896,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,34 CUBANA Y 06 NICARAGÜENSE,22,17,0.0,1.0
4896,4897,2022,Coahuila,Piedras Negras,"VILLAHERMOSA, TABASCO",80,"01 ANGOLESA, 09 COLOMBIANA, 28 CUBANA, 05 SALVADOREÑA, 13 NICARAGÜENSE, 16 SALVADOREÑA, 04 UZBEKISTANI Y 04 VENEZOLANA",59,20,1.0,0.0
4897,4898,2022,Coahuila,Piedras Negras,"VILLAHERMOSA, TABASCO",39,"02 COLOMBIANA, 32 CUBANA, 02 GUATEMALTECA, 01 HAITIANA, 01 NICARAGÜENSE Y 01 SALVADOREÑA",21,12,4.0,2.0
4898,4899,2022,Coahuila,Piedras Negras,"VILLAHERMOSA, TABASCO",40,"27 CUBANA, 10 NICARAGÜENSE Y 03 VENEZOLANA",25,15,0.0,0.0
4899,4900,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,40 CUBANA,29,11,0.0,0.0
4900,4901,2022,Coahuila,Monclova,"VILLAHERMOSA, TABASCO",40,40 CUBANA,24,16,0.0,0.0
4901,4902,2022,Coahuila,Torreon,"VILLAHERMOSA, TABASCO",41,"21 CUBANA, 19 NICARAGÜENSE Y 01 SURINAM",22,10,6.0,3.0
4902,4903,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,"03 COLOMBIANA, 25 CUBANA, 11 NICARAGÜENSE Y 01 VENEZOLANA",24,16,0.0,0.0
4903,4904,2022,Coahuila,Piedras Negras,"VILLAHERMOSA, TABASCO",40,"01 CENTROAFRICANA, 03 COLOMBIANA, 15 CUBANA, 01 MAURITANA, 09 NICARAGÜENSE, 03 SENEGALESA Y 08 VENEZOLANA",27,11,0.0,2.0
4904,4905,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",39,"02 ARGENTINA, 03 BURKINA FASO, 09 COLOMBIANA, 10 CUBANA, 01 GHANESA, 10 NICARAGÜENSE, 04 VENEZOLANA",18,13,4.0,4.0
4905,4906,2022,Coahuila,Piedras Negras,"VILLAHERMOSA, TABASCO",76,"23 NICARAGÜENSE, 03 PERUANA, 14 SALVADOREÑA Y 05 VENEZOLANA",42,24,4.0,6.0
4906,4907,2022,Coahuila,Piedras Negras,"VILLAHERMOSA, TABASCO",81,"02 BELICEÑA, 09 COLOMBIANA, 01 COSTARICENSE, 42 CUBANA, 01 GUINESA, 16 NICARAGÜENSE, 04 PAKISTANI, 02 SALVADOREÑA Y 04 VENEZOLANA",41,26,5.0,9.0
4907,4908,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,"13 CUBANA, 06 DOMINICANA, 03 NICARAGÜENSE, 16 SALVADOREÑA Y 02 USBEKISTANI",31,9,0.0,0.0
4908,4909,2022,Coahuila,Monclova,"VILLAHERMOSA, TABASCO",79,"03 COLOMBIANA, 63 CUBANA, 04 NICARAGÜENSE Y 09 VENEZOLANA",43,31,2.0,3.0
4909,4910,2022,Coahuila,Saltillo,"ACAYUCAN, VERACRUZ",50,50 GUATEMALTECA,38,12,0.0,0.0
4910,4911,2022,Coahuila,Monclova,"VILLAHERMOSA, TABASCO",40,"28 CUBANA, 02 SALVADOREÑA, 08 NICARAGÜENSE Y 02 PERUANA",31,9,0.0,0.0
4911,4912,2022,Coahuila,Saltillo,"ACAYUCAN, VERACRUZ",38,38 HONDUREÑA,37,1,0.0,0.0
4912,4913,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,"30 CUBANA, 02 ECUATORIANA, 02 SALVADOREÑA, 06 VENEZOLANA",27,11,2.0,0.0
4913,4914,2022,Coahuila,Monclova,"VILLAHERMOSA, TABASCO",40,"34 CUBANA, 05 GHANESA Y 01 NICARAGÜENSE",23,14,1.0,2.0
4914,4915,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",76,"15 HONDUREÑA, 54 NICARAGÜENSE Y 07 SALVADOREÑA",59,17,0.0,0.0
4915,4916,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",80,80 HONDUREÑA,78,2,0.0,0.0
4916,4917,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,"11 CUBANA, 01 ECUATORIANA, 01 HAITIANA, 10 NICARAGÜENSE, 01 PERUANA, 15 SALVADOREÑA Y 01 VENEZOLANA",35,5,0.0,0.0
4917,4918,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,"13 CUBANA, 01 ECUATORIANA, 21 NICARAGÜENSE Y 05 SALVADOREÑA",31,9,0.0,0.0
4918,4919,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,"06 COLOMBIANA, 18 CUBANA, 14 NICARAGÜENSE Y 02 SALVADOREÑA",32,8,0.0,0.0
4919,4920,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",38,"10 COLOMBIANA, 06 CUBANA, 17 NICARAGÜENSE, 02 SALVADOREÑA Y 03 VENEZOLANA",30,8,0.0,0.0
4920,4921,2022,Coahuila,Piedras Negras,"VILLAHERMOSA, TABASCO",41,41 HONDUREÑA,36,5,0.0,0.0
4921,4922,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,"16 CUBANA, 01 GHANESA, 16 NICARAGÜENSE, 02 DOMINICANA, 02 SALVADOREÑA Y 03 SENEGALESA",33,7,0.0,0.0
4922,4923,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",35,35 HONDUREÑA,26,9,0.0,0.0
4923,4924,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",12,"02 CUBANA, 10 NICARAGÜENSE",5,7,0.0,0.0
4924,4925,2022,Coahuila,Torreon,"VILLAHERMOSA, TABASCO",40,"02 ARGENTINA, 14 CUBANA, 21 NICARAGÜENSE Y 03 VENEZOLANA",19,21,0.0,0.0
4925,4926,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,"11 CUBANA, 05 HONDUREÑA Y 24 NICARAGÜENSE",29,11,0.0,0.0
4926,4927,2022,Coahuila,Piedras Negras,"NUEVO LAREDO, TAMAULIPAS",12,12 HONDUREÑA,2,10,0.0,0.0
4927,4928,2022,Coahuila,Piedras Negras,"NUEVO LAREDO, TAMAULIPAS",18,18 HONDUREÑA,15,3,0.0,0.0
4928,4929,2022,Coahuila,Piedras Negras,"VILLAHERMOSA, TABASCO",40,"04 COLOMBIANA, 29 CUBANA, 02 SALVADOREÑA, 03 NICARAGÜENSE Y 02 VENEZOLANA",28,12,0.0,0.0
4929,4930,2022,Coahuila,Monclova,"VILLAHERMOSA, TABASCO",40,"01 COLOMBIANA, 13 CUBANA, 25 NICARAGÜENSE Y 01 VENEZOLANA",33,7,0.0,0.0
4930,4931,2022,Coahuila,Piedras Negras,"VILLAHERMOSA, TABASCO",40,"05 COLOMBIANA, 26 CUBANA Y 09 NICARAGÜENSE",25,14,1.0,0.0
4931,4932,2022,Coahuila,Piedras Negras,"VILLAHERMOSA, TABASCO",82,"08 CUBANA, 18 ECUATORIANA, 49 NICARAGÜENSE, 02 SALVADOREÑA Y 05 VENEZOLANA",50,22,6.0,4.0
4932,4933,2022,Coahuila,Piedras Negras,"VILLAHERMOSA, TABASCO",41,"03 COLOMBIANA, 07 CUBANA, 07 NICARAGÜENSE, 03 PERUANA Y 21 SALVADOREÑA",27,14,0.0,0.0
4933,4934,2022,Coahuila,Saltillo,ZACATECAS,10,10 GUATEMALTECA,6,4,0.0,0.0
4934,4935,2022,Coahuila,Saltillo,ZACATECAS,50,50 HONDUREÑA,49,1,0.0,0.0
4935,4936,2022,Coahuila,Saltillo,CIUDAD DE MEXICO,40,40 HONDUREÑA,32,8,0.0,0.0
4936,4937,2022,Coahuila,Monclova,SAN LUIS POTOSI,41,"01 BOLIVIANA, 01 COLOMBIANA, 06 CUBANA, 01 ECUATORIANA Y 32 VENEZOLANA",35,6,0.0,0.0
4937,4938,2022,Coahuila,Monclova,ZACATECAS,39,39 HONDUREÑA,34,5,0.0,0.0
4938,4939,2022,Coahuila,Saltillo,CIUDAD DE MEXICO,40,40 HONDUREÑA,39,1,0.0,0.0
4939,4940,2022,Coahuila,Saltillo,CIUDAD DE MEXICO,40,24 GUATEMALTECA Y 16 HONDUREÑA,40,0,0.0,0.0
4940,4941,2022,Coahuila,Monclova,"MONTERREY, NUEVO LEON",30,06 CUBANA Y 24 NICARAGÜENSE,29,1,0.0,0.0
4941,4942,2022,Coahuila,Monclova,CIUDAD DE MEXICO,5,05 GUATEMALTECA,3,2,0.0,0.0
4942,4943,2022,Coahuila,Monclova,CIUDAD DE MEXICO,29,29 HONDUREÑA,23,6,0.0,0.0
4943,4944,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",37,"01 COLOMBIANA, 04 CUBANA, 26 NICARAGÜENSE, 01 PERUANA, 01 DOMINICANA, 01 SALVADOREÑA, 01 URUGUAYA Y 02 VENEZOLANA",25,12,0.0,0.0
4944,4945,2022,Coahuila,Monclova,"VILLAHERMOSA, TABASCO",39,"01 CHINA, 05 COLOMBIANA, 04 CUBANA, 05 DOMINICANA, 05 ECUATORIANA, 03 NICARAGÜENSE, 01 PALESTINA, 13 SALVADOREÑA Y 02 VENEZOLANA",26,13,0.0,0.0
4945,4946,2022,Coahuila,Piedras Negras,"VILLAHERMOSA, TABASCO",30,"04 CUBANA, 13 NICARAGÜENSE Y 13 VENEZOLANA",26,4,0.0,0.0
4946,4947,2022,Coahuila,Monclova,ZACATECAS,25,21 VENEZOLANA Y 04 CUBANA,22,3,0.0,0.0
4947,4948,2022,Coahuila,Piedras Negras,ZACATECAS,40,40 VENEZOLANA,33,7,0.0,0.0
4948,4949,2022,Coahuila,Saltillo,ZACATECAS,20,"01 COLOMBIANA, 01 CUBANA, 02 PERUANA, 03 SALVADOREÑA Y 13",16,4,0.0,0.0
4949,4950,2022,Coahuila,Saltillo,ZACATECAS,37,22 GUATEMALTECA Y 15 HONDUREÑA,31,6,0.0,0.0
4950,4951,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",36,"01 COLOMBIANA, 04 CUBANA, 16 NICARAGÜENSE, 01 PERUANA, 07 SALVADOREÑA Y 07 VENEZOLANA",24,12,0.0,0.0
4951,4952,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",33,"03 COLOMBIANA, 03 ECUATORIANA, 01 SALVADOREÑA, 20 NICARAGÜENSE Y 06 VENEZOLANA",23,10,0.0,0.0
4952,4953,2022,Coahuila,Saltillo,"VILLAHERMOSA, TABASCO",40,"01 BOLIVIANA, 04 COLOMBIANA, 08 CUBANA, 11 NICARAGÜENSE, 06 SALVADOREÑA Y 10 VENEZOLANA",30,10,0.0,0.0
4953,4954,2022,Coahuila,Monclova,"VILLAHERMOSA, TABASCO",40,"02 COLOMBIANA, 01 ECUATORIANA, 16 NICARAGÜENSE, 01 PERUANO, 02 SALVADOREÑA Y 18 VENEZOLANA",28,12,0.0,0.0
4954,4955,2022,Coahuila,Saltillo,CIUDAD DE MEXICO,6,06 GUATEMALTECA,6,0,0.0,0.0
4955,4956,2022,Coahuila,Saltillo,ZACATECAS,45,45 HONDUREÑA,41,4,0.0,0.0
4956,4957,2022,Coahuila,Torreon,VILLAHERMOSA,37,"22 VENEZOLANOS, 13 CUBANOS, 01 HONDUREÑOS, 01 NICARAGUENSE.",9,8,6.0,4.0
4957,4958,2022,Coahuila,Torreon,VILLAHERMOSA,40,"32 VENEZOLANOS, 08 CUBANOS., 01 SURINAME.",4,8,8.0,2.0
4958,4959,2022,Coahuila,Torreon,VILLAHERMOSA,44,44 VENEZOLANOS,12,11,11.0,10.0
4959,4960,2022,Coahuila,Torreon,VILLAHERMOSA,49,"46 VENEZOLANOS, 02 COLOMBIANOS, 01 PERUANO.",12,15,11.0,11.0
4960,4961,2022,Coahuila,Torreon,VILLAHERMOSA,24,"17 VENEZOLANOS, 03 HONDUREÑOS, 02 COLOMBIANOS. 01 PERUANO, 01 PANAMEÑO",5,7,3.0,4.0
4961,4962,2022,Coahuila,Torreon,AEROPUERTO INT. MONTERREY,40,40 CUBANOS.,6,8,7.0,4.0
4962,4963,2022,Coahuila,Torreon,SALTILLO,9,09 HONDUREÑOS.,1,3,3.0,2.0
4963,4964,2022,Coahuila,Torreon,VILLAHERMOSA,39,"17 CUBANOS, 09 NICARAGUENSES, 03 PERUANOS, 10 VENEZOLANOS.",9,12,6.0,12.0
4964,4965,2022,Coahuila,Torreon,VILLAHERMOSA,39,"18 CUBANOS, 09 NICARAGUENSES, 10 VENEZOLANOS, 03 PERUANOS.",9,12,7.0,11.0
4965,4966,2022,Coahuila,Torreon,VILLAHERMOSA,39,"24 CUBANOS, 06 NICARAGUENSE, 03 BURKINA FASO, 06 COLOMBIA.",4,7,3.0,5.0
4966,4967,2022,Coahuila,Torreon,AEROPUERTO INT. CD. DE MEXICO,23,23 SALVADOREÑOS,2,3,3.0,3.0
4967,4968,2022,Coahuila,Torreon,SALTILLO,36,"17 HONDUREÑOS, 09 NICARAGUENSES, 10 CUBANOS.",3,7,3.0,13.0
4968,4969,2022,Coahuila,Torreon,SALTILLO,40,"37 CUBANOS, 03 SALVADOREÑOS.",17,22,0.0,1.0
4969,4970,2022,Coahuila,Torreon,AEROPUERTO INT. PLAN DE GUADALUPE,49,"32 CUBANOS, 13 VENEZOLANOS, 01 ECUATORIANA, 03 NICARAGUENSES.",4,3,7.0,3.0
4970,4971,2022,Coahuila,Torreon,AEROPUERTO INT. PLAN DE GUADALUPE,41,"10 CUBANOS, 09 COLOMBIANOS, 09 VENEZOLANOS, 02 NICARAGUENSES, 02 ECUATORIANOS, 03 PERUANOS, 03 HAITIANOS, 02 BRASILEÑOS. 01 CHILENO.",18,7,0.0,0.0
4971,4972,2022,Coahuila,Torreon,"AEROPUERTO INT, DE MONTERREY",32,"17 HONDUREÑOS, 15 GUATEMALTECOS.",6,8,12.0,6.0
4972,4973,2022,Coahuila,Torreon,SALTILLO,39,"17 NICARAGUENSES, 09 CUBANOS, 09 HONDUREÑOS, 01 SALVADOREÑO, 03 GUATEMALTECOS.",32,7,0.0,0.0
4973,4974,2022,Coahuila,Torreon,AEROPUERTO INT. PLAN DE GUADALUPE,32,"06 VENEZOLANOS, 11 SALVADOREÑOS, 08 CUBANOS, 07 NICARAGUENSES.",6,11,6.0,9.0
4974,4975,2022,Coahuila,Torreon,SALTILLO,25,"10 GUATEMALTECOS, 14 NICARAGUENSE, 01 HONDUREÑO.",17,8,0.0,0.0
4975,4976,2022,Coahuila,Torreon,AEROPUERTO INT. PLAN DE GUADALUPE,50,50 HONDUREÑOS,2,10,12.0,26.0
4976,4977,2022,Coahuila,Torreon,SALTILLO,46,"22 HONDUREÑOS, 02 SALVADOREÑOS, 07 CUBANOS, 12 NICARAGUENSE, 02 DOMINICANOS, 01 ECUATORIANO.",34,12,0.0,0.0
4977,4978,2022,Coahuila,Torreon,SALTILLO,41,"24 NICARAGUENSES, 16 CUBANOS, 01 GUATEMALTECA.",29,12,0.0,0.0
4978,4979,2022,Coahuila,Torreon,VILLAHERMOSA,40,"19 CUBANOS, 02 ARGENTINOS, 16 NICARAGUENSES, 03 VENEZOLANOS",7,8,5.0,6.0
4979,4980,2022,Coahuila,Torreon,AWROPUERTO INT. PLAN DE GUADALUPE,40,40 HONDUREÑOS.,2,2,7.0,11.0
4980,4981,2022,Coahuila,Torreon,AEROPUERTO INT. MONTERREY,38,38 GUATEMALTECOS.,0,0,15.0,5.0
4981,4982,2022,Coahuila,Torreon,MORELIA,34,"26 HONDUREÑOS, 03 SALVADOREÑOS, 01 GUATEMALTECO, 01 CUBANO, 03 NICARAGUENSE.",NaN,0,0.0,0.0
4982,4983,2022,Coahuila,Torreon,CIUDAD DE MEXICO,42,"15 CUBANOS, 10 VENEZOLANOS, 17 HONDUREÑOS.",16,10,3.0,7.0
4983,4984,2022,Coahuila,Torreon,ZACATECAS,40,"10 CUBANOS, 10 GUATEMALTECOS, 17 HONDUREÑOS, 03 NICARAGUENSES.",32,8,0.0,0.0
4984,4985,2022,Coahuila,Torreon,ZACATECAS,NaN,NaN,NaN,0,0.0,0.0
4985,4986,2022,Coahuila,Torreon,VILLAHERMOSA,37,"22 VENEZOLANOS, 13 CUBANOS, 01 HONDUREÑOS, 01 NICARAGUENSE.",9,8,6.0,4.0
4986,4987,2022,Coahuila,Torreon,VILLAHERMOSA,40,"32 VENEZOLANOS, 08 CUBANOS., 01 SURINAME.",4,8,8.0,2.0
4987,4988,2022,Coahuila,Torreon,VILLAHERMOSA,44,44 VENEZOLANOS,12,11,11.0,10.0
4988,4989,2022,Coahuila,Torreon,VILLAHERMOSA,49,"46 VENEZOLANOS, 02 COLOMBIANOS, 01 PERUANO.",12,15,11.0,11.0
4989,4990,2022,Coahuila,Torreon,VILLAHERMOSA,24,"17 VENEZOLANOS, 03 HONDUREÑOS, 02 COLOMBIANOS. 01 PERUANO, 01 PANAMEÑO",5,7,3.0,4.0
4990,4991,2022,Coahuila,Torreon,AEROPUERTO INT. MONTERREY,40,40 CUBANOS.,6,8,7.0,4.0
4991,4992,2022,Coahuila,Torreon,SALTILLO,9,09 HONDUREÑOS.,1,3,3.0,2.0
4992,4993,2022,Coahuila,Torreon,VILLAHERMOSA,39,"17 CUBANOS, 09 NICARAGUENSES, 03 PERUANOS, 10 VENEZOLANOS.",9,12,6.0,12.0
4993,4994,2022,Coahuila,Torreon,VILLAHERMOSA,39,"18 CUBANOS, 09 NICARAGUENSES, 10 VENEZOLANOS, 03 PERUANOS.",9,12,7.0,11.0
4994,4995,2022,Coahuila,Torreon,VILLAHERMOSA,39,"24 CUBANOS, 06 NICARAGUENSE, 03 BURKINA FASO, 06 COLOMBIA.",4,7,3.0,5.0
4995,4996,2022,Coahuila,Torreon,AEROPUERTO INT. CD. DE MEXICO,23,23 SALVADOREÑOS,2,3,3.0,3.0
4996,4997,2022,Coahuila,Torreon,SALTILLO,36,"17 HONDUREÑOS, 09 NICARAGUENSES, 10 CUBANOS.",3,7,3.0,13.0
4997,4998,2022,Coahuila,Torreon,SALTILLO,40,"37 CUBANOS, 03 SALVADOREÑOS.",17,22,0.0,1.0
4998,4999,2022,Coahuila,Torreon,AEROPUERTO INT. PLAN DE GUADALUPE,49,"32 CUBANOS, 13 VENEZOLANOS, 01 ECUATORIANA, 03 NICARAGUENSES.",4,3,7.0,3.0
4999,5000,2022,Coahuila,Torreon,AEROPUERTO INT. PLAN DE GUADALUPE,41,"10 CUBANOS, 09 COLOMBIANOS, 09 VENEZOLANOS, 02 NICARAGUENSES, 02 ECUATORIANOS, 03 PERUANOS, 03 HAITIANOS, 02 BRASILEÑOS. 01 CHILENO.",18,7,0.0,0.0
5000,5001,2022,Coahuila,Torreon,"AEROPUERTO INT, DE MONTERREY",32,"17 HONDUREÑOS, 15 GUATEMALTECOS.",6,8,12.0,6.0
5001,5002,2022,Coahuila,Torreon,SALTILLO,39,"17 NICARAGUENSES, 09 CUBANOS, 09 HONDUREÑOS, 01 SALVADOREÑO, 03 GUATEMALTECOS.",32,7,0.0,0.0
5002,5003,2022,Coahuila,Torreon,AEROPUERTO INT. PLAN DE GUADALUPE,32,"06 VENEZOLANOS, 11 SALVADOREÑOS, 08 CUBANOS, 07 NICARAGUENSES.",6,11,6.0,9.0
5003,5004,2022,Coahuila,Torreon,SALTILLO,25,"10 GUATEMALTECOS, 14 NICARAGUENSE, 01 HONDUREÑO.",17,8,0.0,0.0
5004,5005,2022,Coahuila,Torreon,AEROPUERTO INT. PLAN DE GUADALUPE,50,50 HONDUREÑOS,2,10,12.0,26.0
5005,5006,2022,Coahuila,Torreon,SALTILLO,46,"22 HONDUREÑOS, 02 SALVADOREÑOS, 07 CUBANOS, 12 NICARAGUENSE, 02 DOMINICANOS, 01 ECUATORIANO.",34,12,0.0,0.0
5006,5007,2022,Coahuila,Torreon,SALTILLO,41,"24 NICARAGUENSES, 16 CUBANOS, 01 GUATEMALTECA.",29,12,0.0,0.0
5007,5008,2022,Coahuila,Torreon,VILLAHERMOSA,40,"19 CUBANOS, 02 ARGENTINOS, 16 NICARAGUENSES, 03 VENEZOLANOS",7,8,5.0,6.0
5008,5009,2022,Coahuila,Torreon,AWROPUERTO INT. PLAN DE GUADALUPE,40,40 HONDUREÑOS.,2,2,7.0,11.0
5009,5010,2022,Coahuila,Torreon,AEROPUERTO INT. MONTERREY,38,38 GUATEMALTECOS.,0,0,15.0,5.0
5010,5011,2022,Coahuila,Torreon,MORELIA,34,"26 HONDUREÑOS, 03 SALVADOREÑOS, 01 GUATEMALTECO, 01 CUBANO, 03 NICARAGUENSE.",NaN,0,0.0,0.0
5011,5012,2022,Coahuila,Torreon,CIUDAD DE MEXICO,42,"15 CUBANOS, 10 VENEZOLANOS, 17 HONDUREÑOS.",16,10,3.0,7.0
5012,5013,2022,Coahuila,Torreon,ZACATECAS,40,"10 CUBANOS, 10 GUATEMALTECOS, 17 HONDUREÑOS, 03 NICARAGUENSES.",32,8,0.0,0.0
5013,5014,2022,Coahuila,Monclova,VILLAHERMOSA,12,"02 CUBANA. 08 VENEZOLANA, 02 HONDUREÑA",9,3,0.0,0.0
5014,5015,2022,Coahuila,Monclova,VILLAHERMOSA,16,"06 CUBANA, 09 UZBEKA, 01 GEORGIA",13,4,0.0,0.0
5015,5016,2022,Coahuila,Monclova,VILLAHERMOSA,5,"04 UZBEKISTAN, 01 BOLIVIANA",4,1,0.0,0.0
5016,5017,2022,Coahuila,Monclova,IZTAPALAPA,14,14 HONDUEÑA,14,0,0.0,0.0
5017,5018,2022,Coahuila,Monclova,VILLAHERMOSA,40,40 CUBANA,23,17,0.0,0.0
5018,5019,2022,Coahuila,Monclova,TAMAULIPAS,41,41 HONDUREÑA,37,4,0.0,0.0
5019,5020,2022,Coahuila,Monclova,SALTILLO,53,"46 HONDUREÑA, 06 GUATEMALTECA, 01 SALVADOREÑA",44,9,0.0,0.0
5020,5021,2022,Coahuila,Monclova,RAMOS ARIZPE,72,"01 VENEZOLANA, 71 CUBANA",39,24,4.0,5.0
5021,5022,2022,Coahuila,Monclova,VILLAHERMOSA,42,"09 VENEZOLANA, 26 CUBANA, 03 COLOMBIANA, 04 NICARAGÜENSE",23,14,3.0,2.0
5022,5023,2022,Coahuila,Monclova,VILLAHERMOSA,22,"03 NICARAGÜENSE, 19 CUBANA",18,4,0.0,0.0
5023,5024,2022,Coahuila,Monclova,IZTAPALAPA,27,"23 HONDUREÑA, 03 GUATEMALTECA, 01 SALVADOREÑA",23,4,0.0,0.0
5024,5025,2022,Coahuila,Monclova,VILLAHERMOSA,30,"29 CUBANA, 01 DOMINICANA",19,11,0.0,0.0
5025,5026,2022,Coahuila,Monclova,ACAYUCAN,23,23 HONDUREÑA,23,0,0.0,0.0
5026,5027,2022,Coahuila,Monclova,VILLAHERMOSA,26,26 CUBANA,17,9,0.0,0.0
5027,5028,2022,Coahuila,Monclova,VILLAHERMOSA,40,40 HONDUREÑA,38,2,0.0,0.0
5028,5029,2022,Coahuila,Monclova,VILLAHERMOSA,16,"13 CUBANA, 01 ECUATORIANA, 02 NICARAGÜENSE",11,5,0.0,0.0
5029,5030,2022,Coahuila,Monclova,NUEVO LEON,26,"21 CUBANA, 05 NICARAGÜENSE",15,9,1.0,1.0
5030,5031,2022,Coahuila,Monclova,NUEVO LEON,6,06 HONDUREÑA,6,0,0.0,0.0
5031,5032,2022,Coahuila,Monclova,VILLAHERMOSA,27,"01 COLOMBIANA, 01 VENEZOLANA. 25 NICARAGÜENSE",23,4,0.0,0.0
5032,5033,2022,Coahuila,Monclova,SAN LUIS POTOSI,24,"01 ECUATORIANA, 01 BOLIVIANA, 22 VENEZOLANA",20,4,0.0,0.0
5033,5034,2022,Coahuila,Monclova,RAMOS ARIZPE,28,"24 VENEZOLANA, 01 PANAMEÑA, 01 SALVADAROÑE,A 02 DOMINICANA",9,12,5.0,3.0
5034,5035,2022,Coahuila,Monclova,MICHOACAN,41,"18 VENEZOLANA, 15 NICARAGÜENSE, 05 SALVADOREÑA, 02 GUATEMALTECA, 01 HONDUREÑA",25,9,3.0,4.0
5035,5036,2022,Coahuila,Monclova,RAMOS ARIZPE,35,35 HONDUREÑA,27,4,1.0,3.0
5036,5037,2022,Coahuila,Monclova,AGUASCALIENTES,40,"05 SALVADOREÑA, 04 GUATEMALTECA, 32 HONDUREÑA",33,7,0.0,0.0
5037,5038,2022,Coahuila,Monclova,IZTAPALAPA,39,"15 GUATEMALTECA, 23 HONDUREÑA, 01 CUBANA",28,11,0.0,0.0
5038,5039,2022,Coahuila,Monclova,ACAPULCO,40,"27 CUBANA, 01 ECUATORIANA, 06 VENEZOLANA, 05 SALVADOREÑA, 01 COLOMBIANA",27,13,0.0,0.0
5039,5040,2022,Coahuila,Monclova,ACAPULCO,38,"23 VENEZOLANA, 01 SALVADOREÑA, 07 NICARAGÜENSE, 05 CUBANA, 02 ECUATORIANA",28,9,0.0,0.0
5040,5041,2022,Coahuila,Monclova,NUEVO LEON,24,24 NICARAGÜENSE,24,0,0.0,0.0
5041,5042,2022,Coahuila,Monclova,AGUASCALIENTES,38,"01 CUBANA, 06 HONDUREÑA, 23 VENEZOLANA, 01 COLOMBIANA, 03 GUATEMALTECA",33,5,0.0,0.0
5042,5043,2022,Coahuila,Monclova,AGUASCALIENTES,30,"29 VENEZOLANA, 01 SALVADOREÑA",25,5,0.0,0.0
5043,5044,2022,Coahuila,Monclova,ZACATECAS,32,32 VENEZOLANA,26,6,0.0,0.0
5044,5045,2022,Coahuila,Monclova,IZTAPALAPA,41,"37 VENEZOLANA, 04 CUBANA",37,4,0.0,0.0

### Ahora, hay que rectificar otro caso especial documentado en la regla 1. Para el rango correspondiente, hay que sumar las categorías demográficas para cada fila y poner este valor como el total de migrantes trasladados.

In [168]:
mask_1 = (master['id_fila_og'].between(316, 318)) | (master['id_fila_og'] == 2750)

# Si los valores demográficos son NaN, ponerles mejor como 0's y sumarlos para los nuevos valores de total_migrantes_traslado
master.loc[mask_1, 'total_migrantes_traslado'] = (
    master.loc[mask_1, 'hombres'].fillna(0)
    + master.loc[mask_1, 'mujeres'].fillna(0)
    + master.loc[mask_1, 'niños'].fillna(0)
    + master.loc[mask_1, 'niñas'].fillna(0)
)

# Verificar
display(master.loc[mask_1, ['id_fila_og', 'hombres', 'mujeres', 'niños', 'niñas', 'total_migrantes_traslado']])

/var/folders/ct/w1dnv1_96gv76pztht3z9vgw0000gn/T/ipykernel_9390/969233967.py:5: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  master.loc[mask_1, 'hombres'].fillna(0)
/var/folders/ct/w1dnv1_96gv76pztht3z9vgw0000gn/T/ipykernel_9390/969233967.py:6: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  + master.loc[mask_1, 'mujeres'].fillna(0)
/var/folders/ct/w1dnv1_96gv76pztht3z9vgw0000gn/T/ipykernel_9390/969233967.py:7: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  + master.loc[mask_1, 'niños'].fillna(0)
/var/folders/ct/w1dnv1_96gv76pztht3z9vgw0000gn/T/ipykernel_9390/969233967.py:8: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  + master.loc[mask_1, 'niñas'].fillna(0)

      id_fila_og hombres mujeres niños niñas total_migrantes_traslado
315          316     180    90.0  31.0  40.0                    341.0
316          317      55    30.0  11.0  20.0                    116.0
317          318      10     6.0   2.0   3.0                     21.0
2749        2750       2     0.0   2.0   0.0                      4.0

# Rellenamos los espacios en blanco de la columna oficina_regional utilizando ffill

In [169]:
master['oficina_regional'] = master['oficina_regional'].ffill()

In [170]:
print(master['oficina_regional'].unique())

['Chihuahua' 'Hidalgo' 'Jalisco' 'Estado de México' 'Oaxaca'
 'Quintana Roo' 'San Luis Potosí' 'Tamaulipas' 'Zacatecas'
 'Aguascalientes' 'Baja California' 'Campeche' 'Chiapas'
 'Ciudad de México' 'Coahuila' 'Querétaro' 'Sinaloa' 'Tabasco' 'Tlaxcala'
 'Veracruz' 'Durango' 'Michoacán' 'Nayarit' 'Yucatán' 'Guanajuato'
 'Guerrero' 'Puebla' 'Nuevo León' 'Sonora']

# Creamos la columna "regla" que muestra la regla combinada identificada que aplica a cada fila

### Habiendo resuelto las reglas especiales 1 & 3, estos rangos quedan reasignados a regla N. Solo tenemos 4 reglas para resolver: N, M, 2 & 4.

#### Regla N

In [171]:
# Regla N por oficina
oficinas_N = ['Aguascalientes', 'Baja California', 'Campeche', 'Chihuahua', 'Ciudad de México', 'Coahuila', 'Guanajuato', 'Guerrero', 'Hidalgo', 'Estado de México', 'Michoacán', 'Nayarit', 'Oaxaca', 'Puebla', 'Querétaro', 'San Luis Potosí', 'Sinaloa', 'Tabasco', 'Tamaulipas', 'Tlaxcala', 'Zacatecas']
master.loc[master['oficina_regional'].isin(oficinas_N), 'regla'] = 'N'

# Regla N por oficina y año
office_years_N = {
    'Chiapas': [2018],
    'Durango': [2023, 2024],
    'Jalisco': [2020, 2021, 2023, 2024],
    'Quintana Roo': [2017, 2018, 2019, 2020, 2021, 2023, 2024],
    'Sonora': [2022, 2024],
    'Veracruz': [2018, 2020, 2022, 2024],
    'Yucatán': [2021, 2023, 2024],
}

cond_N2 = pd.Series(False, index=master.index)
for office, years in office_years_N.items():
    cond_N2 |= (master['oficina_regional'] == office) & (master['year'].isin(years))

master.loc[cond_N2, 'regla'] = 'N'

# Regla N para ciertos valores de id_fila_og
cond_N3 = master['id_fila_og'].between(2772, 2780) | master['id_fila_og'].between(4599, 4634) | master['id_fila_og'].between(7598, 7848) |  master['id_fila_og'].between(4637, 4657) | master['id_fila_og'].between(7855, 8122) | master['id_fila_og'].between(1158, 1160) | master['id_fila_og'].between(6157, 6165) | master['id_fila_og'].between(4121, 4544) | master['id_fila_og'].between(4770, 4776) | master['id_fila_og'].between(8145, 8157) | master['id_fila_og'].between(12117, 12380) | master['id_fila_og'].between(12108, 12110)
master.loc[cond_N3, 'regla'] = 'N'

#### Regla M

In [172]:
# Regla M por oficina y año
office_years_M = {   
    'Durango': [2021, 2022],
    'Jalisco': [2017, 2018],
    'Yucatán': [2019, 2020],
}

cond_M2 = pd.Series(False, index=master.index)
for office, years in office_years_M.items():
    cond_M2 |= (master['oficina_regional'] == office) & (master['year'].isin(years))

master.loc[cond_M2, 'regla'] = 'M'

# Regla M para ciertos valores de id_fila_og
cond_M3 = master['id_fila_og'].between(2766, 2771) | master['id_fila_og'].between(4635, 4636) | master['id_fila_og'].between(4668, 4769) | master['id_fila_og'].between(8127, 8144) | master['id_fila_og'].between(1161, 1164) | master['id_fila_og'].between(6166, 6168) | master['id_fila_og'].between(4112, 4120) | master['id_fila_og'].between(12111, 12116)    
master.loc[cond_M3, 'regla'] = 'M'

#### Regla 2

In [173]:
# Regla 2 por oficina
oficinas_dos = ['Nuevo León']
master.loc[master['oficina_regional'].isin(oficinas_dos), 'regla'] = 'Dos'

# Regla 2 por oficina y año
office_years_dos = {   
    'Chiapas': [2019, 2020],
    'Sonora': [2023],
    'Yucatán': [2019, 2020],
}

cond_dos = pd.Series(False, index=master.index)
for office, years in office_years_dos.items():
    cond_dos |= (master['oficina_regional'] == office) & (master['year'].isin(years))

master.loc[cond_dos, 'regla'] = 'Dos'

# Regla 2 para ciertos valores de id_fila_og
cond_dos_2 = master['id_fila_og'].between(2753, 2765) | master['id_fila_og'].between(4658, 4667) | master['id_fila_og'].between(8123, 8126)
master.loc[cond_dos_2, 'regla'] = 'Dos'

#### Regla 4

In [174]:
# Regla 4 para ciertos valores de id_fila_og
cond_cuatro = master['id_fila_og'].between(7849, 7854) 
master.loc[cond_cuatro, 'regla'] = 'Cuatro'

In [175]:
# Verificar que no hay errores y todas las filas fueron asignadas una regla

In [176]:
master['regla'].value_counts(dropna=False)

regla
N         10824
Dos        2815
M           232
Cuatro        6
Name: count, dtype: int64

In [177]:
master.loc[master['regla'].isna(), 'id_fila_og'].tolist()

[]

# Rellenamos lugar_origen and lugar_destino utilizando ffill

### Lo hacemos sabiendo que muchas de las filas rellenas después se quitarán ya que les aplican reglas de quitar filas sin ciertos valores, o bien porque tienen valores en NaN

In [178]:
master['lugar_origen'] = master['lugar_origen'].ffill()
master['lugar_destino'] = master['lugar_destino'].ffill()

# Creamos la columna id_viaje y le asignamos sus valores según las reglas que aplican a cada fila

In [179]:
# Definir cuáles filas recibirán un valor de id_viaje
qualifies = (
    (master['regla'] == 'N')
    | (
        master['regla'].isin(['M', 'Dos', 'Cuatro'])
        & master['total_migrantes_traslado'].notna()
    )
)

# Asignar id_viaje
master['id_viaje'] = np.nan
master.loc[qualifies, 'id_viaje'] = range(1, qualifies.sum() + 1)

In [180]:
# Checamos nuestro trabajo
master[['id_fila_og', 'regla', 'total_migrantes_traslado', 'id_viaje']].sample(30)

       id_fila_og regla total_migrantes_traslado  id_viaje
9315         9316   Dos                      NaN       NaN
13513       13514     N                       35   11033.0
2110         2111     N                     34.0    2068.0
4055         4056     N                       32    3990.0
2821         2822     N                       28    2766.0
5477         5478   Dos                       40    5309.0
8746         8747     N                     39.0    8098.0
8987         8988     N                     24.0    8339.0
12913       12914   Dos                      NaN       NaN
10768       10769   Dos                      NaN       NaN
7233         7234     N                       21    6602.0
12448       12449     N                       29   10215.0
11894       11895     N                     40.0    9665.0
8629         8630     N                     30.0    7981.0
9682         9683   Dos                      NaN       NaN
5145         5146     N                       37    5000.0
10197       10198   Dos                      NaN       NaN
2763         2764   Dos                        5    2712.0
8769         8770     N                     32.0    8121.0
13378       13379     N                       32   10898.0
9670         9671   Dos                      NaN       NaN
12471       12472     N                       40   10238.0
545           546     N                       41     518.0
12730       12731     N                       44   10497.0
5029         5030     N                       26    4884.0
7208         7209     N                       38    6577.0
3290         3291     N                       17    3225.0
8063         8064     N                     41.0    7428.0
13700       13701     N                       37   11220.0
3032         3033     M                       43    2971.0

In [181]:
print("Con id_viaje:", master['id_viaje'].notna().sum())
print("Sin id_viaje:", master['id_viaje'].isna().sum())
print("Total filas:", len(master))

Con id_viaje: 11396
Sin id_viaje: 2481
Total filas: 13877

# Las filas con regla N ya están listas para la limpieza, pero aún debemos terminar la concatenación para reglas M, 2, y 4

### Regla M:

In [182]:
# Quitamos todas las filas con regla M que no tienen un valor para id_viaje
master = master[~((master['regla'] == 'M') & (master['id_viaje'].isna()))]

In [183]:
# Verificar que no permanezca ninguna fila con regla == 'M' y id_viaje NaN
master[(master['regla'] == 'M') & (master['id_viaje'].isna())]

Empty DataFrame
Columns: [id_fila_og, year, oficina_regional, lugar_origen, lugar_destino, total_migrantes_traslado, nacionalidad, hombres, mujeres, niñas, niños, regla, id_viaje]
Index: []

In [184]:
print(len(master))  # Nuevo total de filas

13730

In [185]:
# Reseatamos el index
master = master.reset_index(drop=True)

### Regla 2:

In [186]:
# Rellenar id_viaje con ffill
mask_dos = master['regla'] == 'Dos'
master.loc[mask_dos, 'id_viaje'] = master.loc[mask_dos, 'id_viaje'].ffill()

In [187]:
# Checar que todo se llenó
master.loc[mask_dos, ['id_fila_og', 'regla', 'id_viaje']]
master.loc[mask_dos, 'id_viaje'].isna().sum()

np.int64(0)

In [188]:
# Reglas para agregar las filas: suma (columnas demográficas), concatenar (nacionalidad), 'first' para lo demás
agg_dict = {}
for col in master.columns:
    if col == 'nacionalidad':
        agg_dict[col] = lambda x: ', '.join(x.dropna().astype(str))
    elif col in ['hombres', 'mujeres', 'niñas', 'niños']:
        agg_dict[col] = 'sum'
    elif col == 'id_viaje':
        continue  # clave para agregar todo
    else:
        agg_dict[col] = 'first'  # id_fila_og y demás columnas se quedan con su valor en la primera fila de id_viaje

agg_dos = master.loc[mask_dos].groupby('id_viaje', as_index=False).agg(agg_dict)

# Reemplazamos nuestras filas con regla 2 originales con las nuevas
master = pd.concat([master[~mask_dos], agg_dos], ignore_index=True)

In [189]:
# Verificamos manualmente que todo parece bien
with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.max_colwidth', None):
    display(
        master.loc[
            master['regla'] == 'Dos',
            ['id_fila_og', 'id_viaje', 'lugar_origen', 'lugar_destino', 'total_migrantes_traslado', 
             'nacionalidad', 'hombres', 'mujeres', 'niñas', 'niños']
        ]
    )

,id_fila_og,id_viaje,lugar_origen,lugar_destino,total_migrantes_traslado,nacionalidad,hombres,mujeres,niñas,niños
10915,1009,981.0,COMITAN,"SIGLO XXI, TAPACHULA",1669.0,"GUATEMALA , HONDURAS , EL SALVADOR , NICARAGUA",1208,360.0,42.0,59.0
10916,1013,982.0,COMITAN,"TECUN UMAN, GTM",2660.0,GUATEMALA,1850,750.0,25.0,35.0
10917,1014,983.0,COMITAN,"LA MESILLA, GTM",82.0,GUATEMALA,55,17.0,4.0,6.0
10918,1015,984.0,COMITAN,"TUXTLA GUTIERREZ, CHIS",20.0,GUATEMALA,12,4.0,2.0,2.0
10919,1016,985.0,"TUXTLA GUTIERREZ, CHIAPAS",TECUN UMAN,4291.0,GUATEMALA,2100,887.0,573.0,731.0
10920,1017,986.0,"TUXTLA GUTIERREZ, CHIAPAS",EL CARMEN,472.0,GUATEMALA,229,79.0,65.0,99.0
10921,1018,987.0,"TUXTLA GUTIERREZ, CHIAPAS",ESTACION MIGRATORIA ACAYUCAN,1.0,COSTARRICENSE,0,0.0,1.0,0.0
10922,1019,988.0,"TUXTLA GUTIERREZ, CHIAPAS",ESTACION MIGRATORIA ACAYUCAN,3.0,GUATEMALTECA,0,0.0,3.0,0.0
10923,1020,989.0,"TUXTLA GUTIERREZ, CHIAPAS",ESTACION MIGRATORIA ACAYUCAN,32.0,HONDUREÑA,5,8.0,8.0,11.0
10924,1021,990.0,"TUXTLA GUTIERREZ, CHIAPAS",ESTACION MIGRATORIA ACAYUCAN,26.0,INDIA,26,0.0,0.0,0.0
10925,1022,991.0,"TUXTLA GUTIERREZ, CHIAPAS",ESTACION MIGRATORIA ACAYUCAN,6.0,NICARAGUENSE,3,2.0,1.0,0.0
10926,1023,992.0,"TUXTLA GUTIERREZ, CHIAPAS",ESTACION MIGRATORIA ACAYUCAN,16.0,SALVADOREÑA,6,4.0,5.0,1.0
10927,1024,993.0,"TUXTLA GUTIERREZ, CHIAPAS",ESTACION MIGRATORIA TAPACHULA,5.0,BANGLADESH,5,0.0,0.0,0.0
10928,1025,994.0,"TUXTLA GUTIERREZ, CHIAPAS",ESTACION MIGRATORIA TAPACHULA,17.0,CAMERUN,14,3.0,0.0,0.0
10929,1026,995.0,"TUXTLA GUTIERREZ, CHIAPAS",ESTACION MIGRATORIA TAPACHULA,2.0,COLOMBIANA,2,0.0,0.0,0.0
10930,1027,996.0,"TUXTLA GUTIERREZ, CHIAPAS",ESTACION MIGRATORIA TAPACHULA,4.0,CUBANA,3,1.0,0.0,0.0
10931,1028,997.0,"TUXTLA GUTIERREZ, CHIAPAS",ESTACION MIGRATORIA TAPACHULA,1128.0,GUATEMALTECA,296,129.0,206.0,497.0
10932,1029,998.0,"TUXTLA GUTIERREZ, CHIAPAS",ESTACION MIGRATORIA TAPACHULA,3011.0,HONDUREÑA,1196,656.0,498.0,661.0
10933,1030,999.0,"TUXTLA GUTIERREZ, CHIAPAS",ESTACION MIGRATORIA TAPACHULA,1567.0,SALVADOREÑA,628,388.0,257.0,294.0
10934,1031,1000.0,"TUXTLA GUTIERREZ, CHIAPAS",ESTACION MIGRATORIA TAPACHULA,147.0,NICARAGUENSE,87,31.0,12.0,17.0
10935,1032,1001.0,"TUXTLA GUTIERREZ, CHIAPAS",ESTACION MIGRATORIA TAPACHULA,4.0,ECUATORIANA,2,1.0,0.0,1.0
10936,1657,1624.0,MÉRIDA,TUXTLA GUTIERREZ,25.0,19 GUATEMALTECOS Y 6 HONDUREÑOS,10,12.0,2.0,1.0
10937,1690,1652.0,COMITAN,"SIGLO XXI, TAPACHULA",526.0,"GUATEMALA , HONDURAS , EL SALVADOR , NICARAGUA, CAMERUN",357,122.0,21.0,26.0
10938,1695,1653.0,COMITAN,"TECUN UMAN, GTM",605.0,GUATEMALA,480,95.0,17.0,3.0
10939,1696,1654.0,COMITAN,"LA MESILLA, GTM",42.0,GUATEMALA,28,8.0,2.0,4.0
10940,1697,1655.0,COMITAN,"TUXTLA GUTIERREZ, CHIS",30.0,"GUATEMALA , EL SALVADOR",18,8.0,1.0,3.0
10941,1699,1656.0,COMITAN,EL CARMEN GUATEMALA,84.0,GUATEMALA,55,15.0,6.0,8.0
10942,1700,1657.0,COMITAN,"ACAYUCAN, VER",11.0,EL SALVADOR,7,4.0,0.0,0.0
10943,1701,1658.0,COMITAN,"IZTAPALAPA, CD. MEXICO",62.0,HONDURAS,35,19.0,4.0,4.0
10944,1702,1659.0,COMITAN,"VILLAHERMOSA, TAB",3.0,HONDURAS,2,1.0,0.0,0.0
10945,1703,1660.0,TUXTLA GUTIERREZ,TECUN UMAN,1659.0,GUATEMALA,1346,235.0,42.0,36.0
10946,1704,1661.0,TUXTLA GUTIERREZ,EL CARMEN,152.0,GUATEMALA,122,21.0,2.0,7.0
10947,1705,1662.0,TUXTLA GUTIERREZ,"SIGLO XXI, TAPACHULA",1283.0,GUATEMALA,696,107.0,145.0,335.0
10948,1706,1663.0,TUXTLA GUTIERREZ,"SIGLO XXI, TAPACHULA",718.0,HONDURAS,452,100.0,61.0,105.0
10949,1707,1664.0,TUXTLA GUTIERREZ,"SIGLO XXI, TAPACHULA",62.0,NICARAGUENSE,42,13.0,4.0,3.0
10950,1708,1665.0,TUXTLA GUTIERREZ,"SIGLO XXI, TAPACHULA",330.0,SALVADOREÑA,231,56.0,18.0,25.0
10951,1709,1666.0,TUXTLA GUTIERREZ,ESTACIÓN MIGRATORIA DE ACAYUCAN,137.0,SALVADOREÑA,99,24.0,8.0,6.0
10952,1710,1667.0,TUXTLA GUTIERREZ,ESTACIÓN MIGRATORIA DE IZTAPALAPA,157.0,HONDUREÑA,108,27.0,5.0,17.0
10953,1711,1668.0,TUXTLA GUTIERREZ,ESTACIÓN MIGRATORIA DE IZTAPALAPA,1.0,SALVADOREÑA,0,1.0,0.0,0.0
10954,2708,2665.0,MÉRIDA,TAPACHULA,22.0,22 GUATEMALTECOS,4,18.0,0.0,0.0
10955,2753,2705.0,CD. CUAUHTEMOC,"TECUN UMAN, GUATEMALA",533,GUATEMALTECA,187,174.0,83.0,89.0
10956,2754,2706.0,COMITAN,"SIGLO XXI, TAPACHULA",848,"GUATEMALA , HONDURAS , EL SALVADOR , COLOMBIA",580,174.0,38.0,56.0
10957,2758,2707.0,COMITAN,"TECUN UMAN, GTM",725,GUATEMALA,650,55.0,8.0,12.0
10958,2759,2708.0,COMITAN,"TUXTLA GUTIERREZ, CHIS",86,"GUATEMALA , HONDURAS",70,10.0,2.0,4.0
10959,2761,2709.0,COMITAN,"TUXTLA GUTIERREZ, CHIS",15,HONDURAS,9,3.0,1.0,2.0
10960,2762,2710.0,COMITAN,"IZTAPALAPA, CD. MEXICO",2,HONDURAS,2,0.0,0.0,0.0
10961,2763,2711.0,COMITAN,"IZTAPALAPA, CD. MEXICO",1,PERU,1,0.0,0.0,0.0
10962,2764,2712.0,COMITAN,"VILLAHERMOSA, TAB",5,GUATEMALA,3,2.0,0.0,0.0
10963,2765,2713.0,COMITAN,"VILLAHERMOSA, TAB",19,HONDURAS,11,4.0,3.0,1.0
10964,4658,4585.0,COMITAN,"SIGLO XXI, TAPACHULA",328,"GUATEMALA , HONDURAS , EL SALVADOR , NICARAGUA, CUBA",192,94.0,26.0,16.0
10965,4663,4586.0,COMITAN,"TECUN UMAN, GTM",624,GUATEMALA,479,89.0,22.0,34.0
10966,4664,4587.0,COMITAN,ESTACION MIGRATORIA CUPAPE,18,HONDURAS,14,4.0,0.0,0.0
10967,4665,4588.0,COMITAN,CAITF HUIXTLA,11,"GUATEMALA , EL SALVADOR",10,1.0,0.0,0.0
10968,4667,4589.0,COMITAN,"VILLAHERMOSA, TAB",2,CUBA,2,0.0,0.0,0.0
10969,5462,5306.0,NUEVO LEON,VILLAHERMOSA,66,"COLOMBIANA, DOMINICANA, ECUATORIANA, INDIA, VENEZOLANA",60,6.0,0.0,0.0
10970,5467,5307.0,NUEVO LEON,VILLAHERMOSA,80,"COLOMBIANA, CUBANA, DOMINICANA, ECUATORIANA, HAITIANA, JAMAIQUINA, NICARAGUENSE , PERUANA, SALVADOREÑA, VENEZOLANA",51,29.0,0.0,0.0
10971,5477,5308.0,NUEVO LEON,SAN LUIS POSTOSI,40,CUBANA,25,15.0,0.0,0.0
10972,5478,5309.0,NUEVO LEON,AGUASCALIENTES,40,CUBANA,29,11.0,0.0,0.0
10973,5479,5310.0,NUEVO LEÓN,AGUASCALIENTES,14,"BRASILEÑA, COLOMBIANA, NICARAGÜENSE , VENEZOLANA",13,1.0,0.0,0.0
10974,5483,5311.0,NUEVO LEON,VILLAHERMOSA,24,"DOMINICANA, HAITIANA, NICARAGUENSE , PERUANA, SALVADOREÑA, VENEZOLANA",18,6.0,0.0,0.0
10975,5489,5312.0,NUEVO LEÓN,IZTAPALAPA,5,CUBANA,4,1.0,0.0,0.0
10976,5490,5313.0,NUEVO LEÓN,VILLAHERMOSA,80,"COLOMBIANA, DOMINICANA, ECUATORIANA, HAITIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",62,18.0,0.0,0.0
10977,5497,5314.0,NUEVO LEÓN,VILLAHERMOSA,80,"COLOMBIANA, CUBANA, DOMINICANA, ECUATORIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",57,23.0,0.0,0.0
10978,5504,5315.0,NUEVO LEON,VILLAHERMOSA,80,"COLOMBIANA, CUBANA, DOMINICANA, ECUATORIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",61,18.0,0.0,0.0
10979,5511,5316.0,NUEVO LEÓN,VILLAHERMOSA,119,"COLOMBIANA, DOMINICANA, ECUATORIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",89,30.0,0.0,0.0
10980,5517,5317.0,NUEVO LEON,VILLAHERMOSA,80,"COLOMBIANA, DOMINICANA, PERUANA, SALVADOREÑA, VENEZOLANA",61,19.0,0.0,0.0
10981,5522,5318.0,NUEVO LEON,IZTAPALAPA,40,"CUBANA, NICARAGUENSE",29,11.0,0.0,0.0
10982,5524,5319.0,NUEVO LEON,VILLAHERMOSA,159,"COLOMBIANA, CUBANA, DOMINICANA, ECUATORIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",126,33.0,0.0,0.0
10983,5531,5320.0,NUEVO LEON,IZTAPALAPA,23,GUATEMALTECA,18,5.0,0.0,0.0
10984,5532,5321.0,NUEVO LEON,VILLAHERMOSA,120,"COLOMBIANA, ECUATORIANA, FRANCESA, HAITIANA, PERUANA, DOMINICANA, SALVADOREÑA, SENEGALESA, VENEZOLANA",95,25.0,0.0,0.0
10985,5541,5322.0,NUEVO LEON,IZTAPALAPA,69,NICARAGUENSE,49,20.0,0.0,0.0
10986,5542,5323.0,NUEVO LEON,VILLAHERMOSA,40,"CUBANA, NICARAGUENSE",25,15.0,0.0,0.0
10987,5544,5324.0,NUEVO LEON,VILLAHERMOSA,57,"COLOMBIANA, DOMINICANA, ECUATORIANA, INDIA, PERUANA, SALVADOREÑA, VENEZOLANA, VIETNAMITA",49,8.0,0.0,0.0
10988,5552,5325.0,NUEVO LEON,VILLAHERMOSA,77,"CHILENA, COLOMBIANA, CUBANA, DOMINICANA, ECUATORIANA, HAITIANA, NICARAGUENSE , PANAMEÑA, SALVADOREÑA, VENEZOLANA",52,25.0,0.0,0.0
10989,5562,5326.0,NUEVO LEON,HERMOSILLO,40,GUATEMALTECA,33,7.0,0.0,0.0
10990,5563,5327.0,NUEVO LEON,VILLAHERMOSA,35,"DOMINICANA, ECUATORIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",29,6.0,0.0,0.0
10991,5568,5328.0,NUEVO LEON,VILLAHERMOSA,40,VENEZOLANA,40,0.0,0.0,0.0
10992,5569,5329.0,NUEVO LEON,VILLAHERMOSA,78,"COLOMBIANA, CUBANA, DOMINICANA, ECUATORIANA, GEORGIANA, HONDUREÑA, JAMAIQUINA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",55,23.0,0.0,0.0
10993,5579,5330.0,NUEVO LEON,VILLAHERMOSA,71,"CUBANA, ECUATORIANA, HAITIANA, HONDUREÑA, MARROQUI, NICARAGUENSE , PANAMEÑA, SALVADOREÑA, VENEZOLANA",50,21.0,0.0,0.0
10994,5588,5331.0,NUEVO LEON,TECUN UMAN,50,GUATEMALTECA,36,14.0,0.0,0.0
10995,5589,5332.0,NUEVO LEON,VILLAHERMOSA,41,"COLOMBIANA, CUBANA, ECUATORIANA, GEORGIANA, HONDUREÑA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",36,5.0,0.0,0.0
10996,5597,5333.0,NUEVO LEON,VILLAHERMOSA,55,"COLOMBIANA, CUBANA, DOMINICANA, ECUATORIANA, ERITREA, HAITIANA, INDIA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",45,10.0,0.0,0.0
10997,5607,5334.0,NUEVO LEON,IZTAPALAPA,150,"GUATEMALTECA , HONDUREÑA",112,38.0,0.0,0.0
10998,5609,5335.0,NUEVO LEON,VILLAHERMOSA,53,"COLOMBIANA, CUBANA, ECUATORIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",40,13.0,0.0,0.0
10999,5615,5336.0,NUEVO LEON,VILLAHERMOSA,39,"CUBANA, NICARAGUENSE , SALVADOREÑA",21,18.0,0.0,0.0
11000,5618,5337.0,NUEVO LEON,VILLAHERMOSA,53,"COLOMBIANA, DOMINICANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",45,8.0,0.0,0.0
11001,5623,5338.0,NUEVO LEON,TECUN UMAN,35,GUATEMALTECA,29,6.0,0.0,0.0
11002,5624,5339.0,NUEVO LEON,TAPACHULA,27,SALVADOREÑA,17,10.0,0.0,0.0
11003,5625,5340.0,NUEVO LEON,VILLAHERMOSA,115,"COLOMBIANA, DOMINICANA, ECUATORIANA, GEORGIANA, NICARAGUENSE , PANAMEÑA, VENEZOLANA",85,30.0,0.0,0.0
11004,5632,5341.0,NUEVO LEON,QUERETARO,12,CUBANA,8,4.0,0.0,0.0
11005,5633,5342.0,NUEVO LEON,REYNOSA,14,HONDUREÑA,12,2.0,0.0,0.0
11006,5634,5343.0,NUEVO LEON,VILLAHERMOSA,32,"BRASILEÑA, COLOMBIANA, CUBANA, ECUATORIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",29,3.0,0.0,0.0
11007,5641,5344.0,NUEVO LEON,VILLAHERMOSA,72,"COLOMBIANA, CUBANA, DOMINICANA, HAITIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",54,18.0,0.0,0.0
11008,5648,5345.0,NUEVO LEON,VILLAHERMOSA,35,"COLOMBIANA, CUBANA, ECUATORIANA, HAITIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",29,6.0,0.0,0.0
11009,5655,5346.0,NUEVO LEON,VILLAHERMOSA,37,NICARAGUENSE,31,6.0,0.0,0.0
11010,5656,5347.0,NUEVO LEON,VILLAHERMOSA,56,"COLOMBIANA, CUBANA, DOMINICANA, ECUATORIANA, SALVADOREÑA, VENEZOLANA",50,6.0,0.0,0.0
11011,5662,5348.0,NUEVO LEON,VILLAHERMOSA,40,"COLOMBIANA, ECUATORIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",30,10.0,0.0,0.0
11012,5667,5349.0,NUEVO LEON,VILLAHERMOSA,78,"ARGENTINA, COLOMBIANA, CUBANA, DOMINICANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",60,18.0,0.0,0.0
11013,5674,5350.0,NUEVO LEON,VILLAHERMOSA,20,"CHINA , CUBANA, DOMINICANA, NICARAGUENSE , PALESTINA, SALVADOREÑA",13,7.0,0.0,0.0
11014,5680,5351.0,NUEVO LEON,VILLAHERMOSA,76,"ARGENTINA, COLOMBIANA, CUBANA, ECUATORIANA, NICARAGUENSE , PERUANA, SALVADOREÑA, VENEZOLANA",53,23.0,0.0,0.0
11015,5688,5352.0,NUEVO LEON,TAPACHULA,65,"GUATEMALTECA , HONDUREÑA",58,7.0,0.0,0.0
11016,5690,5353.0,NUEVO LEON,VILLAHERMOSA,42,"COLOMBIANA, CUBANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",36,6.0,0.0,0.0
11017,5695,5354.0,NUEVO LEON,VILLAHERMOSA,50,"CUBANA, HAITIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",39,11.0,0.0,0.0
11018,5700,5355.0,NUEVO LEON,VILLAHERMOSA,65,"COLOMBIANA, CUBANA, DOMINICANA, ECUATORIANA, NICARAGUENSE , PERUANA, SALVADOREÑA, SRILANKA, VENEZOLANA",43,22.0,0.0,0.0
11019,5709,5356.0,NUEVO LEON,VILLAHERMOSA,68,"COLOMBIANA, CUBANA, ECUATORIANA, NICARAGUENSE , PERUANA, SALVADOREÑA, SRILANKA, VENEZOLANA",54,14.0,0.0,0.0
11020,5717,5357.0,NUEVO LEON,VILLAHERMOSA,73,"GUATEMALTECA , HONDUREÑA",57,16.0,0.0,0.0
11021,5719,5358.0,NUEVO LEON,VILLAHERMOSA,83,"COLOMBIANA, DOMINICANA, INDIA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",67,16.0,0.0,0.0
11022,5725,5359.0,NUEVO LEON,VILLAHERMOSA,37,"COLOMBIANA, CUBANA, DOMINICANA, ECUATORIANA, GHANESA , HAITIANA, NICARAGUENSE , PANAMEÑA, SALVADOREÑA, SENEGALESA, VENEZOLANA",28,9.0,0.0,0.0
11023,5736,5360.0,NUEVO LEON,VILLAHERMOSA,79,"COLOMBIANA, DOMINICANA, ECUATORIANA, GUATEMALTECA , LIBERIANA, NICARAGUENSE , PERUANA, SALVADOREÑA, VENEZOLANA",63,16.0,0.0,0.0
11024,5745,5361.0,NUEVO LEON,VILLAHERMOSA,23,"CHINA , COLOMBIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",19,4.0,0.0,0.0
11025,5750,5362.0,NUEVO LEON,VILLAHERMOSA,100,"COLOMBIANA, CUBANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",76,24.0,0.0,0.0
11026,5755,5363.0,NUEVO LEON,VILLAHERMOSA,68,"COLOMBIANA, DOMINICANA, HAITIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",43,25.0,0.0,0.0
11027,5761,5364.0,NUEVO LEON,VILLAHERMOSA,88,"COLOMBIANA, CUBANA, HONDUREÑA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",63,25.0,0.0,0.0
11028,5767,5365.0,NUEVO LEON,VILLAHERMOSA,34,"CUBANA, DOMINICANA, ECUATORIANA, NICARAGUENSE , PERUANA, SALVADOREÑA, VENEZOLANA",27,7.0,0.0,0.0
11029,5774,5366.0,NUEVO LEON,VILLAHERMOSA,83,"COLOMBIANA, CUBANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",49,34.0,0.0,0.0
11030,5779,5367.0,NUEVO LEON,VILLAHERMOSA,62,"CHINA , COLOMBIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",46,16.0,0.0,0.0
11031,5784,5368.0,NUEVO LEON,VILLAHERMOSA,76,"COLOMBIANA, GUATEMALTECA , HAITIANA, NICARAGUENSE , SALVADOREÑA",59,17.0,0.0,0.0
11032,5789,5369.0,NUEVO LEON,VILLAHERMOSA,129,"COLOMBIANA, CUBANA, DOMINICANA, NICARAGUENSE , PERUANA, SALVADOREÑA",97,32.0,0.0,0.0
11033,5795,5370.0,NUEVO LEON,VILLAHERMOSA,86,"ARGENTINA, COLOMBIANA, COSTARRICENSE , GUATEMALTECA , GUYANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",59,27.0,0.0,0.0
11034,5803,5371.0,NUEVO LEON,VILLAHERMOSA,27,"COLOMBIANA, DOMINICANA, ECUATORIANA, NICARAGUENSE , SALVADOREÑA",26,1.0,0.0,0.0
11035,5808,5372.0,NUEVO LEON,VILLAHERMOSA,137,"COLOMBIANA, CUBANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",98,39.0,0.0,0.0
11036,5813,5373.0,NUEVO LEON,VILLAHERMOSA,43,"COLOMBIANA, CUBANA, DOMINICANA, ECUATORIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",32,11.0,0.0,0.0
11037,5820,5374.0,NUEVO LEON,IZTAPALAPA,40,GUATEMALTECA,38,2.0,0.0,0.0
11038,5821,5375.0,NUEVO LEON,VILLAHERMOSA,59,"CHINA , COLOMBIANA, CUBANA, ECUATORIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",39,20.0,0.0,0.0
11039,5828,5376.0,NUEVO LEON,ZACATECAS,31,HONDUREÑA,29,2.0,0.0,0.0
11040,5829,5377.0,NUEVO LEON,VILLAHERMOSA,132,"CUBANA, ECUATORIANA, GUATEMALTECA , NICARAGUENSE , SALVADOREÑA",101,31.0,0.0,0.0
11041,5834,5378.0,NUEVO LEON,VILLAHERMOSA,92,"COLOMBIANA, CUBANA, NEPALI, NICARAGUENSE , SALVADOREÑA",59,33.0,0.0,0.0
11042,5839,5379.0,NUEVO LEON,VILLAHERMOSA,67,"CUBANA, DOMINICANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",48,19.0,0.0,0.0
11043,5844,5380.0,NUEVO LEON,VILLAHERMOSA,122,"COLOMBIANA, CUBANA, DOMINICANA, ECUATORIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",86,36.0,0.0,0.0
11044,5851,5381.0,NUEVO LEON,VILLAHERMOSA,41,"COLOMBIANA, COSTARRICENSE , CUBANA, ECUATORIANA, HAITIANA, NICARAGUENSE , PERUANA, SALVADOREÑA, VENEZOLANA",29,12.0,0.0,0.0
11045,5860,5382.0,NUEVO LEON,VILLAHERMOSA,50,"CUBANA, DOMINICANA, ECUATORIANA, NICARAGUENSE , SALVADOREÑA",32,18.0,0.0,0.0
11046,5865,5383.0,NUEVO LEON,VILLAHERMOSA,39,CUBANA,26,13.0,0.0,0.0
11047,5866,5384.0,NUEVO LEON,VILLAHERMOSA,28,"ARGENTINA, COLOMBIANA, CUBANA, DOMINICANA, ECUATORIANA, NICARAGUENSE , SALVADOREÑA",20,8.0,0.0,0.0
11048,5873,5385.0,NUEVO LEON,TECUN UMAN,50,GUATEMALTECA,42,8.0,0.0,0.0
11049,5874,5386.0,NUEVO LEON,VILLAHERMOSA,35,"ARGENTINA, BANGLADESH, COLOMBIANA, CUBANA, DOMINICANA, INDIA, NICARAGUENSE , PERUANA, SALVADOREÑA, VENEZOLANA",29,6.0,0.0,0.0
11050,5884,5387.0,NUEVO LEON,VILLAHERMOSA,110,"COLOMBIANA, CUBANA, ECUATORIANA, NICARAGUENSE , SALVADOREÑA",80,30.0,0.0,0.0
11051,5889,5388.0,NUEVO LEON,ZACATECAS,77,CUBANA,48,29.0,0.0,0.0
11052,5890,5389.0,NUEVO LEON,TECUN UMAN,71,GUATEMALTECA,56,15.0,0.0,0.0
11053,5891,5390.0,NUEVO LEON,VILLAHERMOSA,144,"BELICEÑA, COLOMBIANA, CUBANA, DOMINICANA, ECUATORIANA, HAITIANA, HONDUREÑA, NICARAGUENSE , PERUANA, SALVADOREÑA, TURCA",116,28.0,0.0,0.0
11054,5902,5391.0,NUEVO LEON,IZTAPALAPA,22,NICARAGUENSE,22,0.0,0.0,0.0
11055,5903,5392.0,NUEVO LEON,VILLAHERMOSA,19,"DOMINICANA, SALVADOREÑA",14,5.0,0.0,0.0
11056,5905,5393.0,NUEVO LEON,TAPACHULA,81,"ARGENTINA, BRASILEÑA, COLOMBIANA, HAITIANA, NICARAGUENSE , PERUANA, RUMANA, SALVADOREÑA, TURCA, UGANDESA, VENEZOLANA",66,15.0,0.0,0.0
11057,5916,5394.0,NUEVO LEON,TAPACHULA,43,HONDUREÑA,38,5.0,0.0,0.0
11058,5917,5395.0,NUEVO LEON,ZACATECAS,28,CUBANA,13,15.0,0.0,0.0
11059,5918,5396.0,NUEVO LEON,VILLAHERMOSA,80,"COLOMBIANA, CUBANA, HAITIANA, NICARAGUENSE , SALVADOREÑA",46,34.0,0.0,0.0
11060,5923,5397.0,NUEVO LEON,VILLAHERMOSA,88,"BOLIVIANA, CEILANDES, COLOMBIANA, CUBANA, ECUATORIANA, HAITIANA, NICARAGUENSE , PARAGUAYA, PERUANA, RUMANA, VENEZOLANA",57,31.0,0.0,0.0
11061,5934,5398.0,NUEVO LEON,VILLAHERMOSA,40,"BELICEÑA, CHILENA, COLOMBIANA, CUBANA, HAITIANA, NICARAGUENSE , PERUANA, VENEZOLANA",29,11.0,0.0,0.0
11062,5942,5399.0,NUEVO LEON,VILLAHERMOSA,40,"BOLIVIANA, COLOMBIANA, DOMINICANA, HAITIANA, NICARAGUENSE , PERUANA, SALVADOREÑA, UZBEKISTAN, VENEZOLANA",28,12.0,0.0,0.0
11063,5951,5400.0,NUEVO LEON,VILLAHERMOSA,116,"ARGENTINA, BRASILEÑA, COLOMBIANA, CUBANA, ECUATORIANA, HAITIANA, NICARAGUENSE , PERUANA, RUMANA, SALVADOREÑA, VENEZOLANA",76,40.0,0.0,0.0
11064,5962,5401.0,NUEVO LEON,VILLAHERMOSA,162,"ARGENTINA, BELICEÑA, BRASILEÑA, COLOMBIANA, COSTARRICENSE , CUBANA, ECUATORIANA, GEORGIANA, HAITIANA, NICARAGUENSE , PERUANA, SALVADOREÑA, VENEZOLANA",114,48.0,0.0,0.0
11065,5975,5402.0,NUEVO LEON,VILLAHERMOSA,124,"COLOMBIANA, CUBANA, GUINEANA, HAITIANA, NICARAGUENSE , PERUANA, SALVADOREÑA, UZBEKISTAN, VENEZOLANA",78,46.0,0.0,0.0
11066,5984,5403.0,NUEVO LEON,TAPACHULA,141,"BRASILEÑA, COLOMBIANA, CUBANA, SALVADOREÑA, HAITIANA, NICARAGUENSE , PERUANA, RUMANA, VENEZOLANA",94,47.0,0.0,0.0
11067,5993,5404.0,NUEVO LEON,VILLAHERMOSA,162,"COLOMBIANA, ECUATORIANA, HONDUREÑA, NICARAGUENSE , PERUANA, SALVADOREÑA, VENEZOLANA",83,79.0,0.0,0.0
11068,6000,5405.0,NUEVO LEON,TAPACHULA,172,"BOLIVIANA, CHILENA, COLOMBIANA, CUBANA, GUATEMALTECA , HAITIANA, HONDUREÑA, NICARAGUENSE , RUMANA, SALVADOREÑA, VENEZOLANA",97,75.0,0.0,0.0
11069,6011,5406.0,NUEVO LEON,TAMPICO,122,"CHILENA, COLOMBIANA, CUBANA, ECUATORIANA, NICARAGUENSE , VENEZOLANA",55,67.0,0.0,0.0
11070,6017,5407.0,NUEVO LEON,VILLAHERMOSA,158,"BOLIVIANA, BRASILEÑA, CHILENA, COLOMBIANA, CUBANA, HAITIANA, HONDUREÑA, NICARAGUENSE , PANAMEÑA, RUMANA, URUGUAYA, VENEZOLANA",99,59.0,0.0,0.0
11071,6029,5408.0,NUEVO LEON,VILLAHERMOSA,165,"COLOMBIANA, CUBANA, GUATEMALTECA , HONDUREÑA, PERUANA, RUMANA, SALVADOREÑA, VENEZOLANA",93,73.0,0.0,0.0
11072,6037,5409.0,NUEVO LEON,TAMPICO,40,"CHILENA, COLOMBIANA, VENEZOLANA",21,19.0,0.0,0.0
11073,8123,7487.0,COMITAN,"SIGLO XXI, TAPACHULA",20.0,"GUATEMALA , EL SALVADOR",17.0,2.0,1.0,0.0
11074,8125,7488.0,COMITAN,"TECUN UMAN, GTM",116.0,GUATEMALA,81.0,20.0,8.0,7.0
11075,8126,7489.0,COMITAN,ESTACION MIGRATORIA CUPAPE,19.0,HONDURAS,14.0,2.0,2.0,1.0
11076,9123,8474.0,NUEVO LEÓN,VILLAHERMOSA,64.0,"CUBANA , DOMINICANA, ECUATORIANA, HAITIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",39.0,25.0,0.0,0.0
11077,9130,8475.0,NUEVO LEÓN,VILLAHERMOSA,67.0,"COLOMBIANA, CUBANA , DOMINICANA, ECUATORIANA, HAITIANA, INDIA, SALVADOREÑA, VENEZOLANA",55.0,11.0,0.0,0.0
11078,9138,8476.0,NUEVO LEÓN,VILLAHERMOSA,80.0,"COLOMBIANA, CUBANA , DOMINICANA, ECUATORIANA, GUATEMALTECA, HONDUREÑA, NICARAGUENSE , SALVADOREÑA",60.0,20.0,0.0,0.0
11079,9146,8477.0,NUEVO LEÓN,VILLAHERMOSA,41.0,"CHINA, COLOMBIANA, CUBANA , DOMINICANA, ECUATORIANA, NICARAGUENSE , SALVADOREÑA, VENEZOLANA",32.0,9.0,0.0,0.0
11080,9154,8478.0,NUEVO LEÓN,VILLAHERMOSA,40.0,"BRASILEÑA, COLOMBIANA, DOMINICANA, ECUATORIANA, KAZAKISTAN, NICARAGUENSE , PERUANA, SALVADOREÑA, UZBEKA",28.0,12.0,0.0,0.0
11081,9163,8479.0,NUEVO LEÓN,VILLAHERMOSA,40.0,"BRASILEÑA, DOMINICANA, ECUATORIANA, HAITIANA, INDIA, NICARAGUENSE , SALVADOREÑA, UZBEKA, VENEZOLANA",38.0,2.0,0.0,0.0
11082,9172,8480.0,NUEVO LEÓN,REYNOSA,39.0,"GUATEMALTECA, HONDUREÑA",30.0,9.0,0.0,0.0
11083,9174,8481.0,NUEVO LEÓN,VILLAHERMOSA,63.0,"COLOMBIANA, DOMINICANA, ECUATORIANA, HAITIANA, INDIA, KAZAKISTAN, KIRGUISTAN , NICARAGUENSE , SALVADOREÑA, UZBEKA, VENEZOLANA",51.0,12.0,0.0,0.0
11084,9185,8482.0,NUEVO LEÓN,SAN LUIS POTOSI,22.0,CUBANA,19.0,3.0,0.0,0.0
11085,9186,8483.0,NUEVO LEÓN,TECUN UMAN,40.0,"ECUATORIANA, GUATEMALTECA, INDIA, VENEZOLANA",32.0,8.0,0.0,0.0

In [190]:
print(len(master)) # Nuevo total de filas

11400

### Regla 4

##### Para filas en este rango, quitamos todas las filas sin un valor de id_viaje; después, revisamos los valores númericos uno por uno (solo hay 2 filas) y multiplicamos los valores que tienen un puntito leído como decimal por 1000

In [191]:
# Quitamos todas las filas con regla 4 que no tienen un valor para id_viaje
master = master[~((master['regla'] == 'Cuatro') & (master['id_viaje'].isna()))]

In [192]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.max_colwidth', None):
    display(master.loc[master['regla'] == 'Cuatro'])

,id_fila_og,year,oficina_regional,lugar_origen,lugar_destino,total_migrantes_traslado,nacionalidad,hombres,mujeres,niñas,niños,regla,id_viaje
7058,7849,2023,Chiapas,TAPACHULA,TUXTLA GUTIERREZ,59695.0,"ECUADOR,SALVADOR,HONDURAS,HAITI,ERITREA,COLOMBIA ,CUBA,BRASIL,CHILE,INDIA,GAMBIA,CAMERUN,BURKINA FASO,ANGOLA,CONGO,GHANA,BOLIVIA,COSTA DE MARFIL,SUDAN,SIRIA,NEPAL,MAURITANIA,UZBEKISTAN,MOZAMBIQUE,ETHIOPIA,REPUBLICA DE TOGO,TCHAD,MARRUECOS,BANGLADESH,PAKISTAN,AFGHANISTAN,CHINA,SIERRA LEONA,URUGUAY,IRAQ,KIRGUISTAN,GEORGIA,RUSA,TURCA,KAZAJISTAN,YEMEN,ARGENTINA,COSTA,RICA,GUATEMALA,GUINEA,MALI,PANAMA,PERU,PARAGUAY,AZERBAIJAN,BENIN,BURUNDI,CABOVERDIANA,SENEGAL,SOMALIA,IVOIRE,LIBERIA,NICARAGUA,NIGERIA,REPUBLICA DOMINICANA,TAJIKISTAN,UGANDA,VENEZUELA,VIETNAM,DJBUTI,TANZANIA",32629.0,20141.0,3280.0,3645.0,Cuatro,7217.0
7061,7852,2023,Chiapas,SUCHIATE,TUXTLA GUTIERREZ,33569.0,"ECUADOR,SALVADOR,HONDURAS,HAITI,ERITREA,COLOMBIA ,CUBA,BRASIL,CHILE,INDIA,GAMBIA,CAMERUN,BURKINA FASO,ANGOLA,CONGO,GHANA,BOLIVIA,COSTA DE MARFIL,SUDAN,SIRIA,NEPAL,MAURITANIA,UZBEKISTAN,MOZAMBIQUE,ETHIOPIA,REPUBLICA DE TOGO,TCHAD,MARRUECOS,BANGLADESH,PAKISTAN,AFGHANISTAN,CHINA,SIERRA LEONA,URUGUAY,IRAQ,KIRGUISTAN,GEORGIA,RUSA,TURCA,KAZAJISTAN,YEMEN,ARGENTINA,COSTA,RICA,GUATEMALA,GUINEA,MALI,PANAMA,PERU,PARAGUAY,AZERBAIJAN,BENIN,BURUNDI,CABOVERDIANA,SENEGAL,SOMALIA,IVOIRE,LIBERIA,NICARAGUA,NIGERIA,REPUBLICA DOMINICANA,TAJIKISTAN,UGANDA,VENEZUELA,VIETNAM,DJBUTI,TANZANIA",17329.0,12583.0,1952.0,1705.0,Cuatro,7218.0

##### Pandas ya las leyó correctamente así que no hay que hacer nada :)

In [193]:
print(len(master)) # Nuevo total de filas

11396

# Aquí ya podemos empezar con una limpieza básica

### Primero, quitamos filas que tienen un valor de NaN para total_migrantes_traslado

In [194]:
master = master[master['total_migrantes_traslado'].notna()]
master['total_migrantes_traslado'].isna().sum()

np.int64(0)

In [195]:
print(len(master)) # Nuevo total de filas

11385

### Después, borramos filas que no tienen datos demográficos o que tienen un mensaje de insuficientes datos (string)

In [196]:
# Primero  cambiamos los strings posibles a integers; checamos cuáles valores no se pudieron convertir
cols_demograficas = ['hombres', 'mujeres', 'niñas', 'niños']

def try_convert_int(x):
    try:
        return int(float(x))  
    except (ValueError, TypeError):
        return None  

for col in cols_demograficas:
    converted = master[col].apply(try_convert_int)
    
    # Identificar strings
    mask_bad = converted.isna() & master[col].notna()
    
    # Mostrar id_fila_og y valor original de strings
    print(col)
    display(master.loc[mask_bad, ['id_fila_og', col]])
    
    # Reemplazar valores convertidos  
    master.loc[~mask_bad, col] = converted.loc[~mask_bad]

hombres

      id_fila_og                                            hombres
691          720  NO SE CUENTA CON  REGISTROS ELECTRONICOS ADMIN...
692          721  NO SE CUENTA CON  REGISTROS ELECTRONICOS ADMIN...
693          722  NO SE CUENTA CON  REGISTROS ELECTRONICOS ADMIN...
694          723  NO SE CUENTA CON  REGISTROS ELECTRONICOS ADMIN...
695          724  NO SE CUENTA CON  REGISTROS ELECTRONICOS ADMIN...
...          ...                                                ...
3432        3548  LA INFORMACION NO SE ENCUENTRA AL GRADO DE DET...
3433        3549  LA INFORMACION NO SE ENCUENTRA AL GRADO DE DET...
3434        3550  LA INFORMACION NO SE ENCUENTRA AL GRADO DE DET...
3435        3551  LA INFORMACION NO SE ENCUENTRA AL GRADO DE DET...
9808       12500  NO SE CUENTA CON LA INFORMACIÓN A GRADO DE DET...

[293 rows x 2 columns]

mujeres

      id_fila_og                                         mujeres
4876        5077  NO SE CUENTA CON EL DETALLE DE LA INFORMACIÓN

niñas

Empty DataFrame
Columns: [id_fila_og, niñas]
Index: []

niños

Empty DataFrame
Columns: [id_fila_og, niños]
Index: []

In [197]:
# Ya que todos los valores no convertibles son mensajes de insuficiencia de datos, los convertimos a NaN 
for col in cols_demograficas:
    master[col] = pd.to_numeric(master[col], errors='coerce')

In [198]:
# Cambiamos los NaNs a 0's y las filas con todo en 0 son eliminadas
master[cols_demograficas] = master[cols_demograficas].fillna(0)
master = master[~(master[cols_demograficas] == 0).all(axis=1)]

In [199]:
print(len(master)) # Nuevo total de filas

11025

### Ahora, limpiamos valores de string en total_migrantes_traslados

In [200]:
# Primero  cambiamos los strings posibles a integers; checamos cuáles valores no se pudieron convertir
def try_convert_int(x):
    try:
        return int(float(x))  
    except (ValueError, TypeError):
        return None 

converted = master['total_migrantes_traslado'].apply(try_convert_int)

mask_bad = converted.isna() & master['total_migrantes_traslado'].notna()

print(master.loc[mask_bad, ['id_fila_og', 'total_migrantes_traslado']].values.tolist())

master.loc[~mask_bad, 'total_migrantes_traslado'] = converted.loc[~mask_bad]

[[3046, '63 (no hay referencia sobre como se enviaron repartidas estas personas a San Luis Potosi e Iztapalapa)'], [3047, '63 (no hay referencia sobre como se enviaron repartidas estas personas a San Luis Potosi e Iztapalapa)']]

In [201]:
# En general, si una fila muestra dos destinos, solo usaremos el primero durante toda la limpieza. 
# Así que aquí, conservamos la primera fila (3046) con destino de San Luis Potosí y eliminamos la segunda fila (3047)

In [202]:
# Actualizamos la fila con id_fila_og 3046
master.loc[master['id_fila_og'] == 3046, 'total_migrantes_traslado'] = 63
master.loc[master['id_fila_og'] == 3046, 'lugar_destino'] = 'San Luis Potosí'

# Borramos la fila con id_fila_og 3047
master = master[master['id_fila_og'] != 3047]

In [203]:
print(len(master)) # Nuevo total de filas

11024

### Finalmente, quitamos filas con valores númericos para lugar_origen, lugar_destino y nacionalidad

In [204]:
# Checamos lugar_origen
def can_convert_int(x):
    try:
        int(float(x))
        return True
    except (ValueError, TypeError):
        return False

mask_convertible = master['lugar_origen'].apply(can_convert_int)

display(master.loc[mask_convertible, ['id_fila_og', 'lugar_origen']])

      id_fila_og lugar_origen
2672        2778          605
2673        2779           40
2674        2780           21

In [205]:
# Checamos lugar_destino
mask_convertible_destino = master['lugar_destino'].apply(can_convert_int)

display(master.loc[mask_convertible_destino, ['id_fila_og', 'lugar_destino']])

Empty DataFrame
Columns: [id_fila_og, lugar_destino]
Index: []

In [206]:
# Checamos nacionalidad
mask_convertible_nac = master['nacionalidad'].apply(can_convert_int)

display(master.loc[mask_convertible_nac, ['id_fila_og', 'nacionalidad']])

      id_fila_og nacionalidad
2672        2778          194
2673        2779           10
2674        2780            6

In [207]:
# Quitamos las filas que están mal
ids_to_delete = [2778, 2779, 2780]  

master = master[~master['id_fila_og'].isin(ids_to_delete)]

In [208]:
print(len(master)) # Nuevo total de filas

11021

# Chequeos finales antes de la limpieza más nítida

In [209]:
print(master.dtypes)

id_fila_og                    int64
year                          int64
oficina_regional             object
lugar_origen                 object
lugar_destino                object
total_migrantes_traslado     object
nacionalidad                 object
hombres                     float64
mujeres                     float64
niñas                       float64
niños                       float64
regla                        object
id_viaje                    float64
dtype: object

In [210]:
master = master.astype({
    'oficina_regional': str,
    'lugar_origen': str,
    'lugar_destino': str,
    'total_migrantes_traslado': int,
    'hombres': int,
    'mujeres': int,
    'niñas': int,
    'niños': int,
    'regla': str,
    'id_viaje': int,
})

In [211]:
master['total_migrantes_traslado'].sum()

np.int64(587058)

# Limpieza

##### Esta sección fue realizada en colaboración con @santiagonh

### Empezamos por asignar los nombres correctos de los municipios a las localidades de lugar_origen y lugar_destino

In [212]:
# Primero convertimos todo a minúscula
master.lugar_origen = master.lugar_origen.str.lower()
master.lugar_destino = master.lugar_destino.str.lower()
master.nacionalidad = master.nacionalidad.str.lower()

In [213]:
# Revisamos la lista de valores únicos de origen y destino
pd.unique(master[['lugar_origen', 'lugar_destino']].values.ravel())

array(['janos', 'chihuahua - iztapalapa', 'iztapalapa', 'pachuca',
       'ciudad de mexico', 'guadalajara ', 'em acayucan', 'edo. mex ',
       'iztapalapa ', 'edo. méx ', 'san pedro tapantepec',
       'tapachula, chiapas',
       'subdelegación local del inm en el estado de oaxaca',
       'estación migratoria \nsiglo xxi, en tapachula, chiapas.\n',
       'estacion migratoria acayucan, veracruz',
       'subdelegacion local del inm en la ventosa', 'e.p la ventosa',
       'frontera el carmen', 'chetumal',
       'aeropuerto internacional de chetumal, quintana roo',
       'san luis potosi', 'tapachula', 'acayucan', 'nuevo laredo',
       'acayucan, ver', 'cdmx', 'tampico', 'acayucan, veracruz',
       'zacatecas', 'iztapalapa, cdmx', 'aguascalientes', 'tijuana',
       'escarcega', 'em tenosique', 'em siglo xxi', 'em chetumal',
       'em cancun', 'campeche', 'comitan', 'siglo xxi, tapachula',
       'tecun uman, gtm', 'la mesilla, gtm', 'gracias a dios, gtm',
       'tuxtla gutierrez, chiapas', 'tecun uman',
       'estacion migratoria siglo xxi', 'e.m. tapachula',
       'piedras negras', 'laredo tamaulipas', 'pachuca, hidalgo',
       'em iztapalapa', 'huatulco', 'em tapachula', 'frontera del carmen',
       'oaxaca', 'ciudad tecun uman', 'guatemala', 'salinacruz, oax.',
       'acayucan, ver.', 'tapachula, chis.', 'tecun uman, guatemala',
       'chetumal, quintana roo', 'mazatlan', 'tenosique', 'reynosa',
       'iztalapa', 'cd. victoria', 'nuevo laredo ', 'apetatitlán, tlax',
       'acayucan, ver. ', 'iztapalapa, cdmx ', 'gudalupe, nuevo leon',
       ' veracruz, veracruz ', 'estacion migratoria de acayucan',
       'ciudad de mèxico', 'san luis potosì', 'ciudad del carmen',
       'chihuahua', 'chiapas-el carmen ', 'e.m. acayucan ', 'acaycuan',
       'gomez palacio durango', 'iztalapalapa mexico', 'zacatecas ',
       'tecun uman ', 'veracruz ', 'morelia', 'ciudad de méxico', 'tepic',
       'ep tapanatepec', 'e.p. huatulco', 'e.m. oaxaca', 'e.m. acayucan',
       'ayutla, san marcos, guatemala',
       'tapachula, chiapas // ayutla, san marcos, guatemala', 'tampico ',
       'saltillo', 'tapachula, chis', 'acayucan, veracrúz', 'tabasco',
       'juarez', 'e.m. puebla/e. m. queretaro ',
       'o.p. toluca/  o.p. aeropuerto int. cd mexico', 'o.p. toluca ',
       'villahermosa', 'monterrey', 'monterrey ', 'tuxtla gutierrez',
       'guadalajara', 'iztapalapa, ciudad de mexico', 'em  acayucan',
       'em tuxtla gutierrez', ' la ventosa', 'e.m. huatulco',
       'villahermosa, tabasco', 'comitan de dominguez', 'palenque',
       'nuevo leon', 'coahuila', 'oficinas administrativas reynosa',
       'aeropuerto lucio blanco \\ reynosa', 'veracruz', 'tuxtla',
       'tampico, tamaulipas', 'queretaro, qro', 'comitan, chis',
       'monterrey, nvo leon', 'hermosillo, son', 'villahermosa, tab',
       'tuxtla gutierrez, chis', 'honduras', 'san salvador', ' guatemala',
       'haiti (salida aerop. de tapachula, chis)',
       'estación mig. veracruz', 'aeropuerto de tuxtla gutierrez chis.',
       'aeropuerto de cdmx', 'aeropuerto de villahermosa',
       'cdmx iztapalapa', 'aeropuerto villahermosa', 'minatitlan',
       'hondureña', 'monterrey, nuevo leon', 'saltillo, coahuila',
       'san cristobal de las casas', 'e.m. siglo xxi ',
       'acayucan - tapachula', 'iztapalapa - tapachula',
       'aeropuerto internacional de ciudad juarez',
       'aeropuerto de saltillo, coahuila', 'cd juarez',
       'chiapas-el carmen/ e. m. tenosique',
       'chiapas-el carmen/ frontera talisman', 'o. p. toluca',
       'o. p. toluca/o. p. aeropuerto internacional ciudad de mexico',
       'e. m. tapachula', 'cdmx ', 'torreon', 'monclova', 'chiapas',
       'saltillo,coahuila', 'acayucan,  veracruz',
       'villahermosa, tabasco ', 'aeropuerto intl nuevo leon ',
       'guadalupe, nuevo leon ', 'monclova, coahuila',
       'gomez palacio dgo', 'monterrey nuevo leon ', 'ramos arizpe',
       'reynosa tamaulipas ', 'san miguel de allende', 'san luis potosí',
       'acapulco', 'villahermosa ', 'san luis potosi, slp',
       'estado de méxico', 'tapachula chiapas', 'tepótzotlan',
       'acayucán veracruz', 'ciudad ixtepec oaxaca ',
       'tapachula chiapas ', 'villa hermosa', 'em huatulco', 'la ventosa',
       'tuxtla, gtz. chis.', 'villahermosa, tab.', 'pais de origen',
       'puebla', 'villahermosa tabasco', 'acayucan ', 'omoa honduras',
       'huixtla chiapas ', 'tenosique tabasco', 'cancun, quintana roo',
       'tuxtla gutiérrez, chiapas', 'chiapa de corzo, chiapas',
       'tecum uman', 'san pedro sula honduras', 'coatzacoalcos',
       'el ceibo ', 'aeropuero de nuevo laredo', 'e.m. nuevo leon',
       'villahermosa, villahermosa, tabasco',
       'villahermosa, villahermosa, tabasco ', 'reynosa, tamaulipas',
       'villahermosa, villahermosa, tabasco, villahermosa, tabasco',
       'matamoros', 'guadalupe nuevo leon', 'tapachula, chis ',
       'villahermosa, tab. ', 'celaya, gto ', 'ixtepec, oax',
       'coatzacoalcos, ver', 'el ceibo, tab. ', 'ixtepec- tapachula',
       'san luis potosi ', 'cdmx- san luis potosi ',
       'oficina de canazalización nna acayucan ',
       'albergue hermanos en el camino, a.c. ixtepec, oaxaca', 'em villa',
       'mérida', 'san luis potosi, san luis potosi',
       'guadalupe, nuevo leon', 'leon, guanajuato', 'em villahermosa',
       'quetzaltenango', 'san pedro sula', 'villa hermosa tabasco',
       'suchiate', 'arriaga', 'cd. cuautemoc', 'cd. mexico',
       'frontera tecun uman. ',
       'centro de atencion para la niñez migrante de huixtla, chiapas',
       'e.m. siglo xxi',
       'estacion migratoria las agujas, iztapalapa, estado de mexico',
       'aeropuerto internacional de tapachula, chiapas',
       'tuxtla gutierrez, chiapas.', 'tuxtla gutierrez nna',
       'aeropuerto de monterrey', 'aeropuerto de hermosillo',
       'juarez - acayucan', 'aeropuerto de ciudad juarez', ' iztapalapa',
       'hermosillo', 'e.m. oaxaca ',
       'e.m. oaxaca/ e. p. san pedro tapanatepec ',
       'o. p. toluca/ o. p.  aeropuerto int. ciudad de mexico',
       'nuevo laredo, tamaulipas', 'aeropuerto int. monterrey',
       'aeropuerto int. cd. de mexico',
       'aeropuerto int. plan de guadalupe',
       'aeropuerto int, de monterrey',
       'awropuerto int. plan de guadalupe', 'tamaulipas', 'michoacan',
       'torreon, coahuila ', 'reynosa, tamaulipas ',
       'zacatecas, zacatecas', 'aeropuerto intl ramos arizpe, coahuila ',
       'monclova, coahuila ', 'aeropuerto inl reynosa, tamaulipas',
       'aeropuerto itnl ramos arizpe ', 'acayucan, veracruz ',
       'aeropuerto intl reynosa, tamaulipas', 'aeropuerto intl toluca',
       'morelia, michoacan ', 'gomez palacio, durango ',
       'aguascalientes ', 'queretaro, queretaro ', 'hidalgo, coahuila ',
       'pachuca, hidalgo ', 'mazatlan, sinaloa', 'acapulco, guerrero',
       'aeropuerto itnl nuevo leon ', 'puebla ', 'gomez palacio, dgo',
       '  ciudad de mexico', 'san miguel allende ', 'iztapala', 'chalco',
       'ixtapaluca', 'tlanepantla', 'oaxaca de juarez ', 'emhuatulco',
       'em tapachula ', 'e.p. la ventosa', 'e.m. acayucan, ver.',
       'e.m. villa hermosa', 'toluca', 'queretaro',
       'toluca, estado de mexico',
       'villahermosa, tabasco // minatitlan, veracruz', 'oaxaca, oaxaca',
       'tuxtla chico', 'monterrey,  nuevo león', 'cd. juarez, chihuahua',
       'puebla, puebla', ' tapachula, chiapas', 'huixtla',
       'omoa cortés honduras', 'belice', 'villehermosa',
       'aeropuerto monterrey nuevo leon',
       'aeropuerto internacional de monterrey nuevo leon',
       'cd de mexico-las agujas-villahermosa',
       'estacion migratoria de ciudad de mexico (las agujas)',
       'e.m. tapachula chiapas', 'villahermosa, tabasco, tabasco',
       'aeropuero de reynosa, tamaulipas', 'queretaro, queretaro',
       'cd de mexico', 'el salvador', 'tecun umán, gtm ',
       'coatzacoalcos, ver. ', 'apto, toluca ', 'omoa, honduras ',
       'oficina de canazalizacion nna acayucan', 'albergue coatzacoalcos',
       'omoa, honduras', 'tecún umán, guatemala', 'aerop. villahermosa',
       'guatemala, guatemala', 'aeropuerto tapachula', 'o.r. veracruz',
       'tecun umán, guatemala', 'aeropuerto de la ciudad de mexico, cdmx',
       'tecunuman, republica de guatemala', 'cdmx  ', 'echegaray',
       'aeropuerto internacional de tapachula', 'huehuetan',
       'estacion siglo xxi', 'san cristobal ', 'san cristobal',
       'caitf-huixtla ', 'tuxtla gutierrez, chiapas ',
       'san cristobal de las casa, chiapas ',
       'parque ecologico, tapachla, chiapas.', 'cd. cuauhtemoc',
       'caitf, trinitaria', 'janos, acayucan', 'ciudad juárez', 'janos ',
       'e.m. tapachula/ chiapas-el carmen ', 'e.m. villahermosa ',
       'e.m villahermosa ', 'e.m. oaxaca/ e.m. villahermosa ',
       'o.p aeropuerto internacional de la cuidad de mexico/ o.p toluca',
       'e. m. villahermosa, tabasco', 'guerrero', 'torreon coah.',
       'nuevo leon ', 'aguascalientes, aguascalientes',
       'torreon, coahuila', 'san miguel de allende, guanajuato ',
       'durango ', 'lazaro cardenas, michoacan ', 'izatapalap, cdmx',
       'acuña', 'gomez palacio, durango',
       'aeropuerto int. piedras negras', 'monterrey nl',
       'gómez palacio, dgo', 'guadalupe, zacatecas',
       'monterrey, nuevo león', 'viillahermosa, tabasco', 'leon',
       'irapuato ', 'celaya', 'salamanca ', 'guanajuato',
       'acayucan,veracruz', 'tuxtla gutierrez chiapas',
       'atlacomulco-maravatío', 'apaxco-huehuetoca', 'edo. méx.',
       'dif. toluca', 'dif. toluca una noche/ villahermosa tabasco',
       'iztapalapa una noche/ villahermosa tabasco', 'or. toluca',
       'iztapalapa, cd. de mexico', 'tapacula',
       'estancia provisionalsan agustin de la juntas', 'arriaga, chiapas',
       'estacion migratoria tapachula chiapas',
       'estación migratoria las agujas en iztapalapa, estado de méxico',
       'salina cruz, oax.', 'tapachula, \nchis',
       'jalapa del marquez, oax.', 'tonala chiapas ', 'arriaga chiapas ',
       'jalapa del marques, oax.', 'jalapa del marques oax.',
       'jalpa del marquez, oax.', 'salina cruz ', 'ciudad de mexico ',
       'la venta ', 'tecun-uman', 'ceibo, villahermosa', 'aifa',
       'conduccion a cdmx', 'villahermosa, tabasco // ciudad de mexico',
       'talisman, tuxtla chico, chiapas', 'el ceibo',
       'el ceibo, tenosique', 'e.m. villahermosa, tabasco',
       'punto de internacion terrestre el ceibo',
       'aeropuerto int. de villahermosa', 'san diego, california e.u.',
       'acayucan veracruz', 'cd de mexico las agujas',
       'aeropuerto internacional de monterrey n.l.', 'monterrey, nl',
       'tampico, tamps', 'reynosa, tamps', 'aeropuerto  de reynosa',
       'aeropuerto de reynosa', 'villahermosa, tab  ',
       'tapachula, chiapas.', 'villahermosa, tabasco.', 'tlaxcala',
       'albergue dif estatal mina',
       'albergue santa faustina  kowalska, a.c.',
       'albergue monseñor guillermo ranzahuer', 'nicaragua',
       'tapachula/ecuador', 'aeropuerto cdmx', 'tapachula chis',
       'oficina admitiva acy', 'albergue minatitlan',
       'san pedro sula, honduras',
       'aeropuerto internacional de ciudad de mexicio ',
       'estancia provisional\ntipo en tijuana', 'zatecas',
       'aeropuerto de tijuana', 'apto cd juarez', 'precos',
       'no se cuenta con la informacion', 'villa hermosa ',
       'e. m. tapachula, chiapas', 'saltillo ', 'monterrey, nuevo leon ',
       'zacatecas, zac', 'dif toluca ', 'villahermosa tabasco ',
       'tapachula ', 'aeropuerto internacional de morelia',
       'terminal de autobuses de morelia', 'san pedro tapanatepec',
       'huatulco, oaxaca', 'estancia provisional en villahermosa tabasco',
       'estancia provisional en tuxtla gutierrez chiapas',
       'berriozabal, chiapas', 'jalapa del marquez oaxaca',
       'tonala, chiapas', 'tonala, chis.', 'berriozabal, chis.',
       'arriaga, chis.', 'pijijiapan, chis.', 'tuxtla gutierrez, chis.',
       'jalapa del marquez', 'la ventosa, juchitan ', 'oaxaca de juarez',
       'puebla, pue.', 'cancún', 'escuinapa', 'guasave', 'ahome',
       'culiacan', 'omoa, cortes, honduras', 'apto reynosa',
       'guadalupe, n.l.', 'aeropuerto, tampico',
       'albergue del dif estatal en minatitlan',
       'albergue minatitlan, ver', 'omoa, hoduras', 'omoa, hondureña',
       'el carmen', 'estacion migratoria acayucan',
       'estacion migratoria tapachula', 'el carmen guatemala',
       'iztapalapa, cd. mexico', 'estación migratoria de acayucan',
       'estación migratoria de iztapalapa', 'estacion migratoria cupape',
       'caitf huixtla', 'san luis postosi ', 'nuevo león', 'queretaro ',
       'reynosa ', 'nuevo leon  ', 'estados unidos '], dtype=object)

In [214]:
corrections = {
    'cdmx': 'Cuauhtémoc, Ciudad de México',
    'janos': 'Janos, Chihuahua',
    'chihuahua - iztapalapa' : 'Chihuahua, Chihuahua',
    'iztapalapa' : 'Iztapalapa, Ciudad de México',
    'pachuca' : 'Pachuca de Soto, Hidalgo', 
    'ciudad de mexico': 'Iztapalapa, Ciudad de México', 
    'guadalajara ': 'Guadalajara, Jalisco', 
    'em acayucan': 'Acayucan, Veracruz', 
    'edo. mex ': 'Estado de México',
    'iztapalapa ': 'Iztapalapa, Ciudad de México', 
    'edo. méx ': 'Estado de México', 
    'san pedro tapantepec': 'San Pedro Tapanatepec, Oaxaca',
    'tapachula, chiapas': 'Tapachula, Chiapas',
    'estación migratoria \nsiglo xxi, en tapachula, chiapas.\n': 'Tapachula, Chiapas',
    'estacion migratoria acayucan, veracruz': 'Acayucan, Veracruz',
    'subdelegacion local del inm en la ventosa': 'Heroica Ciudad de Juchitán de Zaragoza, Oaxaca', 
    'e.p la ventosa': 'Heroica Ciudad de Juchitán de Zaragoza, Oaxaca',
    'frontera el carmen': 'Guatemala', 
    'chetumal': 'Othón P. Blanco, Quintana Roo',
    'aeropuerto internacional de chetumal, quintana roo': 'Othón P. Blanco, Quintana Roo',
    'san luis potosi': 'San Luis Potosí, San Luis Potosí', 
    'tapachula': 'Tapachula, Chiapas', 
    'acayucan': 'Acayucan, Veracruz', 
    'nuevo laredo': 'Nuevo Laredo, Tamaulipas',
    'acayucan, ver': 'Acayucan, Veracruz', 
    'cdmx': 'Cuauhtémoc, Ciudad de México', 
    'tampico': 'Tampico, Tamaulipas', 
    'acayucan, veracruz': 'Acayucan, Veracruz',
    'zacatecas': 'Zacatecas, Zacatecas', 
    'iztapalapa, cdmx': 'Iztapalapa, Ciudad de México', 
    'tijuana': 'Tijuana, Baja California',
    'escarcega': 'Escárcega, Campeche', 
    'em tenosique': 'Tenosique, Tabasco', 
    'em siglo xxi': 'Tapachula, Chiapas', 
    'em chetumal': 'Othón P. Blanco, Quintana Roo',
    'em cancun': 'Benito Juárez, Quintana Roo', 
    'campeche': 'Campeche, Campeche', 
    'comitan': 'Comitán de Domínguez, Chiapas', 
    'siglo xxi, tapachula': 'Tapachula, Chiapas',
    'tecun uman, gtm': 'Guatemala', 
    'la mesilla, gtm': 'Guatemala', 
    'gracias a dios, gtm': 'Guatemala',
    'tuxtla gutierrez, chiapas': 'Tuxtla Gutiérrez, Chiapas', 
    'tecun uman': 'Guatemala',
    'estacion migratoria siglo xxi': 'Tapachula, Chiapas', 
    'e.m. tapachula': 'Tapachula, Chiapas',
    'piedras negras': 'Piedras Negras, Coahuila', 
    'laredo tamaulipas': 'Nuevo Laredo, Tamaulipas', 
    'pachuca, hidalgo': 'Pachuca de Soto, Hidalgo',
    'guadalajara': 'Guadalajara, Jalisco', 
    'em iztapalapa': 'Iztapalapa, Ciudad de México', 
    'huatulco': 'Santa María Huatulco, Oaxaca', 
    'em tapachula': 'Tapachula, Chiapas',
    'frontera del carmen': 'Guatemala', 
    'oaxaca': 'Oaxaca de Juárez, Oaxaca', 
    'ciudad tecun uman': 'Guatemala', 
    'guatemala': 'Guatemala',
    'salinacruz, oax': 'Salina Cruz, Oaxaca', 
    'acayucan, ver.': 'Acayucan, Veracruz', 
    'tapachula, chis.': 'Tapachula, Chiapas',
    'tecun uman, guatemala': 'Guatemala', 
    'querétaro ': 'Querétaro, Querétaro', 
    'chetumal, quintana roo': 'Othón P. Blanco, Quintana Roo',
    'mazatlan': 'Mazatlán, Sinaloa', 
    'tenosique': 'Tenosique, Tabasco', 
    'reynosa': 'Reynosa, Tamaulipas', 
    'iztalapa': 'Iztapalapa, Ciudad de México', 
    'cd. victoria': 'Ciudad Victoria, Tamaulipas',
    'nuevo laredo ': 'Nuevo Laredo, Tamaulipas', 
    'apetatitlán, tlax': 'Apetatitlán de Antonio Carvajal, Tlaxcala', 
    'acayucan, ver. ': 'Acayucan, Veracruz',
    'iztapalapa, cdmx ': 'Iztapalapa, Ciudad de México', 
    'gudalupe, nuevo leon': 'Guadalupe, Nuevo León',
    ' veracruz, veracruz ': 'Veracruz, Veracruz', 
    'estacion migratoria de acayucan': 'Acayucan, Veracruz',
    'ciudad de mèxico': 'Iztapalapa, Ciudad de México', 
    'san luis potosì': 'San Luis Potosí, San Luis Potosí', 
    'ciudad del carmen': 'Carmen, Campeche',
    'tuxtla gutierrez, chis': 'Tuxtla Gutiérrez, Chiapas', 
    'el carmen': 'Pijijiapan, Chiapas',
    'estacion migratoria acayucan': 'Acayucan, Veracruz', 
    'estacion migratoria tapachula': 'Tapachula, Chiapas',
    'chiapas-el carmen ': 'Pijijiapan, Chiapas', 
    'e.m. acayucan ': 'Acayucan, Veracruz', 
    'acaycuan': 'Acayucan, Veracruz',
    'gomez palacio durango': 'Gómez Palacio, Durango', 
    'iztalapalapa mexico': 'Iztapalapa, Ciudad de México', 
    'zacatecas ': 'Zacatecas, Zacatecas',
    'tecun uman ': 'Guatemala', 
    'morelia': 'Morelia, Michoacán', 
    'ciudad de méxico': 'Iztapalapa, Ciudad de México', 
    'tepic': 'Tepic, Nayarit',
    'ep tapanatepec': 'San Pedro Tapanatepec, Oaxaca', 
    'salinacruz, oax.': 'Salina Cruz, Oaxaca', 
    'e.p. huatulco': 'Santa María Huatulco, Oaxaca',
    'e.m. acayucan': 'Acayucan, Veracruz', 
    'ayutla, san marcos, guatemala': 'Guatemala',
    'tapachula, chiapas // ayutla, san marcos, guatemala': 'Tapachula, Chiapas', 
    'tampico ': 'Tampico, Tamaulipas',
    'saltillo': 'Saltillo, Coahuila de Zaragoza', 
    'tapachula, chis': 'Tapachula, Chiapas', 
    'mérida': 'Mérida, Yucatán', 
    'tuxtla gutierrez': 'Tuxtla Gutiérrez, Chiapas',
    'acayucan, veracrúz': 'Acayucan, Veracruz', 
    'el carmen guatemala': 'Guatemala',
    'iztapalapa, cd. mexico': 'Iztapalapa, Ciudad de México', 
    'villahermosa, tab': 'Centro, Tabasco',
    'estación migratoria de acayucan': 'Acayucan, Veracruz',
    'estación migratoria de iztapalapa': 'Iztapalapa, Ciudad de México', 
    'monterrey': 'Monterrey, Nuevo León',
    'e.m. puebla/e. m. queretaro ': 'Puebla, Puebla',
    'o.p. toluca/  o.p. aeropuerto int. cd mexico': 'Toluca, México', 
    'o.p. toluca ': 'Toluca, México',
    'villahermosa': 'Centro, Tabasco', 
    'monterrey ': 'Monterrey, Nuevo León', 
    'iztapalapa, ciudad de mexico': 'Iztapalapa, Ciudad de México',
    'em  acayucan': 'Acayucan, Veracruz', 
    'em tuxtla gutierrez': 'Tuxtla Gutiérrez, Chiapas', 
    ' la ventosa': 'Heroica Ciudad de Juchitán de Zaragoza, Oaxaca',
    'e.m. huatulco': 'Santa María Huatulco, Oaxaca', 
    'queretaro': 'Querétaro, Querétaro', 
    'villahermosa, tabasco': 'Centro, Tabasco',
    'comitan de dominguez': 'Comitán de Domínguez, Chiapas', 
    'palenque': 'Palenque, Chiapas', 
    'oficinas administrativas reynosa': 'Reynosa, Tamaulipas',
    'aeropuerto lucio blanco \\ reynosa': 'Reynosa, Tamaulipas',  
    'tuxtla': 'Tuxtla Gutiérrez, Chiapas',
    'tampico, tamaulipas': 'Tampico, Tamaulipas', 
    'queretaro, qro': 'Querétaro, Querétaro', 
    'comitan, chis': 'Comitán de Domínguez, Chiapas',
    'monterrey, nvo leon': 'Monterrey, Nuevo León', 
    'hermosillo, son': 'Hermosillo, Sonora', 
    'honduras': 'Honduras',
    'san salvador': 'El Salvador', 
    ' guatemala': 'Guatemala',
    'haiti (salida aerop. de tapachula, chis)': 'Tapachula, Chiapas',
    'estación mig. veracruz': 'Acayucan, Veracruz', 
    'aeropuerto de tuxtla gutierrez chis.': 'Chiapa de Corzo, Chiapas',
    'aeropuerto de cdmx': 'Venustiano Carranza, Ciudad de México', 
    'aeropuerto de villahermosa': 'Centro, Tabasco',
    'cdmx iztapalapa': 'Iztapalapa, Ciudad de México', 
    'aeropuerto villahermosa': 'Centro, Tabasco', 
    'minatitlan': 'Minatitlán, Veracruz',
    'hondureña': 'Honduras', 
    'monterrey, nuevo leon': 'Monterrey, Nuevo León', 
    'saltillo, coahuila': 'Saltillo, Coahuila de Zaragoza',
    'cd. cuauhtemoc': 'Frontera Comalapa, Chiapas', 
    'san cristobal de las casas': 'San Cristóbal de las Casas, Chiapas', 
    'e.m. siglo xxi ': 'Tapachula, Chiapas',
    'acayucan - tapachula': 'Acayucan, Veracruz', 
    'iztapalapa - tapachula': 'Iztapalapa, Ciudad de México',
    'aeropuerto internacional de ciudad juarez': 'Juárez, Chihuahua',
    'aeropuerto de saltillo, coahuila': 'Ramos Arizpe, Coahuila de Zaragoza', 
    'cd juarez':'Juárez, Chihuahua',
    'chiapas-el carmen/ e. m. tenosique': 'Pijijiapan, Chiapas',
    'chiapas-el carmen/ frontera talisman':'Pijijiapan, Chiapas',
    'o. p. toluca': 'Toluca, México',
    'o. p. toluca/o. p. aeropuerto internacional ciudad de mexico': 'Toluca, México',
    'e. m. tapachula': 'Tapachula, Chiapas', 
    'cdmx ': 'Cuauhtémoc, Ciudad de México', 
    'torreon': 'Torreón, Coahuila de Zaragoza', 
    'monclova': 'Monclova, Coahuila de Zaragoza', 
    'saltillo,coahuila': 'Saltillo, Coahuila de Zaragoza', 
    'acayucan,  veracruz': 'Acayucan, Veracruz',
    'villahermosa, tabasco ': 'Centro, Tabasco', 
    'aeropuerto intl nuevo leon ': 'Apodaca, Nuevo León',
    'guadalupe, nuevo leon ': 'Guadalupe, Nuevo León', 
    'monclova, coahuila': 'Monclova, Coahuila de Zaragoza',
    'gomez palacio dgo': 'Gómez Palacio, Durango', 
    'monterrey nuevo leon ': 'Monterrey, Nuevo León', 
    'ramos arizpe': 'Ramos Arizpe, Coahuila de Zaragoza',
    'reynosa tamaulipas ': 'Reynosa, Tamaulipas', 
    'san miguel de allende': 'San Miguel de Allende, Guanajuato', 
    'acapulco': 'Acapulco de Juárez, Guerrero',
    'villahermosa ': 'Centro, Tabasco', 
    'san luis potosi, slp': 'San Luis Potosí, San Luis Potosí', 
    'estado de méxico': 'Estado de México',
    'tapachula chiapas': 'Tapachula, Chiapas', 
    'tepótzotlan': 'Tepotzotlán, México', 
    'acayucán veracruz': 'Acayucan, Veracruz',
    'ciudad ixtepec oaxaca ': 'Ciudad Ixtepec, Oaxaca', 
    'tapachula chiapas ': 'Tapachula, Chiapas', 
    'villa hermosa': 'Centro, Tabasco',
    'em huatulco': 'Santa María Huatulco, Oaxaca', 
    'la ventosa': 'Heroica Ciudad de Juchitán de Zaragoza, Oaxaca', 
    'tuxtla, gtz. chis.': 'Tuxtla Gutiérrez, Chiapas', 
    'villahermosa, tab.': 'Centro, Tabasco', 
    'pais de origen': 'Deportación', 
    'villahermosa tabasco': 'Centro, Tabasco', 
    'acayucan ': 'Acayucan, Veracruz', 
    'omoa honduras': 'Honduras',
    'huixtla chiapas ': 'Huixtla, Chiapas', 
    'tenosique tabasco': 'Tenosique, Tabasco', 
    'cancun, quintana roo': 'Benito Juárez, Quintana Roo',
    'tuxtla gutiérrez, chiapas': 'Tuxtla Gutiérrez, Chiapas', 
    'chiapa de corzo, chiapas': 'Chiapa de Corzo, Chiapas',
    'tecum uman': 'Guatemala', 
    'san pedro sula honduras': 'Honduras', 
    'coatzacoalcos': 'Coatzacoalcos, Veracruz',
    'el ceibo ': 'Tenosique, Tabasco', 
    'aeropuero de nuevo laredo': 'Nuevo Laredo, Tamaulipas', 
    'e.m. nuevo leon': 'Guadalupe, Nuevo León',
    'villahermosa, villahermosa, tabasco': 'Centro, Tabasco',
    'villahermosa, villahermosa, tabasco ': 'Centro, Tabasco', 
    'reynosa, tamaulipas': 'Reynosa, Tamaulipas',
    'villahermosa, villahermosa, tabasco, villahermosa, tabasco': 'Centro, Tabasco',
    'matamoros': 'Matamoros, Tamaulipas', 
    'guadalupe nuevo leon': 'Guadalupe, Nuevo León', 
    'tapachula, chis ': 'Tapachula, Chiapas',
    'villahermosa, tab. ': 'Centro, Tabasco', 
    'celaya, gto ': 'Celaya, Guanajuato', 
    'ixtepec, oax': 'Ciudad Ixtepec, Oaxaca',
    'coatzacoalcos, ver': 'Coatzacoalcos, Veracruz', 
    'el ceibo, tab. ': 'Tenosique, Tabasco', 
    'ixtepec- tapachula': 'Ciudad Ixtepec, Oaxaca',
    'san luis potosi ': 'San Luis Potosí, San Luis Potosí', 
    'cdmx- san luis potosi ': 'Iztapalapa, Ciudad de México',
    'oficina de canazalización nna acayucan ': 'Acayucan, Veracruz',
    'albergue hermanos en el camino, a.c. ixtepec, oaxaca': 'Ciudad Ixtepec, Oaxaca', 
    'em villa': 'Centro, Tabasco',
    'san luis potosi, san luis potosi': 'San Luis Potosí, San Luis Potosí', 
    'guadalupe, nuevo leon': 'Guadalupe, Nuevo León',
    'leon, guanajuato': 'León, Guanajuato', 
    'em villahermosa': 'Centro, Tabasco', 
    'quetzaltenango': 'Guatemala',
    'san pedro sula': 'Honduras', 
    'villa hermosa tabasco': 'Centro, Tabasco', 
    'suchiate': 'Suchiate, Chiapas', 
    'arriaga': 'Arriaga, Chiapas',
    'cd. cuautemoc': 'Frontera Comalapa, Chiapas', 
    'cd. mexico': 'Cuauhtémoc, Ciudad de México', 
    'estacion migratoria cupape': 'Chiapa de Corzo, Chiapas',
    'caitf huixtla': 'Huixtla, Chiapas', 
    'frontera tecun uman. ': 'Guatemala',
    'centro de atencion para la niñez migrante de huixtla, chiapas': 'Huixtla, Chiapas',
    'e.m. siglo xxi': 'Tapachula, Chiapas',
    'estacion migratoria las agujas, iztapalapa, estado de mexico': 'Iztapalapa, Ciudad de México',
    'aeropuerto internacional de tapachula, chiapas': 'Tapachula, Chiapas',
    'tuxtla gutierrez, chiapas.': 'Tuxtla Gutiérrez, Chiapas', 
    'tuxtla gutierrez nna': 'Tuxtla Gutiérrez, Chiapas',
    'aeropuerto de monterrey': 'Apodaca, Nuevo León', 
    'aeropuerto de hermosillo': 'Hermosillo, Sonora',
    'juarez': 'Juárez, Chihuahua',
    'juarez - acayucan': 'Juárez, Chihuahua', 
    'aeropuerto de ciudad juarez': 'Juárez, Chihuahua', 
    ' iztapalapa': 'Iztapalapa, Ciudad de México',
    'hermosillo': 'Hermosillo, Sonora', 
    'e.m. oaxaca/ e. p. san pedro tapanatepec ': 'San Pedro Tapanatepec, Oaxaca',
    'o. p. toluca/ o. p.  aeropuerto int. ciudad de mexico': 'Toluca, México',
    'gomez palacio, dgo': 'Gómez Palacio, Durango', 
    'san miguel allende ': 'San Miguel de Allende, Guanajuato', 
    'iztapala': 'Iztapalapa, Ciudad de México', 
    'chalco': 'Chalco, México',
    'ixtapaluca': 'Ixtapaluca, México', 
    'tlanepantla': 'Tlalnepantla de Baz, México', 
    'san luis postosi ': 'San Luis Potosí, San Luis Potosí', 
    'tecún uman': 'Guatemala',
    'oaxaca de juarez ': 'Oaxaca de Juárez, Oaxaca', 
    'emhuatulco': 'Santa María Huatulco, Oaxaca', 
    'em tapachula ': 'Tapachula, Chiapas',
    'e.p. la ventosa': 'Heroica Ciudad de Juchitán de Zaragoza, Oaxaca', 
    'e.m. acayucan, ver.': 'Acayucan, Veracruz', 
    'e.m. villa hermosa': 'Centro, Tabasco',
    'toluca': 'Toluca, México', 
    'toluca, estado de mexico': 'Toluca, México',
    'villahermosa, tabasco // minatitlan, veracruz': 'Centro, Tabasco', 
    'oaxaca, oaxaca': 'Oaxaca de Juárez, Oaxaca',
    'tuxtla chico': 'Tuxtla Chico, Chiapas', 
    'zacatecas, zacatecas': 'Zacatecas, Zacatecas', 
    'san luis potosí': 'San Luis Potosí, San Luis Potosí',
    'monterrey,  nuevo león':'Monterrey, Nuevo León', 
    'cd. juarez, chihuahua': 'Juárez, Chihuahua',
    'puebla, puebla': 'Puebla, Puebla', 
    ' tapachula, chiapas': 'Tapachula, Chiapas', 
    'huixtla': 'Huixtla, Chiapas',
    'omoa cortés honduras': 'Honduras', 
    'belice' : 'Belice', 
    'villehermosa': 'Centro, Tabasco',
    'aeropuerto monterrey nuevo leon': 'Apodaca, Nuevo León',
    'aeropuerto internacional de monterrey nuevo leon': 'Apodaca, Nuevo León',
    'cd de mexico-las agujas-villahermosa': 'Iztapalapa, Ciudad de México',
    'estacion migratoria de ciudad de mexico (las agujas)': 'Iztapalapa, Ciudad de México',
    'e.m. tapachula chiapas': 'Tapachula, Chiapas', 
    'villahermosa, tabasco, tabasco': 'Centro, Tabasco',
    'aeropuero de reynosa, tamaulipas': 'Reynosa, Tamaulipas', 
    'queretaro, queretaro': 'Querétaro, Querétaro',
    'cd de mexico': 'Cuauhtémoc, Ciudad de México', 
    'el salvador': 'El Salvador', 
    'tecun umán, gtm ': 'Guatemala',
    'acayucan, veracruz ': 'Acayucan, Veracruz', 
    'coatzacoalcos, ver. ': 'Coatzacoalcos, Veracruz', 
    'apto, toluca ': 'Toluca, México',
    'omoa, honduras ': 'Honduras', 
    'oficina de canazalizacion nna acayucan': 'Acayucan, Veracruz',
    'albergue coatzacoalcos': 'Coatzacoalcos, Veracruz', 
    'omoa, honduras': 'Honduras',
    'tecún umán, guatemala': 'Guatemala', 
    'aerop. villahermosa': 'Centro, Tabasco',
    'guatemala, guatemala': 'Guatemala', 
    'aeropuerto tapachula': 'Tapachula, Chiapas', 
    'o.r. veracruz': 'Veracruz, Veracruz',
    'tecun umán, guatemala': 'Guatemala', 
    'aeropuerto de la ciudad de mexico, cdmx': 'Venustiano Carranza, Ciudad de México',
    'tecunuman, republica de guatemala': 'Guatemala', 
    'echegaray': 'Echegaray, Chiapas',
    'aeropuerto internacional de tapachula': 'Tapachula, Chiapas', 
    'huehuetan': 'Huehuetán, Chiapas',
    'estacion siglo xxi': 'Tapachula, Chiapas', 
    'san cristobal': 'San Cristóbal de las Casas, Chiapas', 
    'caitf-huixtla ': 'Huixtla, Chiapas',
    'san cristobal de las casa, chiapas': 'San Cristóbal de las Casas, Chiapas',
    'parque ecologico, tapachla, chiapas.': 'Tapachula, Chiapas', 
    'caitf, trinitaria': 'La Trinitaria, Chiapas',
    'frontera tecun uman.': 'Guatemala', 
    'janos, acayucan': 'Janos, Chihuahua', 
    'ciudad juárez': 'Juárez, Chihuahua',
    'janos ': 'Janos, Chihuahua', 
    'e.m. tapachula/ chiapas-el carmen': 'Tapachula, Chiapas', 
    'e.m. villahermosa': 'Centro, Tabasco',
    'e.m villahermosa': 'Centro, Tabasco', 
    'e.m. oaxaca/ e.m. villahermosa': 'Centro, Tabasco',
    'o.p aeropuerto internacional de la cuidad de mexico/ o.p toluca': 'Venustiano Carranza, Ciudad de México',
    'e. m. villahermosa, tabasco': 'Centro, Tabasco', 
    'torreon coah.': 'Torreón, Coahuila de Zaragoza',
    'morelia, michoacan': 'Morelia, Michoacán', 
    'acapulco, guerrero': 'Acapulco de Juárez, Guerrero',
    'aguascalientes, aguascalientes': 'Aguascalientes, Aguascalientes', 
    'torreon, coahuila': 'Torreón, Coahuila de Zaragoza',
    'san miguel de allende, guanajuato': 'San Miguel de Allende, Guanajuato', 
    'lazaro cardenas, michoacan': 'Lázaro Cárdenas, Michoacán', 
    'gomez palacio, durango': 'Gómez Palacio, Durango',
    'mazatlan, sinaloa': 'Mazatlán, Sinaloa', 
    'aeropuerto intl nuevo leon': 'Apodaca, Nuevo León',
    'aeropuerto intl ramos arizpe, coahuila': 'Ramos Arizpe, Coahuila de Zaragoza',
    'aeropuerto intl reynosa, tamaulipas': 'Reynosa, Tamaulipas', 
    'izatapalap, cdmx': 'Iztapalapa, Ciudad de México', 
    'acuña': 'Acuña, Coahuila de Zaragoza',
    'aeropuerto int. piedras negras': 'Nava, Coahuila de Zaragoza', 
    'monterrey nl': 'Monterrey, Nuevo León',
    'gómez palacio, dgo': 'Gómez Palacio, Durango', 
    'guadalupe, zacatecas': 'Guadalupe, Zacatecas',
    'monterrey, nuevo león': 'Monterrey, Nuevo León', 
    'viillahermosa, tabasco': 'Centro, Tabasco', 
    'leon': 'León, Guanajuato',
    'irapuato': 'Irapuato, Guanajuato', 
    'celaya': 'Celaya, Guanajuato', 
    'salamanca': 'Salamanca, Guanajuato', 
    'guanajuato': 'Guanajuato, Guanajuato',
    'acayucan,veracruz': 'Acayucan, Veracruz', 
    'tuxtla gutierrez chiapas': 'Tuxtla Gutiérrez, Chiapas',
    'atlacomulco-maravatío': 'Atlacomulco, México', 
    'apaxco-huehuetoca': 'Apaxco, México',
    'edo. méx.': 'Estado de México',
    'dif. toluca': 'Toluca, México', 
    'dif. toluca una noche/ villahermosa tabasco': 'Toluca, México',
    'iztapalapa una noche/ villahermosa tabasco': 'Iztapalapa, Ciudad de México', 
    'or. toluca': 'Toluca, México',
    'iztapalapa, cd. de mexico': 'Iztapalapa, Ciudad de México', 
    'estados unidos': 'Estados Unidos',
    'tapacula': 'Tapachula, Chiapas', 
    'estancia provisionalsan agustin de la juntas': 'San Agustín de las Juntas, Oaxaca',
    'arriaga, chiapas': 'Arriaga, Chiapas', 
    'estacion migratoria tapachula chiapas': 'Tapachula, Chiapas',
    'estación migratoria las agujas en iztapalapa, estado de méxico': 'Iztapalapa, Ciudad de México',
    'salina cruz, oax.': 'Salina Cruz, Oaxaca', 
    'tapachula, \nchis': 'Tapachula, Chiapas',
    'jalapa del marquez, oax.': 'Santa María Jalapa del Marqués, Oaxaca', 
    'tonala chiapas': 'Tonalá, Chiapas', 
    'arriaga chiapas': 'Arriaga, Chiapas',
    'jalapa del marques, oax.': 'Santa María Jalapa del Marqués, Oaxaca', 
    'jalapa del marques oax.': 'Santa María Jalapa del Marqués, Oaxaca',
    'jalpa del marquez, oax.': 'Santa María Jalapa del Marqués, Oaxaca', 
    'salina cruz': 'Salina Cruz, Oaxaca', 
    'oaxaca de juarez': 'Oaxaca de Juárez, Oaxaca',
    'la venta': 'Huimanguillo, Tabasco', 
    'tecun-uman': 'Guatemala', 
    'ceibo, villahermosa': 'Tenosique, Tabasco', 
    'aifa': 'Zumpango, México',
    'conduccion a cdmx': 'Cuauhtémoc, Ciudad de México', 
    'villahermosa, tabasco // ciudad de mexico': 'Centro, Tabasco',
    'talisman, tuxtla chico, chiapas': 'Talismán, Chiapas', 
    'el ceibo': 'Tenosique, Tabasco',
    'el ceibo, tenosique': 'Tenosique, Tabasco', 
    'e.m. villahermosa, tabasco': 'Centro, Tabasco',
    'punto de internacion terrestre el ceibo': 'Tenosique, Tabasco',
    'aeropuerto int. de villahermosa': 'Centro, Tabasco', 
    'san diego, california e.u.': 'Estados Unidos',
    'acayucan veracruz': 'Acayucan, Veracruz', 
    'cd de mexico las agujas': 'Iztapalapa, Ciudad de México',
    'aeropuerto internacional de monterrey n.l.': 'Apodaca, Nuevo León', 
    'monterrey, nl': 'Monterrey, Nuevo León',
    'tampico, tamps': 'Tampico, Tamaulipas', 
    'reynosa, tamps': 'Reynosa, Tamaulipas', 
    'aeropuerto  de reynosa': 'Reynosa, Tamaulipas',
    'aeropuerto de reynosa': 'Reynosa, Tamaulipas', 
    'tapachula, chiapas.': 'Tapachula, Chiapas',
    'villahermosa, tabasco.': 'Centro, Tabasco', 
    'albergue dif estatal mina': 'Cuauhtémoc, Ciudad de México',
    'albergue santa faustina  kowalska, a.c.': 'Coatzacoalcos, Veracruz',
    'albergue monseñor guillermo ranzahuer': 'Oluta, Veracruz', 
    'nicaragua': 'Nicaragua',
    'tapachula/ecuador': 'Tapachula, Chiapas', 
    'aeropuerto cdmx': 'Venustiano Carranza, Ciudad de México', 
    'tapachula chis': 'Tapachula, Chiapas',
    'oficina admitiva acy': 'Acayucan, Veracruz', 
    'albergue minatitlan': 'Minatitlán, Veracruz',
    'san pedro sula, honduras': 'Honduras',
    'aeropuerto internacional de ciudad de mexicio': 'Venustiano Carranza, Ciudad de México',
    'estancia provisional\ntipo en tijuana': 'Tijuana, Baja California', 
    'zatecas': 'Zacatecas, Zacatecas',
    'aeropuerto de tijuana': 'Tijuana, Baja California', 
    'apto cd juarez': 'Juárez, Chihuahua', 
    'e. m. tapachula, chiapas': 'Tapachula, Chiapas',
    'zacatecas, zac': 'Zacatecas, Zacatecas', 
    'edo. mex': 'Estado de México', 
    'dif toluca': 'Toluca, México',
    'veracruz ': 'veracruz',
    'aeropuerto internacional de morelia': 'Álvaro Obregón, Michoacán',
    'terminal de autobuses de morelia': 'Morelia, Michoacán', 
    'san pedro tapanatepec': 'San Pedro Tapanatepec, Oaxaca',
    'huatulco, oaxaca': 'Santa María Huatulco, Oaxaca', 
    'estancia provisional en villahermosa tabasco': 'Centro, Tabasco',
    'estancia provisional en tuxtla gutierrez chiapas': 'Tuxtla Gutiérrez, Chiapas',
    'berriozabal, chiapas': 'Berriozábal, Chiapas', 
    'jalapa del marquez oaxaca': 'Santa María Jalapa del Marqués, Oaxaca',
    'tonala, chiapas': 'Tonalá, Chiapas', 
    'tonala, chis.': 'Tonalá, Chiapas' , 
    'berriozabal, chis.':'Berriozábal, Chiapas' ,
    'arriaga, chis.': 'Arriaga, Chiapas', 
    'pijijiapan, chis.': 'Pijijiapan, Chiapas', 
    'tuxtla gutierrez, chis.': 'Tuxtla Gutiérrez, Chiapas',
    'jalapa del marquez': 'Santa María Jalapa del Marqués, Oaxaca', 
    'la ventosa, juchitan':'Heroica Ciudad de Juchitán de Zaragoza, Oaxaca', 
    'puebla, pue.':'Puebla, Puebla',
    'cancún': 'Benito Juárez, Quintana Roo', 
    'escuinapa': 'Escuinapa de Hidalgo, Sinaloa', 
    'guasave': 'Guasave, Sinaloa', 
    'ahome': 'Ahome, Sinaloa', 
    'culiacan': 'Culiacán, Sinaloa',
    'omoa, cortes, honduras': 'Honduras', 
    'apto reynosa': 'Reynosa, Tamaulipas', 
    'guadalupe, n.l.': 'Guadalupe, Nuevo León',
    'aeropuerto, tampico': 'Tampico, Tamaulipas', 
    'albergue del dif estatal en minatitlan': 'Minatitlán, Veracruz',
    'albergue minatitlan, ver': 'Minatitlán, Veracruz', 
    'omoa, hoduras': 'Honduras', 
    'omoa, hondureña': 'Honduras',
    '  ciudad de mexico': 'Cuauhtémoc, Ciudad de México',
    'aeropuerto inl reynosa, tamaulipas': 'Reynosa, Tamaulipas',
    'aeropuerto int, de monterrey': 'Apodaca, Nuevo León',
    'aeropuerto int. cd. de mexico': 'Venustiano Carranza, Ciudad de México',
    'aeropuerto int. monterrey': 'Apodaca, Nuevo León',
    'aeropuerto int. plan de guadalupe': 'Ramos Arizpe, Coahuila de Zaragoza',
    'aeropuerto internacional de ciudad de mexicio ': 'Venustiano Carranza, Ciudad de México',
    'aeropuerto intl ramos arizpe, coahuila ': 'Ramos Arizpe, Coahuila de Zaragoza',
    'aeropuerto intl toluca': 'Toluca, Estado de México',
    'aeropuerto itnl nuevo leon ': 'Apodaca, Nuevo León',
    'aeropuerto itnl ramos arizpe ': 'Ramos Arizpe, Coahuila de Zaragoza',
    'aguascalientes ': 'aguascalientes',
    'arriaga chiapas ': 'Arriaga, Chiapas',
    'awropuerto int. plan de guadalupe': 'Ramos Arizpe, Coahuila de Zaragoza',
    'cdmx  ': 'Cuauhtémoc, Ciudad de México',
    'ciudad de mexico ': 'Cuauhtémoc, Ciudad de México',
    'dif toluca ': 'Toluca, Estado de México',
    'durango ': 'Durango, Durango',
    'e.m villahermosa ': 'Centro, Tabasco',
    'e.m. tapachula/ chiapas-el carmen ': 'Tapachula, Chiapas',
    'e.m. villahermosa ': 'Centro, Tabasco',
    'estados unidos ': 'Estados Unidos',
    'gomez palacio, durango ': 'Gómez Palacio, Durango',
    'hidalgo, coahuila ': 'Hidalgo, Coahuila de Zaragoza',
    'irapuato ': 'Irapuato, Guanajuato',
    'la venta ': 'Huimanguillo, Tabasco',
    'la ventosa, juchitan ': 'Heroica Ciudad de Juchitán de Zaragoza, Oaxaca',
    'lazaro cardenas, michoacan ': 'Lázaro Cárdenas, Michoacán',
    'monclova, coahuila ': 'Monclova, Coahuila de Zaragoza',
    'monterrey, nuevo leon ': 'Monterrey, Nuevo León', 
    'morelia, michoacan ': 'Morelia, Michoacán',
    'nuevo laredo, tamaulipas': 'Nuevo Laredo, Tamaulipas',
    'pachuca, hidalgo ': 'Pachuca de Soto, Hidalgo',
    'puebla': 'Puebla, Puebla',
    'puebla ': 'Puebla, Puebla',
    'queretaro ': 'Querétaro, Querétaro',
    'queretaro, queretaro ': 'Querétaro, Querétaro',
    'reynosa ': 'Reynosa, Tamaulipas',
    'reynosa, tamaulipas ': 'Reynosa, Tamaulipas',
    'salamanca ': 'Salamanca, Guanajuato',
    'salina cruz ': 'Salina Cruz, Oaxaca',
    'saltillo ': 'Saltillo, Coahuila',
    'san cristobal ': 'San Cristóbal de las Casas, Chiapas',
    'san cristobal de las casa, chiapas ': 'San Cristóbal de las Casas, Chiapas',
    'san miguel de allende, guanajuato ': 'San Miguel de Allende, Guanajuato',
    'tapachula ': 'Tapachula, Chiapas',
    'tonala chiapas ': 'Tonalá, Chiapas',
    'torreon, coahuila ': 'Torreón, Coahuila de Zaragoza',
    'tuxtla gutierrez, chiapas ': 'Tuxtla Gutiérrez, Chiapas',
    'villa hermosa ': 'Centro, Tabasco',
    'villahermosa tabasco ': 'Centro, Tabasco',
    'villahermosa, tab  ': 'Centro, Tabasco',
    'nuevo leon ': 'nuevo león',
    'michoacan': 'michoacán'
}

def apply_corrections(x):
    if isinstance(x, str):
        return corrections.get(x.lower(), x)
    return x

cols_to_fix = ['lugar_origen', 'lugar_destino']  

master[cols_to_fix] = master[cols_to_fix].map(apply_corrections)

In [215]:
# Hay algunas entradas para las que no existen datos claros, las borramos
master = master[~((master['lugar_origen'].str.lower() == 'e.m. oaxaca') | (master['lugar_destino'].str.lower() == 'e.m. oaxaca'))]
master = master[~((master['lugar_origen'].str.lower() == 'e.m. oaxaca ') | (master['lugar_destino'].str.lower() == 'e.m. oaxaca '))]
master = master[~((master['lugar_origen'].str.lower() == 'precos') | (master['lugar_destino'].str.lower() == 'precos'))]
master = master[~((master['lugar_origen'].str.lower() == 'subdelegación local del inm en el estado de oaxaca') | (master['lugar_destino'].str.lower() == 'subdelegación local del inm en el estado de oaxaca'))]
master = master[~((master['lugar_origen'].str.lower() == 'no se cuenta con la informacion') | (master['lugar_destino'].str.lower() == 'no se cuenta con la informacion'))]

In [216]:
# Volviendo a ver qué hay
pd.unique(master[['lugar_origen', 'lugar_destino']].values.ravel())

array(['Janos, Chihuahua', 'Chihuahua, Chihuahua',
       'Iztapalapa, Ciudad de México', 'Pachuca de Soto, Hidalgo',
       'Guadalajara, Jalisco', 'Acayucan, Veracruz', 'Estado de México',
       'San Pedro Tapanatepec, Oaxaca', 'Tapachula, Chiapas',
       'Heroica Ciudad de Juchitán de Zaragoza, Oaxaca', 'Guatemala',
       'Othón P. Blanco, Quintana Roo',
       'San Luis Potosí, San Luis Potosí', 'Nuevo Laredo, Tamaulipas',
       'Cuauhtémoc, Ciudad de México', 'Tampico, Tamaulipas',
       'Zacatecas, Zacatecas', 'aguascalientes',
       'Tijuana, Baja California', 'Escárcega, Campeche',
       'Tenosique, Tabasco', 'Benito Juárez, Quintana Roo',
       'Campeche, Campeche', 'Comitán de Domínguez, Chiapas',
       'Tuxtla Gutiérrez, Chiapas', 'Piedras Negras, Coahuila',
       'Santa María Huatulco, Oaxaca', 'Oaxaca de Juárez, Oaxaca',
       'Salina Cruz, Oaxaca', 'Mazatlán, Sinaloa', 'Reynosa, Tamaulipas',
       'Ciudad Victoria, Tamaulipas',
       'Apetatitlán de Antonio Carvajal, Tlaxcala',
       'Guadalupe, Nuevo León', 'Veracruz, Veracruz', 'Carmen, Campeche',
       'chihuahua', 'Pijijiapan, Chiapas', 'Gómez Palacio, Durango',
       'veracruz', 'Morelia, Michoacán', 'Tepic, Nayarit',
       'Saltillo, Coahuila de Zaragoza', 'tabasco', 'Juárez, Chihuahua',
       'Puebla, Puebla', 'Toluca, México', 'Centro, Tabasco',
       'Monterrey, Nuevo León', 'Palenque, Chiapas', 'nuevo leon',
       'coahuila', 'Querétaro, Querétaro', 'Hermosillo, Sonora',
       'Honduras', 'El Salvador', 'Chiapa de Corzo, Chiapas',
       'Venustiano Carranza, Ciudad de México', 'Minatitlán, Veracruz',
       'San Cristóbal de las Casas, Chiapas',
       'Ramos Arizpe, Coahuila de Zaragoza',
       'Torreón, Coahuila de Zaragoza', 'Monclova, Coahuila de Zaragoza',
       'chiapas', 'Apodaca, Nuevo León',
       'San Miguel de Allende, Guanajuato',
       'Acapulco de Juárez, Guerrero', 'Tepotzotlán, México',
       'Ciudad Ixtepec, Oaxaca', 'Deportación', 'Huixtla, Chiapas',
       'Coatzacoalcos, Veracruz', 'Matamoros, Tamaulipas',
       'Celaya, Guanajuato', 'Mérida, Yucatán', 'León, Guanajuato',
       'Suchiate, Chiapas', 'Arriaga, Chiapas',
       'Frontera Comalapa, Chiapas', 'tamaulipas', 'michoacán',
       'Toluca, Estado de México', 'Hidalgo, Coahuila de Zaragoza',
       'Chalco, México', 'Ixtapaluca, México',
       'Tlalnepantla de Baz, México', 'Tuxtla Chico, Chiapas', 'Belice',
       'Echegaray, Chiapas', 'Huehuetán, Chiapas',
       'La Trinitaria, Chiapas', 'e.m. oaxaca/ e.m. villahermosa ',
       'guerrero', 'nuevo león', 'Aguascalientes, Aguascalientes',
       'Durango, Durango', 'Lázaro Cárdenas, Michoacán',
       'Acuña, Coahuila de Zaragoza', 'Nava, Coahuila de Zaragoza',
       'Guadalupe, Zacatecas', 'Irapuato, Guanajuato',
       'Salamanca, Guanajuato', 'Guanajuato, Guanajuato',
       'Atlacomulco, México', 'Apaxco, México',
       'San Agustín de las Juntas, Oaxaca',
       'Santa María Jalapa del Marqués, Oaxaca', 'Tonalá, Chiapas',
       'Huimanguillo, Tabasco', 'Zumpango, México', 'Talismán, Chiapas',
       'Estados Unidos', 'tlaxcala', 'Oluta, Veracruz', 'Nicaragua',
       'Saltillo, Coahuila', 'Álvaro Obregón, Michoacán',
       'Berriozábal, Chiapas', 'Escuinapa de Hidalgo, Sinaloa',
       'Guasave, Sinaloa', 'Ahome, Sinaloa', 'Culiacán, Sinaloa',
       'nuevo leon  '], dtype=object)

#### No limpiamos las entradas que son solamente nombres de entidades federativas porque por cómo nos entregaron las tablas, pensamos que podrían ser los nombres de las oficinas de representación del INM en los Estados, que sirven como estimado del origen. No atreveríamos a generalizar eso para lugar_destino ya que los traslados podían ir a un sin fin de lugares particulares. Así que, buscando los municipios de las oficinas de representación en el sitio del INM, aplicaremos estas correcciones únicamente a la columna "lugar_origen"

In [217]:
master.lugar_origen=master.lugar_origen.str.replace('aguascalientes', 'Jesús María, Aguascalientes').str.replace('chihuahua','Juárez, Chihuahua')
master.lugar_origen=master.lugar_origen.str.replace('veracruz', 'Veracruz, Veracruz').str.replace('veracruz ', 'Veracruz, Veracruz')
master.lugar_origen=master.lugar_origen.str.replace('tabasco', 'Centro, Tabasco').str.replace('coahuila', 'Saltillo, Coahuila de Zaragoza')
master.lugar_origen=master.lugar_origen.str.replace('nuevo leon', 'Guadalupe, Nuevo León').str.replace('nuevo león', 'Guadalupe, Nuevo León')
master.lugar_origen=master.lugar_origen.str.replace('chiapas', 'Tapachula, Chiapas').str.replace('puebla', 'Puebla, Puebla')
master.lugar_origen=master.lugar_origen.str.replace('guerrero', 'Acapulco de Juárez, Guerrero').str.replace('durango', 'Durango, Durango')
master.lugar_origen=master.lugar_origen.str.replace('tlaxcala', 'Tlaxcala, Tlaxcala').str.replace('Estado de México', 'Toluca, México')

In [218]:
sorted(pd.unique(master[['lugar_origen', 'lugar_destino']].values.ravel()))

['Acapulco de Juárez, Guerrero',
 'Acayucan, Veracruz',
 'Acuña, Coahuila de Zaragoza',
 'Aguascalientes, Aguascalientes',
 'Ahome, Sinaloa',
 'Apaxco, México',
 'Apetatitlán de Antonio Carvajal, Tlaxcala',
 'Apodaca, Nuevo León',
 'Arriaga, Chiapas',
 'Atlacomulco, México',
 'Belice',
 'Benito Juárez, Quintana Roo',
 'Berriozábal, Chiapas',
 'Campeche, Campeche',
 'Carmen, Campeche',
 'Celaya, Guanajuato',
 'Centro, Tabasco',
 'Chalco, México',
 'Chiapa de Corzo, Chiapas',
 'Chihuahua, Chihuahua',
 'Ciudad Ixtepec, Oaxaca',
 'Ciudad Victoria, Tamaulipas',
 'Coatzacoalcos, Veracruz',
 'Comitán de Domínguez, Chiapas',
 'Cuauhtémoc, Ciudad de México',
 'Culiacán, Sinaloa',
 'Deportación',
 'Durango, Durango',
 'Echegaray, Chiapas',
 'El Salvador',
 'Escuinapa de Hidalgo, Sinaloa',
 'Escárcega, Campeche',
 'Estados Unidos',
 'Frontera Comalapa, Chiapas',
 'Guadalajara, Jalisco',
 'Guadalupe, Nuevo León',
 'Guadalupe, Nuevo León  ',
 'Guadalupe, Zacatecas',
 'Guanajuato, Guanajuato',
 'Guasave, Sinaloa',
 'Guatemala',
 'Gómez Palacio, Durango',
 'Hermosillo, Sonora',
 'Heroica Ciudad de Juchitán de Zaragoza, Oaxaca',
 'Hidalgo, Coahuila de Zaragoza',
 'Honduras',
 'Huehuetán, Chiapas',
 'Huimanguillo, Tabasco',
 'Huixtla, Chiapas',
 'Irapuato, Guanajuato',
 'Ixtapaluca, México',
 'Iztapalapa, Ciudad de México',
 'Janos, Chihuahua',
 'Jesús María, Aguascalientes',
 'Juárez, Chihuahua',
 'La Trinitaria, Chiapas',
 'León, Guanajuato',
 'Lázaro Cárdenas, Michoacán',
 'Matamoros, Tamaulipas',
 'Mazatlán, Sinaloa',
 'Minatitlán, Veracruz',
 'Monclova, Coahuila de Zaragoza',
 'Monterrey, Nuevo León',
 'Morelia, Michoacán',
 'Mérida, Yucatán',
 'Nava, Coahuila de Zaragoza',
 'Nicaragua',
 'Nuevo Laredo, Tamaulipas',
 'Oaxaca de Juárez, Oaxaca',
 'Oluta, Veracruz',
 'Othón P. Blanco, Quintana Roo',
 'Pachuca de Soto, Hidalgo',
 'Palenque, Chiapas',
 'Piedras Negras, Coahuila',
 'Pijijiapan, Chiapas',
 'Puebla, Puebla',
 'Querétaro, Querétaro',
 'Ramos Arizpe, Coahuila de Zaragoza',
 'Reynosa, Tamaulipas',
 'Salamanca, Guanajuato',
 'Salina Cruz, Oaxaca',
 'Saltillo, Coahuila',
 'Saltillo, Coahuila de Zaragoza',
 'San Agustín de las Juntas, Oaxaca',
 'San Cristóbal de las Casas, Chiapas',
 'San Luis Potosí, San Luis Potosí',
 'San Miguel de Allende, Guanajuato',
 'San Pedro Tapanatepec, Oaxaca',
 'Santa María Huatulco, Oaxaca',
 'Santa María Jalapa del Marqués, Oaxaca',
 'Suchiate, Chiapas',
 'Talismán, Chiapas',
 'Tampico, Tamaulipas',
 'Tapachula, Chiapas',
 'Tenosique, Tabasco',
 'Tepic, Nayarit',
 'Tepotzotlán, México',
 'Tijuana, Baja California',
 'Tlalnepantla de Baz, México',
 'Tlaxcala, Tlaxcala',
 'Toluca, Estado de México',
 'Toluca, México',
 'Tonalá, Chiapas',
 'Torreón, Coahuila de Zaragoza',
 'Tuxtla Chico, Chiapas',
 'Tuxtla Gutiérrez, Chiapas',
 'Venustiano Carranza, Ciudad de México',
 'Veracruz, Veracruz',
 'Zacatecas, Zacatecas',
 'Zumpango, México',
 'aguascalientes',
 'chiapas',
 'chihuahua',
 'coahuila',
 'e.m. oaxaca/ e.m. villahermosa ',
 'guerrero',
 'michoacán',
 'nuevo leon',
 'nuevo león',
 'tabasco',
 'tamaulipas',
 'veracruz',
 'Álvaro Obregón, Michoacán']

In [219]:
# Terminando la limpieza
corrections_2 = {
    'Echegaray, Chiapas': 'Pijijiapan, Chiapas',
    'Escuinapa de Hidalgo, Sinaloa': 'Escuinapa, Sinaloa',
    'Guadalupe, Nuevo León  ': 'Guadalupe, Nuevo León',
    'Piedras Negras, Coahuila': 'Piedras Negras, Coahuila de Zaragoza',
    'Saltillo, Coahuila': 'Saltillo, Coahuila de Zaragoza',
    'Toluca, Estado de México': 'Toluca, México',
}

def apply_corrections_2(x):
    if isinstance(x, str):
        return corrections_2.get(x.lower(), x)
    return x

cols_to_fix = ['lugar_origen', 'lugar_destino']  

master[cols_to_fix] = master[cols_to_fix].map(apply_corrections_2)

In [220]:
# Ya todos los valores de lugar_origen deberían estar bien
sorted(pd.unique(master[['lugar_origen']].values.ravel()))

['Acapulco de Juárez, Guerrero',
 'Acayucan, Veracruz',
 'Acuña, Coahuila de Zaragoza',
 'Ahome, Sinaloa',
 'Apaxco, México',
 'Apetatitlán de Antonio Carvajal, Tlaxcala',
 'Arriaga, Chiapas',
 'Atlacomulco, México',
 'Benito Juárez, Quintana Roo',
 'Campeche, Campeche',
 'Carmen, Campeche',
 'Celaya, Guanajuato',
 'Centro, Tabasco',
 'Chalco, México',
 'Ciudad Ixtepec, Oaxaca',
 'Ciudad Victoria, Tamaulipas',
 'Comitán de Domínguez, Chiapas',
 'Cuauhtémoc, Ciudad de México',
 'Echegaray, Chiapas',
 'Escuinapa de Hidalgo, Sinaloa',
 'Escárcega, Campeche',
 'Frontera Comalapa, Chiapas',
 'Guadalajara, Jalisco',
 'Guadalupe, Nuevo León',
 'Guadalupe, Nuevo León  ',
 'Guanajuato, Guanajuato',
 'Guasave, Sinaloa',
 'Gómez Palacio, Durango',
 'Hermosillo, Sonora',
 'Heroica Ciudad de Juchitán de Zaragoza, Oaxaca',
 'Huehuetán, Chiapas',
 'Huixtla, Chiapas',
 'Ixtapaluca, México',
 'Iztapalapa, Ciudad de México',
 'Janos, Chihuahua',
 'Jesús María, Aguascalientes',
 'Juárez, Chihuahua',
 'La Trinitaria, Chiapas',
 'León, Guanajuato',
 'Matamoros, Tamaulipas',
 'Mazatlán, Sinaloa',
 'Monclova, Coahuila de Zaragoza',
 'Morelia, Michoacán',
 'Mérida, Yucatán',
 'Nuevo Laredo, Tamaulipas',
 'Oaxaca de Juárez, Oaxaca',
 'Othón P. Blanco, Quintana Roo',
 'Pachuca de Soto, Hidalgo',
 'Palenque, Chiapas',
 'Piedras Negras, Coahuila',
 'Puebla, Puebla',
 'Querétaro, Querétaro',
 'Reynosa, Tamaulipas',
 'Salamanca, Guanajuato',
 'Salina Cruz, Oaxaca',
 'Saltillo, Coahuila',
 'Saltillo, Coahuila de Zaragoza',
 'San Agustín de las Juntas, Oaxaca',
 'San Cristóbal de las Casas, Chiapas',
 'San Luis Potosí, San Luis Potosí',
 'San Miguel de Allende, Guanajuato',
 'San Pedro Tapanatepec, Oaxaca',
 'Santa María Huatulco, Oaxaca',
 'Santa María Jalapa del Marqués, Oaxaca',
 'Suchiate, Chiapas',
 'Tampico, Tamaulipas',
 'Tapachula, Chiapas',
 'Tenosique, Tabasco',
 'Tepic, Nayarit',
 'Tepotzotlán, México',
 'Tijuana, Baja California',
 'Tlalnepantla de Baz, México',
 'Tlaxcala, Tlaxcala',
 'Toluca, México',
 'Torreón, Coahuila de Zaragoza',
 'Tuxtla Gutiérrez, Chiapas',
 'Veracruz, Veracruz',
 'Zacatecas, Zacatecas',
 'Álvaro Obregón, Michoacán']

In [221]:
sorted(pd.unique(master[['lugar_destino']].values.ravel()))

['Acapulco de Juárez, Guerrero',
 'Acayucan, Veracruz',
 'Aguascalientes, Aguascalientes',
 'Apodaca, Nuevo León',
 'Arriaga, Chiapas',
 'Belice',
 'Benito Juárez, Quintana Roo',
 'Berriozábal, Chiapas',
 'Celaya, Guanajuato',
 'Centro, Tabasco',
 'Chiapa de Corzo, Chiapas',
 'Chihuahua, Chihuahua',
 'Ciudad Ixtepec, Oaxaca',
 'Coatzacoalcos, Veracruz',
 'Comitán de Domínguez, Chiapas',
 'Cuauhtémoc, Ciudad de México',
 'Culiacán, Sinaloa',
 'Deportación',
 'Durango, Durango',
 'El Salvador',
 'Estados Unidos',
 'Guadalajara, Jalisco',
 'Guadalupe, Nuevo León',
 'Guadalupe, Zacatecas',
 'Guatemala',
 'Gómez Palacio, Durango',
 'Hermosillo, Sonora',
 'Heroica Ciudad de Juchitán de Zaragoza, Oaxaca',
 'Hidalgo, Coahuila de Zaragoza',
 'Honduras',
 'Huimanguillo, Tabasco',
 'Huixtla, Chiapas',
 'Irapuato, Guanajuato',
 'Iztapalapa, Ciudad de México',
 'Janos, Chihuahua',
 'Juárez, Chihuahua',
 'León, Guanajuato',
 'Lázaro Cárdenas, Michoacán',
 'Mazatlán, Sinaloa',
 'Minatitlán, Veracruz',
 'Monclova, Coahuila de Zaragoza',
 'Monterrey, Nuevo León',
 'Morelia, Michoacán',
 'Nava, Coahuila de Zaragoza',
 'Nicaragua',
 'Nuevo Laredo, Tamaulipas',
 'Oaxaca de Juárez, Oaxaca',
 'Oluta, Veracruz',
 'Othón P. Blanco, Quintana Roo',
 'Pachuca de Soto, Hidalgo',
 'Palenque, Chiapas',
 'Piedras Negras, Coahuila',
 'Pijijiapan, Chiapas',
 'Puebla, Puebla',
 'Querétaro, Querétaro',
 'Ramos Arizpe, Coahuila de Zaragoza',
 'Reynosa, Tamaulipas',
 'Saltillo, Coahuila de Zaragoza',
 'San Cristóbal de las Casas, Chiapas',
 'San Luis Potosí, San Luis Potosí',
 'San Miguel de Allende, Guanajuato',
 'San Pedro Tapanatepec, Oaxaca',
 'Santa María Huatulco, Oaxaca',
 'Santa María Jalapa del Marqués, Oaxaca',
 'Talismán, Chiapas',
 'Tampico, Tamaulipas',
 'Tapachula, Chiapas',
 'Tenosique, Tabasco',
 'Tijuana, Baja California',
 'Toluca, Estado de México',
 'Toluca, México',
 'Tonalá, Chiapas',
 'Torreón, Coahuila de Zaragoza',
 'Tuxtla Chico, Chiapas',
 'Tuxtla Gutiérrez, Chiapas',
 'Venustiano Carranza, Ciudad de México',
 'Veracruz, Veracruz',
 'Zacatecas, Zacatecas',
 'Zumpango, México',
 'aguascalientes',
 'chiapas',
 'chihuahua',
 'coahuila',
 'e.m. oaxaca/ e.m. villahermosa ',
 'guerrero',
 'michoacán',
 'nuevo leon',
 'nuevo león',
 'tabasco',
 'tamaulipas',
 'veracruz']

In [222]:
# Quitamos las filas para las que no hubo un destino claro 
values_to_drop = ['aguascalientes', 'chiapas', 'chihuahua', 'coahuila', 'e.m. oaxaca/ e.m. villahermosa ', 'guerrero', 'michoacán', 'nuevo leon', 'nuevo león', 'tabasco', 'tamaulipas', 'veracruz'] 
master = master[~master['lugar_destino'].isin(values_to_drop)]

In [223]:
# Checar que ya no hay filas con nacionalidad "No se cuenta..." o "Varios"
mask_keyword = master['nacionalidad'].str.contains('no |varios', case=False, na=False)

with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.max_colwidth', None):
    display(master.loc[mask_keyword, ['id_fila_og', 'nacionalidad']])

,id_fila_og,nacionalidad
352,359,hondureña y uno de costarica
1066,1119,34 hondureños 1 ecuatoriano 9 salvadoreños 4 guatemaltecos
1713,1796,34 hondureños 1 ecuatoriano 9 salvadoreños 4 guatemaltecos
4627,4828,"20 guatemaltecos, 01 salvadoreño, 01 cubano y 18 ecuatorianos"
4635,4836,"31 nicaraguense, 01 dominicano y 08 ecuatoriano"
4637,4838,"09 guatemaltecos, 01 salvadoreños, 18 nicaraguense, 01 colombiano y 10 cubanos"
4643,4844,13 cuba 9 venezolana 7 ecuatoriana 4 nicaraguense 2 peruano 1 dominicano 1 brasil 1 hondureño 1 colombiana
4655,4856,"guatemaltecos (30), hondureños (8), nicaragua (1), venezolano (1)"
5134,5335,09 venezuela 12 panama 04 colombia 06 nicaragua 05 honduras 05 guatemala 01 dominicano
7431,8238,17 guatemala 18 venezolano 2 honduras
7435,8242,4 venezuela 33 gtemala 1 colombiano 1 dominicano 2 cubanos 3 salvador
7446,8253,"16 guatemaltecos, 01 ecuatoriano y 04 venezolanos"
7447,8254,"07 guatemaltecos, 02 salvadoreños,01 brasileño, 09 venezolanos,01 peruano y 05 ecuatoriano"
7448,8255,"25 guatemaltecos,03 indios, 01 venezolano,01 colombiano y 08 ecuatorianos"
7453,8260,"27 guatemaltecos, 05 hondureños,05 ecuatorianos, 01 colombiano y 01 salvadoreño"
7461,8268,"22 guatemaltecos, 05 hondureños, 05 salvadoreño,05 ecuatorianos, 01 colombiano, 01 peruano y 01 dominicanos"
7462,8269,"25 guatemaltecos, 05 salvadoreño, 04 brasileños, 01 venezolano y 02 cubano"
7530,8337,"sierra leona (2), uzbekistan (15), dominicano (7), salvador (14)"
7532,8339,"guinea (4), vietnam (3), cubano (10), uzbekistan (10), hondureño (13)"
7534,8341,"senegal (4), ecuador (20), venezolano (14)"
7535,8342,"mauritania (4), afgana (5), china (9), venezolano (22)"
7703,8510,"39 venezolano, 01 colombiano"
7712,8519,"17 venezolanos, 02 colombianos, 21 ecuatorianos, 01 haitiano"
7713,8520,"33 cubanos, 4 ecuatorianos, 02 venezolanos, 01 colombiano"
7738,8545,"24 cubanos, 15 nicaragüenses, 01 ecuatoriano"
7740,8547,"25 cubanos, 14 nicaragüenses, 01 ecuatoriano"
7742,8549,"06 cubanos, 31 nicaragüenses, 01 venezolano"
7792,8599,"21 nicaragüenses, 04 colombianos, 02 dominicanos, 01 venezolano, 01 peruano"
7807,8614,"30 hondureños, 04 ecuatorianos, 02 peruanos, 03 salvadoreños, 01 dominicano"
7923,8730,34 venezuela 01 dominicano 01 hondureño
8145,8952,01 brasil - 01 colombia - 01 ecuador - 07 guatemala - 01 honduras - 04 india - 01 dominicano - 04 senegal - 09 mauritania - 11 venezuela
8324,9851,"15 chinos, 05 venezolanos, 06 hondureños, 02 haitianos, 02 guatemaltecos, 11 ecuatorianos, 01 colombiano"
9745,12437,"guatemala 12, senegal 3, burkina faso 1, peru 5,\niran 1, china 2, ecuador 5, jamaica 1, brasil 2, bolivia 1,\n colombia 7, guinea 3, india 3, libano 1, \nel congo 1, guatemala 3, colombia 5, ecuador 10, \nhaiti 4"
9869,12561,"12 guatemaltecos, 07 colombianos, 09 venezolanos, 06 hondureños, 04 nicaraguenses, 01 dominicano y 01 salvadoreño"
9871,12563,"02 guineanos, 23 venezolanos,01 hondureño, 02 nicaraguenses, 08 guatemaltecos, 05 colombianos, 01 cubano , 05 mauritania, 14 ecuatorianos, 02 brasileños, 06 salvadoreños, 01 peruano y 05 hondureños"
9878,12570,"10 ecuatorianos, 12 guatemaltecos, 01 colombiano,10 hondureños, 02 nicaraguenses, 01 salvadoreño, 01 peruano y 03 venezolanos"
9880,12572,"10 guatemaltecos, 05 hondureños, 04 salvadoreños, 07 nicaraguenses, 02 dominicnos, 10 ecuatorianos, 03 colombianos, 02 venezolanos y 01 peruano"
9888,12580,"2 brasileños, 09 colombianos, 08 ecuatorianos, 02 salvadoreños, 06 guatemaltecos, 01 guineano ,01 hondureño,01 nicaraguense y 10 venezolanos"
9893,12585,"01 dominicano 01 colombianos, 12 ecuatorianos, 03 peruano, 01 guatemaltecos, 03 hondureño,01 nicaraguense y 18 venezolanos"
9895,12587,"01 argentina , 01 brasileña, 1 colombianos, 07 ecuatorianos, 01 salvadoreño 04 gautemalteco, 1hondureño , 01 mauritabia, 05 dominicano 18 venezolanos"
10211,13174,"11 chinos, 05 venezolanos, 06 hondureños, 02 haitianos, 02 guatemaltecos, 15 ecuatorianos, 01 colombiano"
10216,13179,"2 cubanos , 3 ecuador ,06 venezolano, 16 mauritanos , 05 tchad, 04 guatemaltecos ,01 palestino"
10224,13187,14 venezolanos \n05 ecuatorianos . \n01 haitiano \n01 peruanos \n01 dominicano \n03 guatemalteca
10226,13189,"ecuador 11, kazajistán 03 ,venezuela 02 , colombiano 05"
10230,13193,05 ecuatorianos (03h 02 m). 01 cubano (01 h). 03 chinos (02 h 1m)
10232,13195,"02 rep. dominicana,11 venezuela, 03 colombianos, 01 peruano ,01 hondureño , 06 ecuatorianos"
10600,13563,27 ecuatoriana \n01 guatemalteca\n01 guineana\n02 mauritano \n01 peruano\n03 salvadoreño \n02 venezolano
10604,13567,03 camerunés \n02 colombiana\n03 cubana\n05 ecuatoriana \n05 guatemalteco \n01 mauritano \n01 nigeriano\n 01 venezolano
10605,13568,03 camerunés \n01 colombiana \n01 dominicano\n01 ecuatoriano \n04 ghanés \n06 guatemalteco \n03 nicaragüense \n03 yemeníes
10606,13569,06guatemaltecos\n01guatemalteca \n03 ecuatorianos\n08 togolenses\n01 veneciano \n01eritreano\n01marroqui\n01libanes\n01mauritano\n01cubana \n01 nicaragüense\n03 bangladesh\n02 nepalí\n01 indues
10607,13570,01 camerunés \n01 salvadoreño\n14 ecuatorianos\n01 togolesa\n01 mali \n08 guatemaltecos\n01 hondureño\n01 cubano \n01 colombiano \n01 guineano \n03 somalí \n03 nepalí
10608,13571,05 guatemaltecos\n03 angoleña\n01 austria \n01 camerunés \n01 china\n02 colombiana \n01 cubana\n04 ecuatoriano \n01 india \n01 dominicano\n01 salvadoreño

In [224]:
print(len(master)) # Nuevo total de filas
master['total_migrantes_traslado'].sum()

10886

np.int64(582522)

In [225]:
master.to_parquet(DATOS / "procesados" / "datos_limpios_concatenados.parquet", index=False)